#include <string.h>
#include <stdio.h>

#include "disassembler.h"

static const char *mnem_to_str(enum ppc_mnemonic mnem)
{
	switch(mnem)
	{
		case PPC_MNEM_ABS: return "abs";
		case PPC_MNEM_ABSO: return "abso";
		case PPC_MNEM_ADD: return "add";
		case PPC_MNEM_ADDC: return "addc";
		case PPC_MNEM_ADDCO: return "addco";
		case PPC_MNEM_ADDE: return "adde";
		case PPC_MNEM_ADDEO: return "addeo";
		case PPC_MNEM_ADDEX: return "addex";
		case PPC_MNEM_ADDG6S: return "addg6s";
		case PPC_MNEM_ADDI: return "addi";
		case PPC_MNEM_ADDIC: return "addic";
		case PPC_MNEM_ADDIS: return "addis";
		case PPC_MNEM_ADDME: return "addme";
		case PPC_MNEM_ADDMEO: return "addmeo";
		case PPC_MNEM_ADDO: return "addo";
		case PPC_MNEM_ADDPCIS: return "addpcis";
		case PPC_MNEM_ADDZE: return "addze";
		case PPC_MNEM_ADDZEO: return "addzeo";
		case PPC_MNEM_AND: return "and";
		case PPC_MNEM_ANDC: return "andc";
		case PPC_MNEM_ANDI: return "andi";
		case PPC_MNEM_ANDIS: return "andis";
		case PPC_MNEM_ATTN: return "attn";
		case PPC_MNEM_B: return "b";
		case PPC_MNEM_BA: return "ba";
		case PPC_MNEM_BBELR: return "bbelr";
		case PPC_MNEM_BBLELS: return "bblels";
		case PPC_MNEM_BC: return "bc";
		case PPC_MNEM_BCA: return "bca";
		case PPC_MNEM_BCCTR: return "bcctr";
		case PPC_MNEM_BCCTRL: return "bcctrl";
		case PPC_MNEM_BCDADD: return "bcdadd";
		case PPC_MNEM_BCDCFN: return "bcdcfn";
		case PPC_MNEM_BCDCFSQ: return "bcdcfsq";
		case PPC_MNEM_BCDCFZ: return "bcdcfz";
		case PPC_MNEM_BCDCPSGN: return "bcdcpsgn";
		case PPC_MNEM_BCDCTN: return "bcdctn";
		case PPC_MNEM_BCDCTSQ: return "bcdctsq";
		case PPC_MNEM_BCDCTZ: return "bcdctz";
		case PPC_MNEM_BCDS: return "bcds";
		case PPC_MNEM_BCDSETSGN: return "bcdsetsgn";
		case PPC_MNEM_BCDSR: return "bcdsr";
		case PPC_MNEM_BCDSUB: return "bcdsub";
		case PPC_MNEM_BCDTRUNC: return "bcdtrunc";
		case PPC_MNEM_BCDUS: return "bcdus";
		case PPC_MNEM_BCDUTRUNC: return "bcdutrunc";
		case PPC_MNEM_BCL: return "bcl";
		case PPC_MNEM_BCLA: return "bcla";
		case PPC_MNEM_BCLR: return "bclr";
		case PPC_MNEM_BCLRL: return "bclrl";
		case PPC_MNEM_BCTAR: return "bctar";
		case PPC_MNEM_BCTARL: return "bctarl";
		case PPC_MNEM_BCTR: return "bctr";
		case PPC_MNEM_BCTRL: return "bctrl";
		case PPC_MNEM_BDNZ: return "bdnz";
		case PPC_MNEM_BDNZA: return "bdnza";
		case PPC_MNEM_BDNZF: return "bdnzf";
		case PPC_MNEM_BDNZFA: return "bdnzfa";
		case PPC_MNEM_BDNZFL: return "bdnzfl";
		case PPC_MNEM_BDNZFLA: return "bdnzfla";
		case PPC_MNEM_BDNZFLR: return "bdnzflr";
		case PPC_MNEM_BDNZFLRL: return "bdnzflrl";
		case PPC_MNEM_BDNZL: return "bdnzl";
		case PPC_MNEM_BDNZLA: return "bdnzla";
		case PPC_MNEM_BDNZLR: return "bdnzlr";
		case PPC_MNEM_BDNZLRL: return "bdnzlrl";
		case PPC_MNEM_BDNZT: return "bdnzt";
		case PPC_MNEM_BDNZTA: return "bdnzta";
		case PPC_MNEM_BDNZTL: return "bdnztl";
		case PPC_MNEM_BDNZTLA: return "bdnztla";
		case PPC_MNEM_BDNZTLR: return "bdnztlr";
		case PPC_MNEM_BDNZTLRL: return "bdnztlrl";
		case PPC_MNEM_BDZ: return "bdz";
		case PPC_MNEM_BDZA: return "bdza";
		case PPC_MNEM_BDZF: return "bdzf";
		case PPC_MNEM_BDZFA: return "bdzfa";
		case PPC_MNEM_BDZFL: return "bdzfl";
		case PPC_MNEM_BDZFLA: return "bdzfla";
		case PPC_MNEM_BDZFLR: return "bdzflr";
		case PPC_MNEM_BDZFLRL: return "bdzflrl";
		case PPC_MNEM_BDZL: return "bdzl";
		case PPC_MNEM_BDZLA: return "bdzla";
		case PPC_MNEM_BDZLR: return "bdzlr";
		case PPC_MNEM_BDZLRL: return "bdzlrl";
		case PPC_MNEM_BDZT: return "bdzt";
		case PPC_MNEM_BDZTA: return "bdzta";
		case PPC_MNEM_BDZTL: return "bdztl";
		case PPC_MNEM_BDZTLA: return "bdztla";
		case PPC_MNEM_BDZTLR: return "bdztlr";
		case PPC_MNEM_BDZTLRL: return "bdztlrl";
		case PPC_MNEM_BEQ: return "beq";
		case PPC_MNEM_BEQA: return "beqa";
		case PPC_MNEM_BEQCTR: return "beqctr";
		case PPC_MNEM_BEQCTRL: return "beqctrl";
		case PPC_MNEM_BEQL: return "beql";
		case PPC_MNEM_BEQLA: return "beqla";
		case PPC_MNEM_BEQLR: return "beqlr";
		case PPC_MNEM_BEQLRL: return "beqlrl";
		case PPC_MNEM_BGE: return "bge";
		case PPC_MNEM_BGEA: return "bgea";
		case PPC_MNEM_BGECTR: return "bgectr";
		case PPC_MNEM_BGECTRL: return "bgectrl";
		case PPC_MNEM_BGEL: return "bgel";
		case PPC_MNEM_BGELA: return "bgela";
		case PPC_MNEM_BGELR: return "bgelr";
		case PPC_MNEM_BGELRL: return "bgelrl";
		case PPC_MNEM_BGT: return "bgt";
		case PPC_MNEM_BGTA: return "bgta";
		case PPC_MNEM_BGTCTR: return "bgtctr";
		case PPC_MNEM_BGTCTRL: return "bgtctrl";
		case PPC_MNEM_BGTL: return "bgtl";
		case PPC_MNEM_BGTLA: return "bgtla";
		case PPC_MNEM_BGTLR: return "bgtlr";
		case PPC_MNEM_BGTLRL: return "bgtlrl";
		case PPC_MNEM_BL: return "bl";
		case PPC_MNEM_BLA: return "bla";
		case PPC_MNEM_BLE: return "ble";
		case PPC_MNEM_BLEA: return "blea";
		case PPC_MNEM_BLECTR: return "blectr";
		case PPC_MNEM_BLECTRL: return "blectrl";
		case PPC_MNEM_BLEL: return "blel";
		case PPC_MNEM_BLELA: return "blela";
		case PPC_MNEM_BLELR: return "blelr";
		case PPC_MNEM_BLELRL: return "blelrl";
		case PPC_MNEM_BLR: return "blr";
		case PPC_MNEM_BLRL: return "blrl";
		case PPC_MNEM_BLT: return "blt";
		case PPC_MNEM_BLTA: return "blta";
		case PPC_MNEM_BLTCTR: return "bltctr";
		case PPC_MNEM_BLTCTRL: return "bltctrl";
		case PPC_MNEM_BLTL: return "bltl";
		case PPC_MNEM_BLTLA: return "bltla";
		case PPC_MNEM_BLTLR: return "bltlr";
		case PPC_MNEM_BLTLRL: return "bltlrl";
		case PPC_MNEM_BNE: return "bne";
		case PPC_MNEM_BNEA: return "bnea";
		case PPC_MNEM_BNECTR: return "bnectr";
		case PPC_MNEM_BNECTRL: return "bnectrl";
		case PPC_MNEM_BNEL: return "bnel";
		case PPC_MNEM_BNELA: return "bnela";
		case PPC_MNEM_BNELR: return "bnelr";
		case PPC_MNEM_BNELRL: return "bnelrl";
		case PPC_MNEM_BNS: return "bns";
		case PPC_MNEM_BNSA: return "bnsa";
		case PPC_MNEM_BNSCTR: return "bnsctr";
		case PPC_MNEM_BNSCTRL: return "bnsctrl";
		case PPC_MNEM_BNSL: return "bnsl";
		case PPC_MNEM_BNSLA: return "bnsla";
		case PPC_MNEM_BNSLR: return "bnslr";
		case PPC_MNEM_BNSLRL: return "bnslrl";
		case PPC_MNEM_BPERMD: return "bpermd";
		case PPC_MNEM_BSO: return "bso";
		case PPC_MNEM_BSOA: return "bsoa";
		case PPC_MNEM_BSOCTR: return "bsoctr";
		case PPC_MNEM_BSOCTRL: return "bsoctrl";
		case PPC_MNEM_BSOL: return "bsol";
		case PPC_MNEM_BSOLA: return "bsola";
		case PPC_MNEM_BSOLR: return "bsolr";
		case PPC_MNEM_BSOLRL: return "bsolrl";
		case PPC_MNEM_CBCDTD: return "cbcdtd";
		case PPC_MNEM_CDTBCD: return "cdtbcd";
		case PPC_MNEM_CLCS: return "clcs";
		case PPC_MNEM_CLF: return "clf";
		case PPC_MNEM_CLI: return "cli";
		case PPC_MNEM_CLRBHRB: return "clrbhrb";
		case PPC_MNEM_CLRLDI: return "clrldi";
		case PPC_MNEM_CLRLWI: return "clrlwi";
		case PPC_MNEM_CMPB: return "cmpb";
		case PPC_MNEM_CMPD: return "cmpd";
		case PPC_MNEM_CMPDI: return "cmpdi";
		case PPC_MNEM_CMPEQB: return "cmpeqb";
		case PPC_MNEM_CMPLD: return "cmpld";
		case PPC_MNEM_CMPLDI: return "cmpldi";
		case PPC_MNEM_CMPLW: return "cmplw";
		case PPC_MNEM_CMPLWI: return "cmplwi";
		case PPC_MNEM_CMPRB: return "cmprb";
		case PPC_MNEM_CMPW: return "cmpw";
		case PPC_MNEM_CMPWI: return "cmpwi";
		case PPC_MNEM_CNTLZD: return "cntlzd";
		case PPC_MNEM_CNTLZW: return "cntlzw";
		case PPC_MNEM_CNTTZD: return "cnttzd";
		case PPC_MNEM_CNTTZW: return "cnttzw";
		case PPC_MNEM_COPY: return "copy";
		case PPC_MNEM_CPABORT: return "cpabort";
		case PPC_MNEM_CRAND: return "crand";
		case PPC_MNEM_CRANDC: return "crandc";
		case PPC_MNEM_CRCLR: return "crclr";
		case PPC_MNEM_CREQV: return "creqv";
		case PPC_MNEM_CRMOVE: return "crmove";
		case PPC_MNEM_CRNAND: return "crnand";
		case PPC_MNEM_CRNOR: return "crnor";
		case PPC_MNEM_CRNOT: return "crnot";
		case PPC_MNEM_CROR: return "cror";
		case PPC_MNEM_CRORC: return "crorc";
		case PPC_MNEM_CRSET: return "crset";
		case PPC_MNEM_CRXOR: return "crxor";
		case PPC_MNEM_DADD: return "dadd";
		case PPC_MNEM_DADDQ: return "daddq";
		case PPC_MNEM_DARN: return "darn";
		case PPC_MNEM_DCBA: return "dcba";
		case PPC_MNEM_DCBAL: return "dcbal";
		case PPC_MNEM_DCBF: return "dcbf";
		case PPC_MNEM_DCBFEP: return "dcbfep";
		case PPC_MNEM_DCBFL: return "dcbfl";
		case PPC_MNEM_DCBI: return "dcbi";
		case PPC_MNEM_DCBLC: return "dcblc";
		case PPC_MNEM_DCBLCE: return "dcblce";
		case PPC_MNEM_DCBLQ: return "dcblq";
		case PPC_MNEM_DCBST: return "dcbst";
		case PPC_MNEM_DCBSTEP: return "dcbstep";
		case PPC_MNEM_DCBT: return "dcbt";
		case PPC_MNEM_DCBTEP: return "dcbtep";
		case PPC_MNEM_DCBTLS: return "dcbtls";
		case PPC_MNEM_DCBTLSE: return "dcbtlse";
		case PPC_MNEM_DCBTST: return "dcbtst";
		case PPC_MNEM_DCBTSTEP: return "dcbtstep";
		case PPC_MNEM_DCBTSTLS: return "dcbtstls";
		case PPC_MNEM_DCBTSTLSE: return "dcbtstlse";
		case PPC_MNEM_DCBTSTT: return "dcbtstt";
		case PPC_MNEM_DCBTT: return "dcbtt";
		case PPC_MNEM_DCBZ: return "dcbz";
		case PPC_MNEM_DCBZEP: return "dcbzep";
		case PPC_MNEM_DCBZL: return "dcbzl";
		case PPC_MNEM_DCBZ_L: return "dcbz_l";
		case PPC_MNEM_DCCCI: return "dccci";
		case PPC_MNEM_DCFFIX: return "dcffix";
		case PPC_MNEM_DCFFIXQ: return "dcffixq";
		case PPC_MNEM_DCI: return "dci";
		case PPC_MNEM_DCLST: return "dclst";
		case PPC_MNEM_DCMPO: return "dcmpo";
		case PPC_MNEM_DCMPOQ: return "dcmpoq";
		case PPC_MNEM_DCMPU: return "dcmpu";
		case PPC_MNEM_DCMPUQ: return "dcmpuq";
		case PPC_MNEM_DCREAD: return "dcread";
		case PPC_MNEM_DCTDP: return "dctdp";
		case PPC_MNEM_DCTFIX: return "dctfix";
		case PPC_MNEM_DCTFIXQ: return "dctfixq";
		case PPC_MNEM_DCTQPQ: return "dctqpq";
		case PPC_MNEM_DDEDPD: return "ddedpd";
		case PPC_MNEM_DDEDPDQ: return "ddedpdq";
		case PPC_MNEM_DDIV: return "ddiv";
		case PPC_MNEM_DDIVQ: return "ddivq";
		case PPC_MNEM_DENBCD: return "denbcd";
		case PPC_MNEM_DENBCDQ: return "denbcdq";
		case PPC_MNEM_DIEX: return "diex";
		case PPC_MNEM_DIEXQ: return "diexq";
		case PPC_MNEM_DIV: return "div";
		case PPC_MNEM_DIVD: return "divd";
		case PPC_MNEM_DIVDE: return "divde";
		case PPC_MNEM_DIVDEO: return "divdeo";
		case PPC_MNEM_DIVDEU: return "divdeu";
		case PPC_MNEM_DIVDEUO: return "divdeuo";
		case PPC_MNEM_DIVDO: return "divdo";
		case PPC_MNEM_DIVDU: return "divdu";
		case PPC_MNEM_DIVDUO: return "divduo";
		case PPC_MNEM_DIVO: return "divo";
		case PPC_MNEM_DIVS: return "divs";
		case PPC_MNEM_DIVSO: return "divso";
		case PPC_MNEM_DIVW: return "divw";
		case PPC_MNEM_DIVWE: return "divwe";
		case PPC_MNEM_DIVWEO: return "divweo";
		case PPC_MNEM_DIVWEU: return "divweu";
		case PPC_MNEM_DIVWEUO: return "divweuo";
		case PPC_MNEM_DIVWO: return "divwo";
		case PPC_MNEM_DIVWU: return "divwu";
		case PPC_MNEM_DIVWUO: return "divwuo";
		case PPC_MNEM_DLMZB: return "dlmzb";
		case PPC_MNEM_DMUL: return "dmul";
		case PPC_MNEM_DMULQ: return "dmulq";
		case PPC_MNEM_DNH: return "dnh";
		case PPC_MNEM_DNI: return "dni";
		case PPC_MNEM_DOZ: return "doz";
		case PPC_MNEM_DOZE: return "doze";
		case PPC_MNEM_DOZI: return "dozi";
		case PPC_MNEM_DOZO: return "dozo";
		case PPC_MNEM_DQUA: return "dqua";
		case PPC_MNEM_DQUAI: return "dquai";
		case PPC_MNEM_DQUAIQ: return "dquaiq";
		case PPC_MNEM_DQUAQ: return "dquaq";
		case PPC_MNEM_DRDPQ: return "drdpq";
		case PPC_MNEM_DRINTN: return "drintn";
		case PPC_MNEM_DRINTNQ: return "drintnq";
		case PPC_MNEM_DRINTX: return "drintx";
		case PPC_MNEM_DRINTXQ: return "drintxq";
		case PPC_MNEM_DRRND: return "drrnd";
		case PPC_MNEM_DRRNDQ: return "drrndq";
		case PPC_MNEM_DRSP: return "drsp";
		case PPC_MNEM_DSCLI: return "dscli";
		case PPC_MNEM_DSCLIQ: return "dscliq";
		case PPC_MNEM_DSCRI: return "dscri";
		case PPC_MNEM_DSCRIQ: return "dscriq";
		case PPC_MNEM_DSN: return "dsn";
		case PPC_MNEM_DSS: return "dss";
		case PPC_MNEM_DSSALL: return "dssall";
		case PPC_MNEM_DST: return "dst";
		case PPC_MNEM_DSTST: return "dstst";
		case PPC_MNEM_DSTSTT: return "dststt";
		case PPC_MNEM_DSTT: return "dstt";
		case PPC_MNEM_DSUB: return "dsub";
		case PPC_MNEM_DSUBQ: return "dsubq";
		case PPC_MNEM_DTSTDC: return "dtstdc";
		case PPC_MNEM_DTSTDCQ: return "dtstdcq";
		case PPC_MNEM_DTSTDG: return "dtstdg";
		case PPC_MNEM_DTSTDGQ: return "dtstdgq";
		case PPC_MNEM_DTSTEX: return "dtstex";
		case PPC_MNEM_DTSTEXQ: return "dtstexq";
		case PPC_MNEM_DTSTSF: return "dtstsf";
		case PPC_MNEM_DTSTSFI: return "dtstsfi";
		case PPC_MNEM_DTSTSFIQ: return "dtstsfiq";
		case PPC_MNEM_DTSTSFQ: return "dtstsfq";
		case PPC_MNEM_DXEX: return "dxex";
		case PPC_MNEM_DXEXQ: return "dxexq";
		case PPC_MNEM_ECIWX: return "eciwx";
		case PPC_MNEM_ECOWX: return "ecowx";
		case PPC_MNEM_EFDCFUF: return "efdcfuf";
		case PPC_MNEM_EFDCTH: return "efdcth";
		case PPC_MNEM_EFDCTSF: return "efdctsf";
		case PPC_MNEM_EFDCTSI: return "efdctsi";
		case PPC_MNEM_EFDCTUF: return "efdctuf";
		case PPC_MNEM_EFDCTUI: return "efdctui";
		case PPC_MNEM_EFSADD: return "efsadd";
		case PPC_MNEM_EFSCFH: return "efscfh";
		case PPC_MNEM_EFSCFSF: return "efscfsf";
		case PPC_MNEM_EFSCFSI: return "efscfsi";
		case PPC_MNEM_EFSCFUF: return "efscfuf";
		case PPC_MNEM_EFSCFUI: return "efscfui";
		case PPC_MNEM_EFSCTSIZ: return "efsctsiz";
		case PPC_MNEM_EFSCTUIZ: return "efsctuiz";
		case PPC_MNEM_EFSDIV: return "efsdiv";
		case PPC_MNEM_EFSMSUB: return "efsmsub";
		case PPC_MNEM_EFSMUL: return "efsmul";
		case PPC_MNEM_EFSNABS: return "efsnabs";
		case PPC_MNEM_EFSNMADD: return "efsnmadd";
		case PPC_MNEM_EFSNMSUB: return "efsnmsub";
		case PPC_MNEM_EFSSUB: return "efssub";
		case PPC_MNEM_EHPRIV: return "ehpriv";
		case PPC_MNEM_EIEIO: return "eieio";
		case PPC_MNEM_EQV: return "eqv";
		case PPC_MNEM_ERATILX: return "eratilx";
		case PPC_MNEM_ERATIVAX: return "erativax";
		case PPC_MNEM_ERATRE: return "eratre";
		case PPC_MNEM_ERATSX: return "eratsx";
		case PPC_MNEM_ERATWE: return "eratwe";
		case PPC_MNEM_EVADDSMIAAW: return "evaddsmiaaw";
		case PPC_MNEM_EVAND: return "evand";
		case PPC_MNEM_EVANDC: return "evandc";
		case PPC_MNEM_EVCMPEQ: return "evcmpeq";
		case PPC_MNEM_EVCMPLTU: return "evcmpltu";
		case PPC_MNEM_EVEQV: return "eveqv";
		case PPC_MNEM_EVEXTSB: return "evextsb";
		case PPC_MNEM_EVEXTSH: return "evextsh";
		case PPC_MNEM_EVFSCFH: return "evfscfh";
		case PPC_MNEM_EVFSCFSF: return "evfscfsf";
		case PPC_MNEM_EVFSCFSI: return "evfscfsi";
		case PPC_MNEM_EVFSCFUF: return "evfscfuf";
		case PPC_MNEM_EVFSCFUI: return "evfscfui";
		case PPC_MNEM_EVFSCTSIZ: return "evfsctsiz";
		case PPC_MNEM_EVFSCTUIZ: return "evfsctuiz";
		case PPC_MNEM_EVFSDIV: return "evfsdiv";
		case PPC_MNEM_EVFSMSUB: return "evfsmsub";
		case PPC_MNEM_EVFSNABS: return "evfsnabs";
		case PPC_MNEM_EVFSNMADD: return "evfsnmadd";
		case PPC_MNEM_EVFSNMSUB: return "evfsnmsub";
		case PPC_MNEM_EVFSSQRT: return "evfssqrt";
		case PPC_MNEM_EVFSSUB: return "evfssub";
		case PPC_MNEM_EVLDD: return "evldd";
		case PPC_MNEM_EVLDDEPX: return "evlddepx";
		case PPC_MNEM_EVLDH: return "evldh";
		case PPC_MNEM_EVLDW: return "evldw";
		case PPC_MNEM_EVLHHESPLAT: return "evlhhesplat";
		case PPC_MNEM_EVMHESMF: return "evmhesmf";
		case PPC_MNEM_EVMHESMFAAW: return "evmhesmfaaw";
		case PPC_MNEM_EVMHESMFANW: return "evmhesmfanw";
		case PPC_MNEM_EVMHESMI: return "evmhesmi";
		case PPC_MNEM_EVMHESMIANW: return "evmhesmianw";
		case PPC_MNEM_EVMHESSFAAW: return "evmhessfaaw";
		case PPC_MNEM_EVMHESSFANW: return "evmhessfanw";
		case PPC_MNEM_EVMHESSIANW: return "evmhessianw";
		case PPC_MNEM_EVMHEUMIANW: return "evmheumianw";
		case PPC_MNEM_EVMHOGUMIAA: return "evmhogumiaa";
		case PPC_MNEM_EVMHOGUMIAN: return "evmhogumian";
		case PPC_MNEM_EVMHOSSIAAW: return "evmhossiaaw";
		case PPC_MNEM_EVMHOSSIANW: return "evmhossianw";
		case PPC_MNEM_EVMHOUMIA: return "evmhoumia";
		case PPC_MNEM_EVMWHSSIAN: return "evmwhssian";
		case PPC_MNEM_EVMWHSSMAA: return "evmwhssmaa";
		case PPC_MNEM_EVMWHUMIA: return "evmwhumia";
		case PPC_MNEM_EVMWLSMF: return "evmwlsmf";
		case PPC_MNEM_EVMWLSMFAAW: return "evmwlsmfaaw";
		case PPC_MNEM_EVMWLSMFANW: return "evmwlsmfanw";
		case PPC_MNEM_EVMWLSMIANW: return "evmwlsmianw";
		case PPC_MNEM_EVMWLSSFAAW: return "evmwlssfaaw";
		case PPC_MNEM_EVMWLSSFANW: return "evmwlssfanw";
		case PPC_MNEM_EVMWLUMIANW: return "evmwlumianw";
		case PPC_MNEM_EVMWLUSIANW: return "evmwlusianw";
		case PPC_MNEM_EVMWSMF: return "evmwsmf";
		case PPC_MNEM_EVMWSMFAA: return "evmwsmfaa";
		case PPC_MNEM_EVMWSMFAN: return "evmwsmfan";
		case PPC_MNEM_EVMWSSF: return "evmwssf";
		case PPC_MNEM_EVMWSSFAA: return "evmwssfaa";
		case PPC_MNEM_EVMWSSFAN: return "evmwssfan";
		case PPC_MNEM_EVNEG: return "evneg";
		case PPC_MNEM_EVNOR: return "evnor";
		case PPC_MNEM_EVORC: return "evorc";
		case PPC_MNEM_EVSTDDEPX: return "evstddepx";
		case PPC_MNEM_EVSTWHO: return "evstwho";
		case PPC_MNEM_EVSTWHOX: return "evstwhox";
		case PPC_MNEM_EVSUBFSMIAAW: return "evsubfsmiaaw";
		case PPC_MNEM_EVSUBFSSIAAW: return "evsubfssiaaw";
		case PPC_MNEM_EVSUBFUMIAAW: return "evsubfumiaaw";
		case PPC_MNEM_EVSUBFUSIAAW: return "evsubfusiaaw";
		case PPC_MNEM_EXTSB: return "extsb";
		case PPC_MNEM_EXTSH: return "extsh";
		case PPC_MNEM_EXTSW: return "extsw";
		case PPC_MNEM_EXTSWSLI: return "extswsli";
		case PPC_MNEM_FABS: return "fabs";
		case PPC_MNEM_FADD: return "fadd";
		case PPC_MNEM_FADDS: return "fadds";
		case PPC_MNEM_FCFID: return "fcfid";
		case PPC_MNEM_FCFIDS: return "fcfids";
		case PPC_MNEM_FCFIDU: return "fcfidu";
		case PPC_MNEM_FCFIDUS: return "fcfidus";
		case PPC_MNEM_FCMPO: return "fcmpo";
		case PPC_MNEM_FCMPU: return "fcmpu";
		case PPC_MNEM_FCPSGN: return "fcpsgn";
		case PPC_MNEM_FCTID: return "fctid";
		case PPC_MNEM_FCTIDU: return "fctidu";
		case PPC_MNEM_FCTIDUZ: return "fctiduz";
		case PPC_MNEM_FCTIDZ: return "fctidz";
		case PPC_MNEM_FCTIW: return "fctiw";
		case PPC_MNEM_FCTIWU: return "fctiwu";
		case PPC_MNEM_FCTIWUZ: return "fctiwuz";
		case PPC_MNEM_FCTIWZ: return "fctiwz";
		case PPC_MNEM_FDIV: return "fdiv";
		case PPC_MNEM_FDIVS: return "fdivs";
		case PPC_MNEM_FMADD: return "fmadd";
		case PPC_MNEM_FMADDS: return "fmadds";
		case PPC_MNEM_FMR: return "fmr";
		case PPC_MNEM_FMRGEW: return "fmrgew";
		case PPC_MNEM_FMRGOW: return "fmrgow";
		case PPC_MNEM_FMSUB: return "fmsub";
		case PPC_MNEM_FMSUBS: return "fmsubs";
		case PPC_MNEM_FMUL: return "fmul";
		case PPC_MNEM_FMULS: return "fmuls";
		case PPC_MNEM_FNABS: return "fnabs";
		case PPC_MNEM_FNEG: return "fneg";
		case PPC_MNEM_FNMADD: return "fnmadd";
		case PPC_MNEM_FNMADDS: return "fnmadds";
		case PPC_MNEM_FNMSUB: return "fnmsub";
		case PPC_MNEM_FNMSUBS: return "fnmsubs";
		case PPC_MNEM_FRE: return "fre";
		case PPC_MNEM_FRES: return "fres";
		case PPC_MNEM_FRIM: return "frim";
		case PPC_MNEM_FRIN: return "frin";
		case PPC_MNEM_FRIP: return "frip";
		case PPC_MNEM_FRIZ: return "friz";
		case PPC_MNEM_FRSP: return "frsp";
		case PPC_MNEM_FRSQRTE: return "frsqrte";
		case PPC_MNEM_FRSQRTES: return "frsqrtes";
		case PPC_MNEM_FSEL: return "fsel";
		case PPC_MNEM_FSQRT: return "fsqrt";
		case PPC_MNEM_FSQRTS: return "fsqrts";
		case PPC_MNEM_FSUB: return "fsub";
		case PPC_MNEM_FSUBS: return "fsubs";
		case PPC_MNEM_FTDIV: return "ftdiv";
		case PPC_MNEM_FTSQRT: return "ftsqrt";
		case PPC_MNEM_HRFID: return "hrfid";
		case PPC_MNEM_HWSYNC: return "hwsync";
		case PPC_MNEM_ICBI: return "icbi";
		case PPC_MNEM_ICBIEP: return "icbiep";
		case PPC_MNEM_ICBLC: return "icblc";
		case PPC_MNEM_ICBLCE: return "icblce";
		case PPC_MNEM_ICBLQ: return "icblq";
		case PPC_MNEM_ICBT: return "icbt";
		case PPC_MNEM_ICCCI: return "iccci";
		case PPC_MNEM_ICI: return "ici";
		case PPC_MNEM_ICREAD: return "icread";
		case PPC_MNEM_ICSWEPX: return "icswepx";
		case PPC_MNEM_ICSWX: return "icswx";
		case PPC_MNEM_ISEL: return "isel";
		case PPC_MNEM_ISELEQ: return "iseleq";
		case PPC_MNEM_ISELGT: return "iselgt";
		case PPC_MNEM_ISELLT: return "isellt";
		case PPC_MNEM_ISYNC: return "isync";
		case PPC_MNEM_LBARX: return "lbarx";
		case PPC_MNEM_LBDCBX: return "lbdcbx";
		case PPC_MNEM_LBDX: return "lbdx";
		case PPC_MNEM_LBEPX: return "lbepx";
		case PPC_MNEM_LBZ: return "lbz";
		case PPC_MNEM_LBZCIX: return "lbzcix";
		case PPC_MNEM_LBZU: return "lbzu";
		case PPC_MNEM_LBZUX: return "lbzux";
		case PPC_MNEM_LBZX: return "lbzx";
		case PPC_MNEM_LD: return "ld";
		case PPC_MNEM_LDARX: return "ldarx";
		case PPC_MNEM_LDAT: return "ldat";
		case PPC_MNEM_LDAWX: return "ldawx";
		case PPC_MNEM_LDBRX: return "ldbrx";
		case PPC_MNEM_LDCIX: return "ldcix";
		case PPC_MNEM_LDDX: return "lddx";
		case PPC_MNEM_LDMX: return "ldmx";
		case PPC_MNEM_LDU: return "ldu";
		case PPC_MNEM_LDUX: return "ldux";
		case PPC_MNEM_LDX: return "ldx";
		case PPC_MNEM_LFD: return "lfd";
		case PPC_MNEM_LFDDX: return "lfddx";
		case PPC_MNEM_LFDEPX: return "lfdepx";
		case PPC_MNEM_LFDP: return "lfdp";
		case PPC_MNEM_LFDPX: return "lfdpx";
		case PPC_MNEM_LFDU: return "lfdu";
		case PPC_MNEM_LFDUX: return "lfdux";
		case PPC_MNEM_LFDX: return "lfdx";
		case PPC_MNEM_LFIWAX: return "lfiwax";
		case PPC_MNEM_LFIWZX: return "lfiwzx";
		case PPC_MNEM_LFQUX: return "lfqux";
		case PPC_MNEM_LFQX: return "lfqx";
		case PPC_MNEM_LFS: return "lfs";
		case PPC_MNEM_LFSU: return "lfsu";
		case PPC_MNEM_LFSUX: return "lfsux";
		case PPC_MNEM_LFSX: return "lfsx";
		case PPC_MNEM_LHA: return "lha";
		case PPC_MNEM_LHARX: return "lharx";
		case PPC_MNEM_LHAU: return "lhau";
		case PPC_MNEM_LHAUX: return "lhaux";
		case PPC_MNEM_LHAX: return "lhax";
		case PPC_MNEM_LHBRX: return "lhbrx";
		case PPC_MNEM_LHDCBX: return "lhdcbx";
		case PPC_MNEM_LHDX: return "lhdx";
		case PPC_MNEM_LHEPX: return "lhepx";
		case PPC_MNEM_LHZ: return "lhz";
		case PPC_MNEM_LHZCIX: return "lhzcix";
		case PPC_MNEM_LHZU: return "lhzu";
		case PPC_MNEM_LHZUX: return "lhzux";
		case PPC_MNEM_LHZX: return "lhzx";
		case PPC_MNEM_LI: return "li";
		case PPC_MNEM_LIS: return "lis";
		case PPC_MNEM_LM: return "lm";
		case PPC_MNEM_LMW: return "lmw";
		case PPC_MNEM_LNIA: return "lnia";
		case PPC_MNEM_LQ: return "lq";
		case PPC_MNEM_LQARX: return "lqarx";
		case PPC_MNEM_LQFCMUX: return "lqfcmux";
		case PPC_MNEM_LSCBX: return "lscbx";
		case PPC_MNEM_LSI: return "lsi";
		case PPC_MNEM_LSWI: return "lswi";
		case PPC_MNEM_LSWX: return "lswx";
		case PPC_MNEM_LSX: return "lsx";
		case PPC_MNEM_LU: return "lu";
		case PPC_MNEM_LUX: return "lux";
		case PPC_MNEM_LVEBX: return "lvebx";
		case PPC_MNEM_LVEHX: return "lvehx";
		case PPC_MNEM_LVEPX: return "lvepx";
		case PPC_MNEM_LVEPXL: return "lvepxl";
		case PPC_MNEM_LVEWX: return "lvewx";
		case PPC_MNEM_LVEXBX: return "lvexbx";
		case PPC_MNEM_LVEXHX: return "lvexhx";
		case PPC_MNEM_LVEXWX: return "lvexwx";
		case PPC_MNEM_LVLX: return "lvlx";
		case PPC_MNEM_LVRX: return "lvrx";
		case PPC_MNEM_LVSL: return "lvsl";
		case PPC_MNEM_LVSM: return "lvsm";
		case PPC_MNEM_LVSR: return "lvsr";
		case PPC_MNEM_LVSWX: return "lvswx";
		case PPC_MNEM_LVSWXL: return "lvswxl";
		case PPC_MNEM_LVTLX: return "lvtlx";
		case PPC_MNEM_LVTLXL: return "lvtlxl";
		case PPC_MNEM_LVTRX: return "lvtrx";
		case PPC_MNEM_LVTRXL: return "lvtrxl";
		case PPC_MNEM_LVX: return "lvx";
		case PPC_MNEM_LVXL: return "lvxl";
		case PPC_MNEM_LWA: return "lwa";
		case PPC_MNEM_LWARX: return "lwarx";
		case PPC_MNEM_LWAT: return "lwat";
		case PPC_MNEM_LWAUX: return "lwaux";
		case PPC_MNEM_LWAX: return "lwax";
		case PPC_MNEM_LWBRX: return "lwbrx";
		case PPC_MNEM_LWDCBX: return "lwdcbx";
		case PPC_MNEM_LWDX: return "lwdx";
		case PPC_MNEM_LWEPX: return "lwepx";
		case PPC_MNEM_LWFCMUX: return "lwfcmux";
		case PPC_MNEM_LWSYNC: return "lwsync";
		case PPC_MNEM_LWZ: return "lwz";
		case PPC_MNEM_LWZCIX: return "lwzcix";
		case PPC_MNEM_LWZU: return "lwzu";
		case PPC_MNEM_LWZUX: return "lwzux";
		case PPC_MNEM_LWZX: return "lwzx";
		case PPC_MNEM_LXSD: return "lxsd";
		case PPC_MNEM_LXSDX: return "lxsdx";
		case PPC_MNEM_LXSIBZX: return "lxsibzx";
		case PPC_MNEM_LXSIHZX: return "lxsihzx";
		case PPC_MNEM_LXSIWAX: return "lxsiwax";
		case PPC_MNEM_LXSIWZX: return "lxsiwzx";
		case PPC_MNEM_LXSSP: return "lxssp";
		case PPC_MNEM_LXSSPX: return "lxsspx";
		case PPC_MNEM_LXV: return "lxv";
		case PPC_MNEM_LXVB16X: return "lxvb16x";
		case PPC_MNEM_LXVD2X: return "lxvd2x";
		case PPC_MNEM_LXVDSX: return "lxvdsx";
		case PPC_MNEM_LXVH8X: return "lxvh8x";
		case PPC_MNEM_LXVL: return "lxvl";
		case PPC_MNEM_LXVLL: return "lxvll";
		case PPC_MNEM_LXVW4X: return "lxvw4x";
		case PPC_MNEM_LXVWSX: return "lxvwsx";
		case PPC_MNEM_LXVX: return "lxvx";
		case PPC_MNEM_MACCHW: return "macchw";
		case PPC_MNEM_MACCHWO: return "macchwo";
		case PPC_MNEM_MACCHWS: return "macchws";
		case PPC_MNEM_MACCHWSO: return "macchwso";
		case PPC_MNEM_MACCHWSU: return "macchwsu";
		case PPC_MNEM_MACCHWSUO: return "macchwsuo";
		case PPC_MNEM_MACCHWU: return "macchwu";
		case PPC_MNEM_MACCHWUO: return "macchwuo";
		case PPC_MNEM_MACHHW: return "machhw";
		case PPC_MNEM_MACHHWO: return "machhwo";
		case PPC_MNEM_MACHHWS: return "machhws";
		case PPC_MNEM_MACHHWSO: return "machhwso";
		case PPC_MNEM_MACHHWSU: return "machhwsu";
		case PPC_MNEM_MACHHWSUO: return "machhwsuo";
		case PPC_MNEM_MACHHWU: return "machhwu";
		case PPC_MNEM_MACHHWUO: return "machhwuo";
		case PPC_MNEM_MACLHW: return "maclhw";
		case PPC_MNEM_MACLHWO: return "maclhwo";
		case PPC_MNEM_MACLHWS: return "maclhws";
		case PPC_MNEM_MACLHWSO: return "maclhwso";
		case PPC_MNEM_MACLHWSU: return "maclhwsu";
		case PPC_MNEM_MACLHWSUO: return "maclhwsuo";
		case PPC_MNEM_MACLHWU: return "maclhwu";
		case PPC_MNEM_MACLHWUO: return "maclhwuo";
		case PPC_MNEM_MADDHD: return "maddhd";
		case PPC_MNEM_MADDHDU: return "maddhdu";
		case PPC_MNEM_MADDLD: return "maddld";
		case PPC_MNEM_MASKG: return "maskg";
		case PPC_MNEM_MASKIR: return "maskir";
		case PPC_MNEM_MBAR: return "mbar";
		case PPC_MNEM_MCRF: return "mcrf";
		case PPC_MNEM_MCRFS: return "mcrfs";
		case PPC_MNEM_MCRXR: return "mcrxr";
		case PPC_MNEM_MCRXRX: return "mcrxrx";
		case PPC_MNEM_MDOIO: return "mdoio";
		case PPC_MNEM_MDOOM: return "mdoom";
		case PPC_MNEM_MFAPIDI: return "mfapidi";
		case PPC_MNEM_MFASR: return "mfasr";
		case PPC_MNEM_MFBEAR: return "mfbear";
		case PPC_MNEM_MFBESR: return "mfbesr";
		case PPC_MNEM_MFBHRBE: return "mfbhrbe";
		case PPC_MNEM_MFBR0: return "mfbr0";
		case PPC_MNEM_MFBR1: return "mfbr1";
		case PPC_MNEM_MFBR2: return "mfbr2";
		case PPC_MNEM_MFBR3: return "mfbr3";
		case PPC_MNEM_MFBR4: return "mfbr4";
		case PPC_MNEM_MFBR5: return "mfbr5";
		case PPC_MNEM_MFBR6: return "mfbr6";
		case PPC_MNEM_MFBR7: return "mfbr7";
		case PPC_MNEM_MFCFAR: return "mfcfar";
		case PPC_MNEM_MFCR: return "mfcr";
		case PPC_MNEM_MFCTR: return "mfctr";
		case PPC_MNEM_MFCTRL: return "mfctrl";
		case PPC_MNEM_MFDAR: return "mfdar";
		case PPC_MNEM_MFDBATL: return "mfdbatl";
		case PPC_MNEM_MFDBATU: return "mfdbatu";
		case PPC_MNEM_MFDCR: return "mfdcr";
		case PPC_MNEM_MFDCRUX: return "mfdcrux";
		case PPC_MNEM_MFDCRX: return "mfdcrx";
		case PPC_MNEM_MFDEC: return "mfdec";
		case PPC_MNEM_MFDMACC0: return "mfdmacc0";
		case PPC_MNEM_MFDMACC1: return "mfdmacc1";
		case PPC_MNEM_MFDMACC2: return "mfdmacc2";
		case PPC_MNEM_MFDMACC3: return "mfdmacc3";
		case PPC_MNEM_MFDMACR0: return "mfdmacr0";
		case PPC_MNEM_MFDMACR1: return "mfdmacr1";
		case PPC_MNEM_MFDMACR2: return "mfdmacr2";
		case PPC_MNEM_MFDMACR3: return "mfdmacr3";
		case PPC_MNEM_MFDMACT0: return "mfdmact0";
		case PPC_MNEM_MFDMACT1: return "mfdmact1";
		case PPC_MNEM_MFDMACT2: return "mfdmact2";
		case PPC_MNEM_MFDMACT3: return "mfdmact3";
		case PPC_MNEM_MFDMADA0: return "mfdmada0";
		case PPC_MNEM_MFDMADA1: return "mfdmada1";
		case PPC_MNEM_MFDMADA2: return "mfdmada2";
		case PPC_MNEM_MFDMADA3: return "mfdmada3";
		case PPC_MNEM_MFDMASA0: return "mfdmasa0";
		case PPC_MNEM_MFDMASA1: return "mfdmasa1";
		case PPC_MNEM_MFDMASA2: return "mfdmasa2";
		case PPC_MNEM_MFDMASA3: return "mfdmasa3";
		case PPC_MNEM_MFDMASR: return "mfdmasr";
		case PPC_MNEM_MFDSCR: return "mfdscr";
		case PPC_MNEM_MFDSISR: return "mfdsisr";
		case PPC_MNEM_MFEAR: return "mfear";
		case PPC_MNEM_MFEXIER: return "mfexier";
		case PPC_MNEM_MFEXISR: return "mfexisr";
		case PPC_MNEM_MFFGPR: return "mffgpr";
		case PPC_MNEM_MFFPRWZ: return "mffprwz";
		case PPC_MNEM_MFFS: return "mffs";
		case PPC_MNEM_MFFSCDRN: return "mffscdrn";
		case PPC_MNEM_MFFSCDRNI: return "mffscdrni";
		case PPC_MNEM_MFFSCE: return "mffsce";
		case PPC_MNEM_MFFSCRN: return "mffscrn";
		case PPC_MNEM_MFFSCRNI: return "mffscrni";
		case PPC_MNEM_MFFSL: return "mffsl";
		case PPC_MNEM_MFIBATL: return "mfibatl";
		case PPC_MNEM_MFIBATU: return "mfibatu";
		case PPC_MNEM_MFIOCR: return "mfiocr";
		case PPC_MNEM_MFLR: return "mflr";
		case PPC_MNEM_MFMSR: return "mfmsr";
		case PPC_MNEM_MFOCRF: return "mfocrf";
		case PPC_MNEM_MFPMR: return "mfpmr";
		case PPC_MNEM_MFPPR: return "mfppr";
		case PPC_MNEM_MFPPR32: return "mfppr32";
		case PPC_MNEM_MFPVR: return "mfpvr";
		case PPC_MNEM_MFRTCL: return "mfrtcl";
		case PPC_MNEM_MFRTCU: return "mfrtcu";
		case PPC_MNEM_MFSDR1: return "mfsdr1";
		case PPC_MNEM_MFSPR: return "mfspr";
		case PPC_MNEM_MFSPRG: return "mfsprg";
		case PPC_MNEM_MFSR: return "mfsr";
		case PPC_MNEM_MFSRI: return "mfsri";
		case PPC_MNEM_MFSRIN: return "mfsrin";
		case PPC_MNEM_MFSRR0: return "mfsrr0";
		case PPC_MNEM_MFSRR1: return "mfsrr1";
		case PPC_MNEM_MFTB: return "mftb";
		case PPC_MNEM_MFTBU: return "mftbu";
		case PPC_MNEM_MFTGPR: return "mftgpr";
		case PPC_MNEM_MFTMR: return "mftmr";
		case PPC_MNEM_MFVRSAVE: return "mfvrsave";
		case PPC_MNEM_MFVRWZ: return "mfvrwz";
		case PPC_MNEM_MFVSCR: return "mfvscr";
		case PPC_MNEM_MFVSRD: return "mfvsrd";
		case PPC_MNEM_MFVSRLD: return "mfvsrld";
		case PPC_MNEM_MFXER: return "mfxer";
		case PPC_MNEM_MODSD: return "modsd";
		case PPC_MNEM_MODSW: return "modsw";
		case PPC_MNEM_MODUD: return "modud";
		case PPC_MNEM_MODUW: return "moduw";
		case PPC_MNEM_MR: return "mr";
		case PPC_MNEM_MSGCLR: return "msgclr";
		case PPC_MNEM_MSGCLRP: return "msgclrp";
		case PPC_MNEM_MSGSND: return "msgsnd";
		case PPC_MNEM_MSGSNDP: return "msgsndp";
		case PPC_MNEM_MSGSYNC: return "msgsync";
		case PPC_MNEM_MTASR: return "mtasr";
		case PPC_MNEM_MTBEAR: return "mtbear";
		case PPC_MNEM_MTBESR: return "mtbesr";
		case PPC_MNEM_MTBR0: return "mtbr0";
		case PPC_MNEM_MTBR1: return "mtbr1";
		case PPC_MNEM_MTBR2: return "mtbr2";
		case PPC_MNEM_MTBR3: return "mtbr3";
		case PPC_MNEM_MTBR4: return "mtbr4";
		case PPC_MNEM_MTBR5: return "mtbr5";
		case PPC_MNEM_MTBR6: return "mtbr6";
		case PPC_MNEM_MTBR7: return "mtbr7";
		case PPC_MNEM_MTCFAR: return "mtcfar";
		case PPC_MNEM_MTCR: return "mtcr";
		case PPC_MNEM_MTCRF: return "mtcrf";
		case PPC_MNEM_MTCTR: return "mtctr";
		case PPC_MNEM_MTCTRL: return "mtctrl";
		case PPC_MNEM_MTDAR: return "mtdar";
		case PPC_MNEM_MTDBATL: return "mtdbatl";
		case PPC_MNEM_MTDBATU: return "mtdbatu";
		case PPC_MNEM_MTDCR: return "mtdcr";
		case PPC_MNEM_MTDCRUX: return "mtdcrux";
		case PPC_MNEM_MTDCRX: return "mtdcrx";
		case PPC_MNEM_MTDEC: return "mtdec";
		case PPC_MNEM_MTDMACC0: return "mtdmacc0";
		case PPC_MNEM_MTDMACC1: return "mtdmacc1";
		case PPC_MNEM_MTDMACC2: return "mtdmacc2";
		case PPC_MNEM_MTDMACC3: return "mtdmacc3";
		case PPC_MNEM_MTDMACR0: return "mtdmacr0";
		case PPC_MNEM_MTDMACR1: return "mtdmacr1";
		case PPC_MNEM_MTDMACR2: return "mtdmacr2";
		case PPC_MNEM_MTDMACR3: return "mtdmacr3";
		case PPC_MNEM_MTDMACT0: return "mtdmact0";
		case PPC_MNEM_MTDMACT1: return "mtdmact1";
		case PPC_MNEM_MTDMACT2: return "mtdmact2";
		case PPC_MNEM_MTDMACT3: return "mtdmact3";
		case PPC_MNEM_MTDMADA0: return "mtdmada0";
		case PPC_MNEM_MTDMADA1: return "mtdmada1";
		case PPC_MNEM_MTDMADA2: return "mtdmada2";
		case PPC_MNEM_MTDMADA3: return "mtdmada3";
		case PPC_MNEM_MTDMASA0: return "mtdmasa0";
		case PPC_MNEM_MTDMASA1: return "mtdmasa1";
		case PPC_MNEM_MTDMASA2: return "mtdmasa2";
		case PPC_MNEM_MTDMASA3: return "mtdmasa3";
		case PPC_MNEM_MTDMASR: return "mtdmasr";
		case PPC_MNEM_MTDSCR: return "mtdscr";
		case PPC_MNEM_MTDSISR: return "mtdsisr";
		case PPC_MNEM_MTEAR: return "mtear";
		case PPC_MNEM_MTEXIER: return "mtexier";
		case PPC_MNEM_MTEXISR: return "mtexisr";
		case PPC_MNEM_MTFPRWA: return "mtfprwa";
		case PPC_MNEM_MTFPRWZ: return "mtfprwz";
		case PPC_MNEM_MTFSB0: return "mtfsb0";
		case PPC_MNEM_MTFSB1: return "mtfsb1";
		case PPC_MNEM_MTFSF: return "mtfsf";
		case PPC_MNEM_MTFSFI: return "mtfsfi";
		case PPC_MNEM_MTIBATL: return "mtibatl";
		case PPC_MNEM_MTIBATU: return "mtibatu";
		case PPC_MNEM_MTIOCR: return "mtiocr";
		case PPC_MNEM_MTLR: return "mtlr";
		case PPC_MNEM_MTMSR: return "mtmsr";
		case PPC_MNEM_MTMSRD: return "mtmsrd";
		case PPC_MNEM_MTOCRF: return "mtocrf";
		case PPC_MNEM_MTPMR: return "mtpmr";
		case PPC_MNEM_MTPPR: return "mtppr";
		case PPC_MNEM_MTPPR32: return "mtppr32";
		case PPC_MNEM_MTRTCL: return "mtrtcl";
		case PPC_MNEM_MTRTCU: return "mtrtcu";
		case PPC_MNEM_MTSDR1: return "mtsdr1";
		case PPC_MNEM_MTSLE: return "mtsle";
		case PPC_MNEM_MTSPR: return "mtspr";
		case PPC_MNEM_MTSPRG: return "mtsprg";
		case PPC_MNEM_MTSR: return "mtsr";
		case PPC_MNEM_MTSRD: return "mtsrd";
		case PPC_MNEM_MTSRDIN: return "mtsrdin";
		case PPC_MNEM_MTSRIN: return "mtsrin";
		case PPC_MNEM_MTSRR0: return "mtsrr0";
		case PPC_MNEM_MTSRR1: return "mtsrr1";
		case PPC_MNEM_MTTBL: return "mttbl";
		case PPC_MNEM_MTTBU: return "mttbu";
		case PPC_MNEM_MTTMR: return "mttmr";
		case PPC_MNEM_MTVRSAVE: return "mtvrsave";
		case PPC_MNEM_MTVRWA: return "mtvrwa";
		case PPC_MNEM_MTVRWZ: return "mtvrwz";
		case PPC_MNEM_MTVSCR: return "mtvscr";
		case PPC_MNEM_MTVSRD: return "mtvsrd";
		case PPC_MNEM_MTVSRDD: return "mtvsrdd";
		case PPC_MNEM_MTVSRWS: return "mtvsrws";
		case PPC_MNEM_MTXER: return "mtxer";
		case PPC_MNEM_MUL: return "mul";
		case PPC_MNEM_MULCHW: return "mulchw";
		case PPC_MNEM_MULCHWU: return "mulchwu";
		case PPC_MNEM_MULHD: return "mulhd";
		case PPC_MNEM_MULHDU: return "mulhdu";
		case PPC_MNEM_MULHHW: return "mulhhw";
		case PPC_MNEM_MULHHWU: return "mulhhwu";
		case PPC_MNEM_MULHW: return "mulhw";
		case PPC_MNEM_MULHWU: return "mulhwu";
		case PPC_MNEM_MULLD: return "mulld";
		case PPC_MNEM_MULLDO: return "mulldo";
		case PPC_MNEM_MULLHW: return "mullhw";
		case PPC_MNEM_MULLHWU: return "mullhwu";
		case PPC_MNEM_MULLI: return "mulli";
		case PPC_MNEM_MULLW: return "mullw";
		case PPC_MNEM_MULLWO: return "mullwo";
		case PPC_MNEM_MULO: return "mulo";
		case PPC_MNEM_MVIDSPLT: return "mvidsplt";
		case PPC_MNEM_MVIWSPLT: return "mviwsplt";
		case PPC_MNEM_NABS: return "nabs";
		case PPC_MNEM_NABSO: return "nabso";
		case PPC_MNEM_NAND: return "nand";
		case PPC_MNEM_NAP: return "nap";
		case PPC_MNEM_NEG: return "neg";
		case PPC_MNEM_NEGO: return "nego";
		case PPC_MNEM_NOP: return "nop";
		case PPC_MNEM_NOR: return "nor";
		case PPC_MNEM_NOT: return "not";
		case PPC_MNEM_OR: return "or";
		case PPC_MNEM_ORC: return "orc";
		case PPC_MNEM_ORI: return "ori";
		case PPC_MNEM_ORIS: return "oris";
		case PPC_MNEM_PASTE: return "paste";
		case PPC_MNEM_PBT: return "pbt";
		case PPC_MNEM_POPCNTB: return "popcntb";
		case PPC_MNEM_POPCNTD: return "popcntd";
		case PPC_MNEM_POPCNTW: return "popcntw";
		case PPC_MNEM_PRTYD: return "prtyd";
		case PPC_MNEM_PRTYW: return "prtyw";
		case PPC_MNEM_PSQ_L: return "psq_l";
		case PPC_MNEM_PSQ_LU: return "psq_lu";
		case PPC_MNEM_PSQ_LUX: return "psq_lux";
		case PPC_MNEM_PSQ_LX: return "psq_lx";
		case PPC_MNEM_PSQ_ST: return "psq_st";
		case PPC_MNEM_PSQ_STU: return "psq_stu";
		case PPC_MNEM_PSQ_STUX: return "psq_stux";
		case PPC_MNEM_PSQ_STX: return "psq_stx";
		case PPC_MNEM_PS_ABS: return "ps_abs";
		case PPC_MNEM_PS_MADD: return "ps_madd";
		case PPC_MNEM_PS_MADDS0: return "ps_madds0";
		case PPC_MNEM_PS_MADDS1: return "ps_madds1";
		case PPC_MNEM_PS_MR: return "ps_mr";
		case PPC_MNEM_PS_MSUB: return "ps_msub";
		case PPC_MNEM_PS_MUL: return "ps_mul";
		case PPC_MNEM_PS_MULS0: return "ps_muls0";
		case PPC_MNEM_PS_MULS1: return "ps_muls1";
		case PPC_MNEM_PS_NABS: return "ps_nabs";
		case PPC_MNEM_PS_NEG: return "ps_neg";
		case PPC_MNEM_PS_RSQRTE: return "ps_rsqrte";
		case PPC_MNEM_PS_SUM0: return "ps_sum0";
		case PPC_MNEM_PS_SUM1: return "ps_sum1";
		case PPC_MNEM_PTESYNC: return "ptesync";
		case PPC_MNEM_RAC: return "rac";
		case PPC_MNEM_RFCI: return "rfci";
		case PPC_MNEM_RFDI: return "rfdi";
		case PPC_MNEM_RFEBB: return "rfebb";
		case PPC_MNEM_RFGI: return "rfgi";
		case PPC_MNEM_RFI: return "rfi";
		case PPC_MNEM_RFID: return "rfid";
		case PPC_MNEM_RFMCI: return "rfmci";
		case PPC_MNEM_RFSCV: return "rfscv";
		case PPC_MNEM_RLDCL: return "rldcl";
		case PPC_MNEM_RLDCR: return "rldcr";
		case PPC_MNEM_RLDIC: return "rldic";
		case PPC_MNEM_RLDICL: return "rldicl";
		case PPC_MNEM_RLDICR: return "rldicr";
		case PPC_MNEM_RLDIMI: return "rldimi";
		case PPC_MNEM_RLMI: return "rlmi";
		case PPC_MNEM_RLWIMI: return "rlwimi";
		case PPC_MNEM_RLWINM: return "rlwinm";
		case PPC_MNEM_RLWNM: return "rlwnm";
		case PPC_MNEM_RMIEG: return "rmieg";
		case PPC_MNEM_ROTLD: return "rotld";
		case PPC_MNEM_ROTLDI: return "rotldi";
		case PPC_MNEM_ROTLW: return "rotlw";
		case PPC_MNEM_ROTLWI: return "rotlwi";
		case PPC_MNEM_RRIB: return "rrib";
		case PPC_MNEM_RVWINKLE: return "rvwinkle";
		case PPC_MNEM_SC: return "sc";
		case PPC_MNEM_SCV: return "scv";
		case PPC_MNEM_SETB: return "setb";
		case PPC_MNEM_SLBFEE: return "slbfee";
		case PPC_MNEM_SLBIA: return "slbia";
		case PPC_MNEM_SLBIAG: return "slbiag";
		case PPC_MNEM_SLBIE: return "slbie";
		case PPC_MNEM_SLBIEG: return "slbieg";
		case PPC_MNEM_SLBMFEE: return "slbmfee";
		case PPC_MNEM_SLBMFEV: return "slbmfev";
		case PPC_MNEM_SLBMTE: return "slbmte";
		case PPC_MNEM_SLBSYNC: return "slbsync";
		case PPC_MNEM_SLD: return "sld";
		case PPC_MNEM_SLE: return "sle";
		case PPC_MNEM_SLEEP: return "sleep";
		case PPC_MNEM_SLEQ: return "sleq";
		case PPC_MNEM_SLIQ: return "sliq";
		case PPC_MNEM_SLLIQ: return "slliq";
		case PPC_MNEM_SLLQ: return "sllq";
		case PPC_MNEM_SLQ: return "slq";
		case PPC_MNEM_SLW: return "slw";
		case PPC_MNEM_SRAD: return "srad";
		case PPC_MNEM_SRADI: return "sradi";
		case PPC_MNEM_SRAIQ: return "sraiq";
		case PPC_MNEM_SRAQ: return "sraq";
		case PPC_MNEM_SRAW: return "sraw";
		case PPC_MNEM_SRAWI: return "srawi";
		case PPC_MNEM_SRD: return "srd";
		case PPC_MNEM_SRE: return "sre";
		case PPC_MNEM_SREA: return "srea";
		case PPC_MNEM_SREQ: return "sreq";
		case PPC_MNEM_SRIQ: return "sriq";
		case PPC_MNEM_SRLIQ: return "srliq";
		case PPC_MNEM_SRLQ: return "srlq";
		case PPC_MNEM_SRQ: return "srq";
		case PPC_MNEM_SRW: return "srw";
		case PPC_MNEM_STB: return "stb";
		case PPC_MNEM_STBCIX: return "stbcix";
		case PPC_MNEM_STBCX: return "stbcx";
		case PPC_MNEM_STBDCBX: return "stbdcbx";
		case PPC_MNEM_STBDX: return "stbdx";
		case PPC_MNEM_STBEPX: return "stbepx";
		case PPC_MNEM_STBU: return "stbu";
		case PPC_MNEM_STBUX: return "stbux";
		case PPC_MNEM_STBX: return "stbx";
		case PPC_MNEM_STD: return "std";
		case PPC_MNEM_STDAT: return "stdat";
		case PPC_MNEM_STDBRX: return "stdbrx";
		case PPC_MNEM_STDCIX: return "stdcix";
		case PPC_MNEM_STDCX: return "stdcx";
		case PPC_MNEM_STDDX: return "stddx";
		case PPC_MNEM_STDEPX: return "stdepx";
		case PPC_MNEM_STDFCMX: return "stdfcmx";
		case PPC_MNEM_STDU: return "stdu";
		case PPC_MNEM_STDUX: return "stdux";
		case PPC_MNEM_STDX: return "stdx";
		case PPC_MNEM_STFD: return "stfd";
		case PPC_MNEM_STFDDX: return "stfddx";
		case PPC_MNEM_STFDEPX: return "stfdepx";
		case PPC_MNEM_STFDP: return "stfdp";
		case PPC_MNEM_STFDPX: return "stfdpx";
		case PPC_MNEM_STFDU: return "stfdu";
		case PPC_MNEM_STFDUX: return "stfdux";
		case PPC_MNEM_STFDX: return "stfdx";
		case PPC_MNEM_STFIWX: return "stfiwx";
		case PPC_MNEM_STFQUX: return "stfqux";
		case PPC_MNEM_STFQX: return "stfqx";
		case PPC_MNEM_STFS: return "stfs";
		case PPC_MNEM_STFSU: return "stfsu";
		case PPC_MNEM_STFSUX: return "stfsux";
		case PPC_MNEM_STFSX: return "stfsx";
		case PPC_MNEM_STH: return "sth";
		case PPC_MNEM_STHBRX: return "sthbrx";
		case PPC_MNEM_STHCIX: return "sthcix";
		case PPC_MNEM_STHCX: return "sthcx";
		case PPC_MNEM_STHDCBX: return "sthdcbx";
		case PPC_MNEM_STHDX: return "sthdx";
		case PPC_MNEM_STHEPX: return "sthepx";
		case PPC_MNEM_STHU: return "sthu";
		case PPC_MNEM_STHUX: return "sthux";
		case PPC_MNEM_STHX: return "sthx";
		case PPC_MNEM_STMW: return "stmw";
		case PPC_MNEM_STOP: return "stop";
		case PPC_MNEM_STQ: return "stq";
		case PPC_MNEM_STQCX: return "stqcx";
		case PPC_MNEM_STQFCMUX: return "stqfcmux";
		case PPC_MNEM_STSWI: return "stswi";
		case PPC_MNEM_STSWX: return "stswx";
		case PPC_MNEM_STU: return "stu";
		case PPC_MNEM_STUX: return "stux";
		case PPC_MNEM_STVEBX: return "stvebx";
		case PPC_MNEM_STVEHX: return "stvehx";
		case PPC_MNEM_STVEPX: return "stvepx";
		case PPC_MNEM_STVEPXL: return "stvepxl";
		case PPC_MNEM_STVEWX: return "stvewx";
		case PPC_MNEM_STVEXBX: return "stvexbx";
		case PPC_MNEM_STVEXHX: return "stvexhx";
		case PPC_MNEM_STVEXWX: return "stvexwx";
		case PPC_MNEM_STVFLX: return "stvflx";
		case PPC_MNEM_STVFLXL: return "stvflxl";
		case PPC_MNEM_STVFRX: return "stvfrx";
		case PPC_MNEM_STVFRXL: return "stvfrxl";
		case PPC_MNEM_STVLX: return "stvlx";
		case PPC_MNEM_STVLXL: return "stvlxl";
		case PPC_MNEM_STVRX: return "stvrx";
		case PPC_MNEM_STVRXL: return "stvrxl";
		case PPC_MNEM_STVSWX: return "stvswx";
		case PPC_MNEM_STVSWXL: return "stvswxl";
		case PPC_MNEM_STVX: return "stvx";
		case PPC_MNEM_STVXL: return "stvxl";
		case PPC_MNEM_STW: return "stw";
		case PPC_MNEM_STWAT: return "stwat";
		case PPC_MNEM_STWBRX: return "stwbrx";
		case PPC_MNEM_STWCIX: return "stwcix";
		case PPC_MNEM_STWCX: return "stwcx";
		case PPC_MNEM_STWDCBX: return "stwdcbx";
		case PPC_MNEM_STWDX: return "stwdx";
		case PPC_MNEM_STWEPX: return "stwepx";
		case PPC_MNEM_STWFCMUX: return "stwfcmux";
		case PPC_MNEM_STWU: return "stwu";
		case PPC_MNEM_STWUX: return "stwux";
		case PPC_MNEM_STWX: return "stwx";
		case PPC_MNEM_STXSD: return "stxsd";
		case PPC_MNEM_STXSDX: return "stxsdx";
		case PPC_MNEM_STXSIBX: return "stxsibx";
		case PPC_MNEM_STXSIHX: return "stxsihx";
		case PPC_MNEM_STXSIWX: return "stxsiwx";
		case PPC_MNEM_STXSSP: return "stxssp";
		case PPC_MNEM_STXSSPX: return "stxsspx";
		case PPC_MNEM_STXV: return "stxv";
		case PPC_MNEM_STXVB16X: return "stxvb16x";
		case PPC_MNEM_STXVD2X: return "stxvd2x";
		case PPC_MNEM_STXVH8X: return "stxvh8x";
		case PPC_MNEM_STXVL: return "stxvl";
		case PPC_MNEM_STXVLL: return "stxvll";
		case PPC_MNEM_STXVW4X: return "stxvw4x";
		case PPC_MNEM_STXVX: return "stxvx";
		case PPC_MNEM_SUBF: return "subf";
		case PPC_MNEM_SUBFC: return "subfc";
		case PPC_MNEM_SUBFCO: return "subfco";
		case PPC_MNEM_SUBFE: return "subfe";
		case PPC_MNEM_SUBFEO: return "subfeo";
		case PPC_MNEM_SUBFIC: return "subfic";
		case PPC_MNEM_SUBFME: return "subfme";
		case PPC_MNEM_SUBFMEO: return "subfmeo";
		case PPC_MNEM_SUBFO: return "subfo";
		case PPC_MNEM_SUBFZE: return "subfze";
		case PPC_MNEM_SUBFZEO: return "subfzeo";
		case PPC_MNEM_SVC: return "svc";
		case PPC_MNEM_SVCLA: return "svcla";
		case PPC_MNEM_SYNC: return "sync";
		case PPC_MNEM_TABORT: return "tabort";
		case PPC_MNEM_TABORTDC: return "tabortdc";
		case PPC_MNEM_TABORTDCI: return "tabortdci";
		case PPC_MNEM_TABORTWC: return "tabortwc";
		case PPC_MNEM_TABORTWCI: return "tabortwci";
		case PPC_MNEM_TBEGIN: return "tbegin";
		case PPC_MNEM_TCHECK: return "tcheck";
		case PPC_MNEM_TD: return "td";
		case PPC_MNEM_TDEQ: return "tdeq";
		case PPC_MNEM_TDEQI: return "tdeqi";
		case PPC_MNEM_TDGE: return "tdge";
		case PPC_MNEM_TDGEI: return "tdgei";
		case PPC_MNEM_TDGT: return "tdgt";
		case PPC_MNEM_TDGTI: return "tdgti";
		case PPC_MNEM_TDI: return "tdi";
		case PPC_MNEM_TDLE: return "tdle";
		case PPC_MNEM_TDLEI: return "tdlei";
		case PPC_MNEM_TDLGE: return "tdlge";
		case PPC_MNEM_TDLGEI: return "tdlgei";
		case PPC_MNEM_TDLGT: return "tdlgt";
		case PPC_MNEM_TDLGTI: return "tdlgti";
		case PPC_MNEM_TDLLE: return "tdlle";
		case PPC_MNEM_TDLLEI: return "tdllei";
		case PPC_MNEM_TDLLT: return "tdllt";
		case PPC_MNEM_TDLLTI: return "tdllti";
		case PPC_MNEM_TDLT: return "tdlt";
		case PPC_MNEM_TDLTI: return "tdlti";
		case PPC_MNEM_TDNE: return "tdne";
		case PPC_MNEM_TDNEI: return "tdnei";
		case PPC_MNEM_TDU: return "tdu";
		case PPC_MNEM_TDUI: return "tdui";
		case PPC_MNEM_TEND: return "tend";
		case PPC_MNEM_TENDALL: return "tendall";
		case PPC_MNEM_TLBI: return "tlbi";
		case PPC_MNEM_TLBIA: return "tlbia";
		case PPC_MNEM_TLBIE: return "tlbie";
		case PPC_MNEM_TLBIEL: return "tlbiel";
		case PPC_MNEM_TLBILX: return "tlbilx";
		case PPC_MNEM_TLBILXLPID: return "tlbilxlpid";
		case PPC_MNEM_TLBILXPID: return "tlbilxpid";
		case PPC_MNEM_TLBILXVA: return "tlbilxva";
		case PPC_MNEM_TLBIVAX: return "tlbivax";
		case PPC_MNEM_TLBLD: return "tlbld";
		case PPC_MNEM_TLBLI: return "tlbli";
		case PPC_MNEM_TLBRE: return "tlbre";
		case PPC_MNEM_TLBREHI: return "tlbrehi";
		case PPC_MNEM_TLBRELO: return "tlbrelo";
		case PPC_MNEM_TLBSRX: return "tlbsrx";
		case PPC_MNEM_TLBSX: return "tlbsx";
		case PPC_MNEM_TLBSYNC: return "tlbsync";
		case PPC_MNEM_TLBWE: return "tlbwe";
		case PPC_MNEM_TLBWEHI: return "tlbwehi";
		case PPC_MNEM_TLBWELO: return "tlbwelo";
		case PPC_MNEM_TRAP: return "trap";
		case PPC_MNEM_TRECHKPT: return "trechkpt";
		case PPC_MNEM_TRECLAIM: return "treclaim";
		case PPC_MNEM_TRESUME: return "tresume";
		case PPC_MNEM_TSUSPEND: return "tsuspend";
		case PPC_MNEM_TW: return "tw";
		case PPC_MNEM_TWEQ: return "tweq";
		case PPC_MNEM_TWEQI: return "tweqi";
		case PPC_MNEM_TWGE: return "twge";
		case PPC_MNEM_TWGEI: return "twgei";
		case PPC_MNEM_TWGT: return "twgt";
		case PPC_MNEM_TWGTI: return "twgti";
		case PPC_MNEM_TWI: return "twi";
		case PPC_MNEM_TWLE: return "twle";
		case PPC_MNEM_TWLEI: return "twlei";
		case PPC_MNEM_TWLGE: return "twlge";
		case PPC_MNEM_TWLGEI: return "twlgei";
		case PPC_MNEM_TWLGT: return "twlgt";
		case PPC_MNEM_TWLGTI: return "twlgti";
		case PPC_MNEM_TWLLE: return "twlle";
		case PPC_MNEM_TWLLEI: return "twllei";
		case PPC_MNEM_TWLLT: return "twllt";
		case PPC_MNEM_TWLLTI: return "twllti";
		case PPC_MNEM_TWLT: return "twlt";
		case PPC_MNEM_TWLTI: return "twlti";
		case PPC_MNEM_TWNE: return "twne";
		case PPC_MNEM_TWNEI: return "twnei";
		case PPC_MNEM_TWU: return "twu";
		case PPC_MNEM_TWUI: return "twui";
		case PPC_MNEM_UDI10FCM: return "udi10fcm";
		case PPC_MNEM_UDI12FCM: return "udi12fcm";
		case PPC_MNEM_UDI13FCM: return "udi13fcm";
		case PPC_MNEM_UDI14FCM: return "udi14fcm";
		case PPC_MNEM_UDI4FCM: return "udi4fcm";
		case PPC_MNEM_UDI5FCM: return "udi5fcm";
		case PPC_MNEM_UDI6FCM: return "udi6fcm";
		case PPC_MNEM_UDI7FCM: return "udi7fcm";
		case PPC_MNEM_UDI8FCM: return "udi8fcm";
		case PPC_MNEM_UDI9FCM: return "udi9fcm";
		case PPC_MNEM_URFID: return "urfid";
		case PPC_MNEM_VABSDUB: return "vabsdub";
		case PPC_MNEM_VABSDUH: return "vabsduh";
		case PPC_MNEM_VABSDUW: return "vabsduw";
		case PPC_MNEM_VADDCUQ: return "vaddcuq";
		case PPC_MNEM_VADDCUW: return "vaddcuw";
		case PPC_MNEM_VADDECUQ: return "vaddecuq";
		case PPC_MNEM_VADDEUQM: return "vaddeuqm";
		case PPC_MNEM_VADDFP: return "vaddfp";
		case PPC_MNEM_VADDSBS: return "vaddsbs";
		case PPC_MNEM_VADDSHS: return "vaddshs";
		case PPC_MNEM_VADDSWS: return "vaddsws";
		case PPC_MNEM_VADDUBM: return "vaddubm";
		case PPC_MNEM_VADDUBS: return "vaddubs";
		case PPC_MNEM_VADDUDM: return "vaddudm";
		case PPC_MNEM_VADDUHM: return "vadduhm";
		case PPC_MNEM_VADDUHS: return "vadduhs";
		case PPC_MNEM_VADDUQM: return "vadduqm";
		case PPC_MNEM_VADDUWM: return "vadduwm";
		case PPC_MNEM_VADDUWS: return "vadduws";
		case PPC_MNEM_VAND: return "vand";
		case PPC_MNEM_VANDC: return "vandc";
		case PPC_MNEM_VAVGSB: return "vavgsb";
		case PPC_MNEM_VAVGSH: return "vavgsh";
		case PPC_MNEM_VAVGSW: return "vavgsw";
		case PPC_MNEM_VAVGUB: return "vavgub";
		case PPC_MNEM_VAVGUH: return "vavguh";
		case PPC_MNEM_VAVGUW: return "vavguw";
		case PPC_MNEM_VBPERMD: return "vbpermd";
		case PPC_MNEM_VBPERMQ: return "vbpermq";
		case PPC_MNEM_VCFSX: return "vcfsx";
		case PPC_MNEM_VCFUX: return "vcfux";
		case PPC_MNEM_VCIPHER: return "vcipher";
		case PPC_MNEM_VCIPHERLAST: return "vcipherlast";
		case PPC_MNEM_VCLZB: return "vclzb";
		case PPC_MNEM_VCLZD: return "vclzd";
		case PPC_MNEM_VCLZH: return "vclzh";
		case PPC_MNEM_VCLZLSBB: return "vclzlsbb";
		case PPC_MNEM_VCLZW: return "vclzw";
		case PPC_MNEM_VCMPBFP: return "vcmpbfp";
		case PPC_MNEM_VCMPEQFP: return "vcmpeqfp";
		case PPC_MNEM_VCMPEQUB: return "vcmpequb";
		case PPC_MNEM_VCMPEQUD: return "vcmpequd";
		case PPC_MNEM_VCMPEQUH: return "vcmpequh";
		case PPC_MNEM_VCMPEQUW: return "vcmpequw";
		case PPC_MNEM_VCMPGEFP: return "vcmpgefp";
		case PPC_MNEM_VCMPGTFP: return "vcmpgtfp";
		case PPC_MNEM_VCMPGTSB: return "vcmpgtsb";
		case PPC_MNEM_VCMPGTSD: return "vcmpgtsd";
		case PPC_MNEM_VCMPGTSH: return "vcmpgtsh";
		case PPC_MNEM_VCMPGTSW: return "vcmpgtsw";
		case PPC_MNEM_VCMPGTUB: return "vcmpgtub";
		case PPC_MNEM_VCMPGTUD: return "vcmpgtud";
		case PPC_MNEM_VCMPGTUH: return "vcmpgtuh";
		case PPC_MNEM_VCMPGTUW: return "vcmpgtuw";
		case PPC_MNEM_VCMPNEB: return "vcmpneb";
		case PPC_MNEM_VCMPNEH: return "vcmpneh";
		case PPC_MNEM_VCMPNEW: return "vcmpnew";
		case PPC_MNEM_VCMPNEZB: return "vcmpnezb";
		case PPC_MNEM_VCMPNEZH: return "vcmpnezh";
		case PPC_MNEM_VCMPNEZW: return "vcmpnezw";
		case PPC_MNEM_VCTSXS: return "vctsxs";
		case PPC_MNEM_VCTUXS: return "vctuxs";
		case PPC_MNEM_VCTZB: return "vctzb";
		case PPC_MNEM_VCTZD: return "vctzd";
		case PPC_MNEM_VCTZH: return "vctzh";
		case PPC_MNEM_VCTZLSBB: return "vctzlsbb";
		case PPC_MNEM_VCTZW: return "vctzw";
		case PPC_MNEM_VEQV: return "veqv";
		case PPC_MNEM_VEXPTEFP: return "vexptefp";
		case PPC_MNEM_VEXTRACTD: return "vextractd";
		case PPC_MNEM_VEXTRACTUB: return "vextractub";
		case PPC_MNEM_VEXTRACTUH: return "vextractuh";
		case PPC_MNEM_VEXTRACTUW: return "vextractuw";
		case PPC_MNEM_VEXTSB2D: return "vextsb2d";
		case PPC_MNEM_VEXTSB2W: return "vextsb2w";
		case PPC_MNEM_VEXTSH2D: return "vextsh2d";
		case PPC_MNEM_VEXTSH2W: return "vextsh2w";
		case PPC_MNEM_VEXTSW2D: return "vextsw2d";
		case PPC_MNEM_VEXTUBLX: return "vextublx";
		case PPC_MNEM_VEXTUBRX: return "vextubrx";
		case PPC_MNEM_VEXTUHLX: return "vextuhlx";
		case PPC_MNEM_VEXTUHRX: return "vextuhrx";
		case PPC_MNEM_VEXTUWLX: return "vextuwlx";
		case PPC_MNEM_VEXTUWRX: return "vextuwrx";
		case PPC_MNEM_VGBBD: return "vgbbd";
		case PPC_MNEM_VINSERTB: return "vinsertb";
		case PPC_MNEM_VINSERTD: return "vinsertd";
		case PPC_MNEM_VINSERTH: return "vinserth";
		case PPC_MNEM_VINSERTW: return "vinsertw";
		case PPC_MNEM_VLOGEFP: return "vlogefp";
		case PPC_MNEM_VMADDFP: return "vmaddfp";
		case PPC_MNEM_VMAXFP: return "vmaxfp";
		case PPC_MNEM_VMAXSB: return "vmaxsb";
		case PPC_MNEM_VMAXSD: return "vmaxsd";
		case PPC_MNEM_VMAXSH: return "vmaxsh";
		case PPC_MNEM_VMAXSW: return "vmaxsw";
		case PPC_MNEM_VMAXUB: return "vmaxub";
		case PPC_MNEM_VMAXUD: return "vmaxud";
		case PPC_MNEM_VMAXUH: return "vmaxuh";
		case PPC_MNEM_VMAXUW: return "vmaxuw";
		case PPC_MNEM_VMHADDSHS: return "vmhaddshs";
		case PPC_MNEM_VMHRADDSHS: return "vmhraddshs";
		case PPC_MNEM_VMINFP: return "vminfp";
		case PPC_MNEM_VMINSB: return "vminsb";
		case PPC_MNEM_VMINSD: return "vminsd";
		case PPC_MNEM_VMINSH: return "vminsh";
		case PPC_MNEM_VMINSW: return "vminsw";
		case PPC_MNEM_VMINUB: return "vminub";
		case PPC_MNEM_VMINUD: return "vminud";
		case PPC_MNEM_VMINUH: return "vminuh";
		case PPC_MNEM_VMINUW: return "vminuw";
		case PPC_MNEM_VMLADDUHM: return "vmladduhm";
		case PPC_MNEM_VMR: return "vmr";
		case PPC_MNEM_VMRGEW: return "vmrgew";
		case PPC_MNEM_VMRGHB: return "vmrghb";
		case PPC_MNEM_VMRGHH: return "vmrghh";
		case PPC_MNEM_VMRGHW: return "vmrghw";
		case PPC_MNEM_VMRGLB: return "vmrglb";
		case PPC_MNEM_VMRGLH: return "vmrglh";
		case PPC_MNEM_VMRGLW: return "vmrglw";
		case PPC_MNEM_VMRGOW: return "vmrgow";
		case PPC_MNEM_VMSUMMBM: return "vmsummbm";
		case PPC_MNEM_VMSUMSHM: return "vmsumshm";
		case PPC_MNEM_VMSUMSHS: return "vmsumshs";
		case PPC_MNEM_VMSUMUBM: return "vmsumubm";
		case PPC_MNEM_VMSUMUDM: return "vmsumudm";
		case PPC_MNEM_VMSUMUHM: return "vmsumuhm";
		case PPC_MNEM_VMSUMUHS: return "vmsumuhs";
		case PPC_MNEM_VMUL10CUQ: return "vmul10cuq";
		case PPC_MNEM_VMUL10ECUQ: return "vmul10ecuq";
		case PPC_MNEM_VMUL10EUQ: return "vmul10euq";
		case PPC_MNEM_VMUL10UQ: return "vmul10uq";
		case PPC_MNEM_VMULESB: return "vmulesb";
		case PPC_MNEM_VMULESH: return "vmulesh";
		case PPC_MNEM_VMULESW: return "vmulesw";
		case PPC_MNEM_VMULEUB: return "vmuleub";
		case PPC_MNEM_VMULEUH: return "vmuleuh";
		case PPC_MNEM_VMULEUW: return "vmuleuw";
		case PPC_MNEM_VMULOSB: return "vmulosb";
		case PPC_MNEM_VMULOSH: return "vmulosh";
		case PPC_MNEM_VMULOSW: return "vmulosw";
		case PPC_MNEM_VMULOUB: return "vmuloub";
		case PPC_MNEM_VMULOUH: return "vmulouh";
		case PPC_MNEM_VMULOUW: return "vmulouw";
		case PPC_MNEM_VMULUWM: return "vmuluwm";
		case PPC_MNEM_VNAND: return "vnand";
		case PPC_MNEM_VNCIPHER: return "vncipher";
		case PPC_MNEM_VNCIPHERLAST: return "vncipherlast";
		case PPC_MNEM_VNEGD: return "vnegd";
		case PPC_MNEM_VNEGW: return "vnegw";
		case PPC_MNEM_VNMSUBFP: return "vnmsubfp";
		case PPC_MNEM_VNOR: return "vnor";
		case PPC_MNEM_VNOT: return "vnot";
		case PPC_MNEM_VOR: return "vor";
		case PPC_MNEM_VORC: return "vorc";
		case PPC_MNEM_VPERM: return "vperm";
		case PPC_MNEM_VPERMR: return "vpermr";
		case PPC_MNEM_VPERMXOR: return "vpermxor";
		case PPC_MNEM_VPKPX: return "vpkpx";
		case PPC_MNEM_VPKSDSS: return "vpksdss";
		case PPC_MNEM_VPKSDUS: return "vpksdus";
		case PPC_MNEM_VPKSHSS: return "vpkshss";
		case PPC_MNEM_VPKSHUS: return "vpkshus";
		case PPC_MNEM_VPKSWSS: return "vpkswss";
		case PPC_MNEM_VPKSWUS: return "vpkswus";
		case PPC_MNEM_VPKUDUM: return "vpkudum";
		case PPC_MNEM_VPKUDUS: return "vpkudus";
		case PPC_MNEM_VPKUHUM: return "vpkuhum";
		case PPC_MNEM_VPKUHUS: return "vpkuhus";
		case PPC_MNEM_VPKUWUM: return "vpkuwum";
		case PPC_MNEM_VPKUWUS: return "vpkuwus";
		case PPC_MNEM_VPMSUMB: return "vpmsumb";
		case PPC_MNEM_VPMSUMD: return "vpmsumd";
		case PPC_MNEM_VPMSUMH: return "vpmsumh";
		case PPC_MNEM_VPMSUMW: return "vpmsumw";
		case PPC_MNEM_VPOPCNTB: return "vpopcntb";
		case PPC_MNEM_VPOPCNTD: return "vpopcntd";
		case PPC_MNEM_VPOPCNTH: return "vpopcnth";
		case PPC_MNEM_VPOPCNTW: return "vpopcntw";
		case PPC_MNEM_VPRTYBD: return "vprtybd";
		case PPC_MNEM_VPRTYBQ: return "vprtybq";
		case PPC_MNEM_VPRTYBW: return "vprtybw";
		case PPC_MNEM_VREFP: return "vrefp";
		case PPC_MNEM_VRFIM: return "vrfim";
		case PPC_MNEM_VRFIN: return "vrfin";
		case PPC_MNEM_VRFIP: return "vrfip";
		case PPC_MNEM_VRFIZ: return "vrfiz";
		case PPC_MNEM_VRLB: return "vrlb";
		case PPC_MNEM_VRLD: return "vrld";
		case PPC_MNEM_VRLDMI: return "vrldmi";
		case PPC_MNEM_VRLDNM: return "vrldnm";
		case PPC_MNEM_VRLH: return "vrlh";
		case PPC_MNEM_VRLW: return "vrlw";
		case PPC_MNEM_VRLWMI: return "vrlwmi";
		case PPC_MNEM_VRLWNM: return "vrlwnm";
		case PPC_MNEM_VRSQRTEFP: return "vrsqrtefp";
		case PPC_MNEM_VSBOX: return "vsbox";
		case PPC_MNEM_VSEL: return "vsel";
		case PPC_MNEM_VSHASIGMAD: return "vshasigmad";
		case PPC_MNEM_VSHASIGMAW: return "vshasigmaw";
		case PPC_MNEM_VSL: return "vsl";
		case PPC_MNEM_VSLB: return "vslb";
		case PPC_MNEM_VSLD: return "vsld";
		case PPC_MNEM_VSLDOI: return "vsldoi";
		case PPC_MNEM_VSLH: return "vslh";
		case PPC_MNEM_VSLO: return "vslo";
		case PPC_MNEM_VSLV: return "vslv";
		case PPC_MNEM_VSLW: return "vslw";
		case PPC_MNEM_VSPLTB: return "vspltb";
		case PPC_MNEM_VSPLTH: return "vsplth";
		case PPC_MNEM_VSPLTISB: return "vspltisb";
		case PPC_MNEM_VSPLTISH: return "vspltish";
		case PPC_MNEM_VSPLTISW: return "vspltisw";
		case PPC_MNEM_VSPLTW: return "vspltw";
		case PPC_MNEM_VSR: return "vsr";
		case PPC_MNEM_VSRAB: return "vsrab";
		case PPC_MNEM_VSRAD: return "vsrad";
		case PPC_MNEM_VSRAH: return "vsrah";
		case PPC_MNEM_VSRAW: return "vsraw";
		case PPC_MNEM_VSRB: return "vsrb";
		case PPC_MNEM_VSRD: return "vsrd";
		case PPC_MNEM_VSRH: return "vsrh";
		case PPC_MNEM_VSRO: return "vsro";
		case PPC_MNEM_VSRV: return "vsrv";
		case PPC_MNEM_VSRW: return "vsrw";
		case PPC_MNEM_VSUBCUQ: return "vsubcuq";
		case PPC_MNEM_VSUBCUW: return "vsubcuw";
		case PPC_MNEM_VSUBECUQ: return "vsubecuq";
		case PPC_MNEM_VSUBEUQM: return "vsubeuqm";
		case PPC_MNEM_VSUBFP: return "vsubfp";
		case PPC_MNEM_VSUBSBS: return "vsubsbs";
		case PPC_MNEM_VSUBSHS: return "vsubshs";
		case PPC_MNEM_VSUBSWS: return "vsubsws";
		case PPC_MNEM_VSUBUBM: return "vsububm";
		case PPC_MNEM_VSUBUBS: return "vsububs";
		case PPC_MNEM_VSUBUDM: return "vsubudm";
		case PPC_MNEM_VSUBUHM: return "vsubuhm";
		case PPC_MNEM_VSUBUHS: return "vsubuhs";
		case PPC_MNEM_VSUBUQM: return "vsubuqm";
		case PPC_MNEM_VSUBUWM: return "vsubuwm";
		case PPC_MNEM_VSUBUWS: return "vsubuws";
		case PPC_MNEM_VSUM2SWS: return "vsum2sws";
		case PPC_MNEM_VSUM4SBS: return "vsum4sbs";
		case PPC_MNEM_VSUM4SHS: return "vsum4shs";
		case PPC_MNEM_VSUM4UBS: return "vsum4ubs";
		case PPC_MNEM_VSUMSWS: return "vsumsws";
		case PPC_MNEM_VUPKHPX: return "vupkhpx";
		case PPC_MNEM_VUPKHSB: return "vupkhsb";
		case PPC_MNEM_VUPKHSH: return "vupkhsh";
		case PPC_MNEM_VUPKHSW: return "vupkhsw";
		case PPC_MNEM_VUPKLPX: return "vupklpx";
		case PPC_MNEM_VUPKLSB: return "vupklsb";
		case PPC_MNEM_VUPKLSH: return "vupklsh";
		case PPC_MNEM_VUPKLSW: return "vupklsw";
		case PPC_MNEM_VXOR: return "vxor";
		case PPC_MNEM_WAIT: return "wait";
		case PPC_MNEM_WAITIMPL: return "waitimpl";
		case PPC_MNEM_WAITRSV: return "waitrsv";
		case PPC_MNEM_WCHKALL: return "wchkall";
		case PPC_MNEM_WCLR: return "wclr";
		case PPC_MNEM_WCLRALL: return "wclrall";
		case PPC_MNEM_WCLRONE: return "wclrone";
		case PPC_MNEM_WRTEE: return "wrtee";
		case PPC_MNEM_WRTEEI: return "wrteei";
		case PPC_MNEM_XNOP: return "xnop";
		case PPC_MNEM_XOR: return "xor";
		case PPC_MNEM_XORI: return "xori";
		case PPC_MNEM_XORIS: return "xoris";
		case PPC_MNEM_XSABSDP: return "xsabsdp";
		case PPC_MNEM_XSABSQP: return "xsabsqp";
		case PPC_MNEM_XSADDDP: return "xsadddp";
		case PPC_MNEM_XSADDQP: return "xsaddqp";
		case PPC_MNEM_XSADDQPO: return "xsaddqpo";
		case PPC_MNEM_XSADDSP: return "xsaddsp";
		case PPC_MNEM_XSCMPEQDP: return "xscmpeqdp";
		case PPC_MNEM_XSCMPEXPDP: return "xscmpexpdp";
		case PPC_MNEM_XSCMPEXPQP: return "xscmpexpqp";
		case PPC_MNEM_XSCMPGEDP: return "xscmpgedp";
		case PPC_MNEM_XSCMPGTDP: return "xscmpgtdp";
		case PPC_MNEM_XSCMPODP: return "xscmpodp";
		case PPC_MNEM_XSCMPOQP: return "xscmpoqp";
		case PPC_MNEM_XSCMPUDP: return "xscmpudp";
		case PPC_MNEM_XSCMPUQP: return "xscmpuqp";
		case PPC_MNEM_XSCPSGNDP: return "xscpsgndp";
		case PPC_MNEM_XSCPSGNQP: return "xscpsgnqp";
		case PPC_MNEM_XSCVDPHP: return "xscvdphp";
		case PPC_MNEM_XSCVDPQP: return "xscvdpqp";
		case PPC_MNEM_XSCVDPSP: return "xscvdpsp";
		case PPC_MNEM_XSCVDPSPN: return "xscvdpspn";
		case PPC_MNEM_XSCVDPSXDS: return "xscvdpsxds";
		case PPC_MNEM_XSCVDPSXWS: return "xscvdpsxws";
		case PPC_MNEM_XSCVDPUXDS: return "xscvdpuxds";
		case PPC_MNEM_XSCVDPUXWS: return "xscvdpuxws";
		case PPC_MNEM_XSCVHPDP: return "xscvhpdp";
		case PPC_MNEM_XSCVQPDP: return "xscvqpdp";
		case PPC_MNEM_XSCVQPDPO: return "xscvqpdpo";
		case PPC_MNEM_XSCVQPSDZ: return "xscvqpsdz";
		case PPC_MNEM_XSCVQPSWZ: return "xscvqpswz";
		case PPC_MNEM_XSCVQPUDZ: return "xscvqpudz";
		case PPC_MNEM_XSCVQPUWZ: return "xscvqpuwz";
		case PPC_MNEM_XSCVSDQP: return "xscvsdqp";
		case PPC_MNEM_XSCVSPDP: return "xscvspdp";
		case PPC_MNEM_XSCVSPDPN: return "xscvspdpn";
		case PPC_MNEM_XSCVSXDDP: return "xscvsxddp";
		case PPC_MNEM_XSCVSXDSP: return "xscvsxdsp";
		case PPC_MNEM_XSCVUDQP: return "xscvudqp";
		case PPC_MNEM_XSCVUXDDP: return "xscvuxddp";
		case PPC_MNEM_XSCVUXDSP: return "xscvuxdsp";
		case PPC_MNEM_XSDIVDP: return "xsdivdp";
		case PPC_MNEM_XSDIVQP: return "xsdivqp";
		case PPC_MNEM_XSDIVQPO: return "xsdivqpo";
		case PPC_MNEM_XSDIVSP: return "xsdivsp";
		case PPC_MNEM_XSIEXPDP: return "xsiexpdp";
		case PPC_MNEM_XSIEXPQP: return "xsiexpqp";
		case PPC_MNEM_XSMADDADP: return "xsmaddadp";
		case PPC_MNEM_XSMADDASP: return "xsmaddasp";
		case PPC_MNEM_XSMADDMDP: return "xsmaddmdp";
		case PPC_MNEM_XSMADDMSP: return "xsmaddmsp";
		case PPC_MNEM_XSMADDQP: return "xsmaddqp";
		case PPC_MNEM_XSMADDQPO: return "xsmaddqpo";
		case PPC_MNEM_XSMAXCDP: return "xsmaxcdp";
		case PPC_MNEM_XSMAXDP: return "xsmaxdp";
		case PPC_MNEM_XSMAXJDP: return "xsmaxjdp";
		case PPC_MNEM_XSMINCDP: return "xsmincdp";
		case PPC_MNEM_XSMINDP: return "xsmindp";
		case PPC_MNEM_XSMINJDP: return "xsminjdp";
		case PPC_MNEM_XSMSUBADP: return "xsmsubadp";
		case PPC_MNEM_XSMSUBASP: return "xsmsubasp";
		case PPC_MNEM_XSMSUBMDP: return "xsmsubmdp";
		case PPC_MNEM_XSMSUBMSP: return "xsmsubmsp";
		case PPC_MNEM_XSMSUBQP: return "xsmsubqp";
		case PPC_MNEM_XSMSUBQPO: return "xsmsubqpo";
		case PPC_MNEM_XSMULDP: return "xsmuldp";
		case PPC_MNEM_XSMULQP: return "xsmulqp";
		case PPC_MNEM_XSMULQPO: return "xsmulqpo";
		case PPC_MNEM_XSMULSP: return "xsmulsp";
		case PPC_MNEM_XSNABSDP: return "xsnabsdp";
		case PPC_MNEM_XSNABSQP: return "xsnabsqp";
		case PPC_MNEM_XSNEGDP: return "xsnegdp";
		case PPC_MNEM_XSNEGQP: return "xsnegqp";
		case PPC_MNEM_XSNMADDADP: return "xsnmaddadp";
		case PPC_MNEM_XSNMADDASP: return "xsnmaddasp";
		case PPC_MNEM_XSNMADDMDP: return "xsnmaddmdp";
		case PPC_MNEM_XSNMADDMSP: return "xsnmaddmsp";
		case PPC_MNEM_XSNMADDQP: return "xsnmaddqp";
		case PPC_MNEM_XSNMADDQPO: return "xsnmaddqpo";
		case PPC_MNEM_XSNMSUBADP: return "xsnmsubadp";
		case PPC_MNEM_XSNMSUBASP: return "xsnmsubasp";
		case PPC_MNEM_XSNMSUBMDP: return "xsnmsubmdp";
		case PPC_MNEM_XSNMSUBMSP: return "xsnmsubmsp";
		case PPC_MNEM_XSNMSUBQP: return "xsnmsubqp";
		case PPC_MNEM_XSNMSUBQPO: return "xsnmsubqpo";
		case PPC_MNEM_XSRDPI: return "xsrdpi";
		case PPC_MNEM_XSRDPIC: return "xsrdpic";
		case PPC_MNEM_XSRDPIM: return "xsrdpim";
		case PPC_MNEM_XSRDPIP: return "xsrdpip";
		case PPC_MNEM_XSRDPIZ: return "xsrdpiz";
		case PPC_MNEM_XSREDP: return "xsredp";
		case PPC_MNEM_XSRESP: return "xsresp";
		case PPC_MNEM_XSRQPI: return "xsrqpi";
		case PPC_MNEM_XSRQPIX: return "xsrqpix";
		case PPC_MNEM_XSRQPXP: return "xsrqpxp";
		case PPC_MNEM_XSRSP: return "xsrsp";
		case PPC_MNEM_XSRSQRTEDP: return "xsrsqrtedp";
		case PPC_MNEM_XSRSQRTESP: return "xsrsqrtesp";
		case PPC_MNEM_XSSQRTDP: return "xssqrtdp";
		case PPC_MNEM_XSSQRTQP: return "xssqrtqp";
		case PPC_MNEM_XSSQRTQPO: return "xssqrtqpo";
		case PPC_MNEM_XSSQRTSP: return "xssqrtsp";
		case PPC_MNEM_XSSUBDP: return "xssubdp";
		case PPC_MNEM_XSSUBQP: return "xssubqp";
		case PPC_MNEM_XSSUBQPO: return "xssubqpo";
		case PPC_MNEM_XSSUBSP: return "xssubsp";
		case PPC_MNEM_XSTDIVDP: return "xstdivdp";
		case PPC_MNEM_XSTSQRTDP: return "xstsqrtdp";
		case PPC_MNEM_XSTSTDCDP: return "xststdcdp";
		case PPC_MNEM_XSTSTDCQP: return "xststdcqp";
		case PPC_MNEM_XSTSTDCSP: return "xststdcsp";
		case PPC_MNEM_XSXEXPDP: return "xsxexpdp";
		case PPC_MNEM_XSXEXPQP: return "xsxexpqp";
		case PPC_MNEM_XSXSIGDP: return "xsxsigdp";
		case PPC_MNEM_XSXSIGQP: return "xsxsigqp";
		case PPC_MNEM_XVABSDP: return "xvabsdp";
		case PPC_MNEM_XVABSSP: return "xvabssp";
		case PPC_MNEM_XVADDDP: return "xvadddp";
		case PPC_MNEM_XVADDSP: return "xvaddsp";
		case PPC_MNEM_XVCMPEQDP: return "xvcmpeqdp";
		case PPC_MNEM_XVCMPEQSP: return "xvcmpeqsp";
		case PPC_MNEM_XVCMPGEDP: return "xvcmpgedp";
		case PPC_MNEM_XVCMPGESP: return "xvcmpgesp";
		case PPC_MNEM_XVCMPGTDP: return "xvcmpgtdp";
		case PPC_MNEM_XVCMPGTSP: return "xvcmpgtsp";
		case PPC_MNEM_XVCPSGNDP: return "xvcpsgndp";
		case PPC_MNEM_XVCPSGNSP: return "xvcpsgnsp";
		case PPC_MNEM_XVCVDPSP: return "xvcvdpsp";
		case PPC_MNEM_XVCVDPSXDS: return "xvcvdpsxds";
		case PPC_MNEM_XVCVDPSXWS: return "xvcvdpsxws";
		case PPC_MNEM_XVCVDPUXDS: return "xvcvdpuxds";
		case PPC_MNEM_XVCVDPUXWS: return "xvcvdpuxws";
		case PPC_MNEM_XVCVHPSP: return "xvcvhpsp";
		case PPC_MNEM_XVCVSPDP: return "xvcvspdp";
		case PPC_MNEM_XVCVSPHP: return "xvcvsphp";
		case PPC_MNEM_XVCVSPSXDS: return "xvcvspsxds";
		case PPC_MNEM_XVCVSPSXWS: return "xvcvspsxws";
		case PPC_MNEM_XVCVSPUXDS: return "xvcvspuxds";
		case PPC_MNEM_XVCVSPUXWS: return "xvcvspuxws";
		case PPC_MNEM_XVCVSXDDP: return "xvcvsxddp";
		case PPC_MNEM_XVCVSXDSP: return "xvcvsxdsp";
		case PPC_MNEM_XVCVSXWDP: return "xvcvsxwdp";
		case PPC_MNEM_XVCVSXWSP: return "xvcvsxwsp";
		case PPC_MNEM_XVCVUXDDP: return "xvcvuxddp";
		case PPC_MNEM_XVCVUXDSP: return "xvcvuxdsp";
		case PPC_MNEM_XVCVUXWDP: return "xvcvuxwdp";
		case PPC_MNEM_XVCVUXWSP: return "xvcvuxwsp";
		case PPC_MNEM_XVDIVDP: return "xvdivdp";
		case PPC_MNEM_XVDIVSP: return "xvdivsp";
		case PPC_MNEM_XVIEXPDP: return "xviexpdp";
		case PPC_MNEM_XVIEXPSP: return "xviexpsp";
		case PPC_MNEM_XVMADDADP: return "xvmaddadp";
		case PPC_MNEM_XVMADDASP: return "xvmaddasp";
		case PPC_MNEM_XVMADDMDP: return "xvmaddmdp";
		case PPC_MNEM_XVMADDMSP: return "xvmaddmsp";
		case PPC_MNEM_XVMAXDP: return "xvmaxdp";
		case PPC_MNEM_XVMAXSP: return "xvmaxsp";
		case PPC_MNEM_XVMINDP: return "xvmindp";
		case PPC_MNEM_XVMINSP: return "xvminsp";
		case PPC_MNEM_XVMOVDP: return "xvmovdp";
		case PPC_MNEM_XVMOVSP: return "xvmovsp";
		case PPC_MNEM_XVMSUBADP: return "xvmsubadp";
		case PPC_MNEM_XVMSUBASP: return "xvmsubasp";
		case PPC_MNEM_XVMSUBMDP: return "xvmsubmdp";
		case PPC_MNEM_XVMSUBMSP: return "xvmsubmsp";
		case PPC_MNEM_XVMULDP: return "xvmuldp";
		case PPC_MNEM_XVMULSP: return "xvmulsp";
		case PPC_MNEM_XVNABSDP: return "xvnabsdp";
		case PPC_MNEM_XVNABSSP: return "xvnabssp";
		case PPC_MNEM_XVNEGDP: return "xvnegdp";
		case PPC_MNEM_XVNEGSP: return "xvnegsp";
		case PPC_MNEM_XVNMADDADP: return "xvnmaddadp";
		case PPC_MNEM_XVNMADDASP: return "xvnmaddasp";
		case PPC_MNEM_XVNMADDMDP: return "xvnmaddmdp";
		case PPC_MNEM_XVNMADDMSP: return "xvnmaddmsp";
		case PPC_MNEM_XVNMSUBADP: return "xvnmsubadp";
		case PPC_MNEM_XVNMSUBASP: return "xvnmsubasp";
		case PPC_MNEM_XVNMSUBMDP: return "xvnmsubmdp";
		case PPC_MNEM_XVNMSUBMSP: return "xvnmsubmsp";
		case PPC_MNEM_XVRDPI: return "xvrdpi";
		case PPC_MNEM_XVRDPIC: return "xvrdpic";
		case PPC_MNEM_XVRDPIM: return "xvrdpim";
		case PPC_MNEM_XVRDPIP: return "xvrdpip";
		case PPC_MNEM_XVRDPIZ: return "xvrdpiz";
		case PPC_MNEM_XVREDP: return "xvredp";
		case PPC_MNEM_XVRESP: return "xvresp";
		case PPC_MNEM_XVRSPI: return "xvrspi";
		case PPC_MNEM_XVRSPIC: return "xvrspic";
		case PPC_MNEM_XVRSPIM: return "xvrspim";
		case PPC_MNEM_XVRSPIP: return "xvrspip";
		case PPC_MNEM_XVRSPIZ: return "xvrspiz";
		case PPC_MNEM_XVRSQRTEDP: return "xvrsqrtedp";
		case PPC_MNEM_XVRSQRTESP: return "xvrsqrtesp";
		case PPC_MNEM_XVSQRTDP: return "xvsqrtdp";
		case PPC_MNEM_XVSQRTSP: return "xvsqrtsp";
		case PPC_MNEM_XVSUBDP: return "xvsubdp";
		case PPC_MNEM_XVSUBSP: return "xvsubsp";
		case PPC_MNEM_XVTDIVDP: return "xvtdivdp";
		case PPC_MNEM_XVTDIVSP: return "xvtdivsp";
		case PPC_MNEM_XVTSQRTDP: return "xvtsqrtdp";
		case PPC_MNEM_XVTSQRTSP: return "xvtsqrtsp";
		case PPC_MNEM_XVTSTDCDP: return "xvtstdcdp";
		case PPC_MNEM_XVTSTDCSP: return "xvtstdcsp";
		case PPC_MNEM_XVXEXPDP: return "xvxexpdp";
		case PPC_MNEM_XVXEXPSP: return "xvxexpsp";
		case PPC_MNEM_XVXSIGDP: return "xvxsigdp";
		case PPC_MNEM_XVXSIGSP: return "xvxsigsp";
		case PPC_MNEM_XXBRD: return "xxbrd";
		case PPC_MNEM_XXBRH: return "xxbrh";
		case PPC_MNEM_XXBRQ: return "xxbrq";
		case PPC_MNEM_XXBRW: return "xxbrw";
		case PPC_MNEM_XXEXTRACTUW: return "xxextractuw";
		case PPC_MNEM_XXINSERTW: return "xxinsertw";
		case PPC_MNEM_XXLAND: return "xxland";
		case PPC_MNEM_XXLANDC: return "xxlandc";
		case PPC_MNEM_XXLEQV: return "xxleqv";
		case PPC_MNEM_XXLNAND: return "xxlnand";
		case PPC_MNEM_XXLNOR: return "xxlnor";
		case PPC_MNEM_XXLOR: return "xxlor";
		case PPC_MNEM_XXLORC: return "xxlorc";
		case PPC_MNEM_XXLXOR: return "xxlxor";
		case PPC_MNEM_XXMRGHD: return "xxmrghd";
		case PPC_MNEM_XXMRGHW: return "xxmrghw";
		case PPC_MNEM_XXMRGLD: return "xxmrgld";
		case PPC_MNEM_XXMRGLW: return "xxmrglw";
		case PPC_MNEM_XXPERM: return "xxperm";
		case PPC_MNEM_XXPERMDI: return "xxpermdi";
		case PPC_MNEM_XXPERMR: return "xxpermr";
		case PPC_MNEM_XXSEL: return "xxsel";
		case PPC_MNEM_XXSLDWI: return "xxsldwi";
		case PPC_MNEM_XXSPLTD: return "xxspltd";
		case PPC_MNEM_XXSPLTIB: return "xxspltib";
		case PPC_MNEM_XXSPLTW: return "xxspltw";
		case PPC_MNEM_XXSWAPD: return "xxswapd";
		case PPC_MNEM_YIELD: return "yield";
		default: return "ERROR";
	}
}

int ppc_disassemble(uint32_t insword, char *result)
{
	struct ppc_decoded dec;
	memset(&dec, 0, sizeof(dec));

	if(ppc_decode(insword, &dec))
		return -1;

	if(!(dec.mnemonic > PPC_MNEM_NONE && dec.mnemonic < PPC_MNEM_LAST_ENTRY))
		return -1;

	strcpy(result, mnem_to_str(dec.mnemonic));
	if(dec.properties & PPC_PROPERTY_DOTTED)
		strcat(result, ".");

	char buf[128] = {'\0'};
	switch(dec.operand_fmtstr) {
		case PPC_FMTSTR_GPR:
			sprintf(buf, "r%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_C_GPR:
			sprintf(buf, "r%d,%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_LPAREN_GPR_RPAREN_:
			sprintf(buf, "r%d,%d(r%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_NUM:
			sprintf(buf, "r%d,r%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__NEG_:
			sprintf(buf, "-");
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_GPR:
			sprintf(buf, "r%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_GPR:
			sprintf(buf, "r%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_FREG_C_FREG:
			sprintf(buf, "f%d,f%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR__POS_NUM_C_FLAG:
			sprintf(buf, "+%d,flag_names[%d]", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_VREG:
			sprintf(buf, "v%d,v%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_C_GPR_C_GPR:
			sprintf(buf, "%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FLAG_C_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "flag_names[%d],%d*cr%d+flag_names[%d],%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5], dec.operand_values[6]);
			break;
		case PPC_FMTSTR_FREG_C_NUM_LPAREN_GPR_RPAREN_:
			sprintf(buf, "f%d,%d(r%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_FREG_C_FREG_C_FREG:
			sprintf(buf, "f%d,f%d,f%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_FREG_C_NUM:
			sprintf(buf, "f%d,%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG_C_VSREG:
			sprintf(buf, "vs%d,vs%d,vs%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_VREG:
			sprintf(buf, "v%d,v%d,v%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__NEG_CREG_C_NUM:
			sprintf(buf, "-cr%d,%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR__POS_CREG_C_NUM:
			sprintf(buf, "+cr%d,%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG:
			sprintf(buf, "vs%d,vs%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_FREG_C_GPR_C_GPR:
			sprintf(buf, "f%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_NUM_C_GPR:
			sprintf(buf, "f%d,%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_GPR:
			sprintf(buf, "f%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_NUM:
			sprintf(buf, "%d*cr%d+flag_names[%d],%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_FLAG_C_NUM:
			sprintf(buf, "flag_names[%d],%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_LPAREN_NUM_RPAREN_:
			sprintf(buf, "r%d,%d(%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__POS_NUM_C_FLAG_C_NUM:
			sprintf(buf, "+%d,flag_names[%d],%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_FLAG_C_NUM:
			sprintf(buf, "%d,flag_names[%d],%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_NUM_C_NUM:
			sprintf(buf, "%d,%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_C_GPR_C_NUM:
			sprintf(buf, "r%d,%d,r%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR__POS_:
			sprintf(buf, "+");
			break;
		case PPC_FMTSTR_NUM_C_GPR_C_NUM:
			sprintf(buf, "%d,r%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_DEC_C_GPR_C_INT:
			sprintf(buf, "%d,r%d,%d", dec.operand_values[0], dec.operand_values[1], (int32_t)dec.operand_values[2]);
			break;
		case PPC_FMTSTR__POS_NUM_C_NUM_MUL_CREG_POS_FLAG_C_NUM:
			sprintf(buf, "+%d,%d*cr%d+flag_names[%d],%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_VREG_C_NUM:
			sprintf(buf, "v%d,%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM:
			sprintf(buf, "%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_VREG_C_VREG:
			sprintf(buf, "v%d,v%d,v%d,v%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_CREG_C_VSREG_C_VSREG:
			sprintf(buf, "cr%d,vs%d,vs%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_NUM:
			sprintf(buf, "r%d,%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG_C_FLAG:
			sprintf(buf, "%d*cr%d+flag_names[%d],%d*cr%d+flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5], dec.operand_values[6]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_GPR_C_NUM_C_NUM:
			sprintf(buf, "r%d,r%d,r%d,%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_VREG_C_GPR_C_GPR:
			sprintf(buf, "v%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__NEG_NUM_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "-%d,%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR__NEG_NUM:
			sprintf(buf, "-%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_FLAG_C_FLAG_C_FLAG:
			sprintf(buf, "flag_names[%d],flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_FREG_C_FREG:
			sprintf(buf, "f%d,f%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_FREG_C_NUM:
			sprintf(buf, "f%d,f%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FLAG_C_FLAG:
			sprintf(buf, "flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_NUM:
			sprintf(buf, "v%d,v%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_CREG_C_NUM:
			sprintf(buf, "cr%d,%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG_C_VSREG_C_NUM:
			sprintf(buf, "vs%d,vs%d,vs%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR__POS_CREG:
			sprintf(buf, "+cr%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_NUM_C_FREG_C_FREG:
			sprintf(buf, "%d,f%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__POS_NUM:
			sprintf(buf, "+%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_FLAG:
			sprintf(buf, "flag_names[%d]", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_VSREG_C_GPR_C_GPR:
			sprintf(buf, "vs%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_GPR:
			sprintf(buf, "%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_VREG:
			sprintf(buf, "r%d,r%d,v%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__NEG_CREG:
			sprintf(buf, "-cr%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR__NEG_NUM_C_NUM_MUL_CREG_POS_FLAG_C_NUM:
			sprintf(buf, "-%d,%d*cr%d+flag_names[%d],%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_FREG_C_FREG_C_FREG_C_NUM:
			sprintf(buf, "f%d,f%d,f%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_CREG:
			sprintf(buf, "cr%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_NUM_C_NUM_C_NUM:
			sprintf(buf, "r%d,r%d,%d,%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_FREG_C_NUM_LPAREN_NUM_RPAREN_:
			sprintf(buf, "f%d,%d(%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FLAG_C_NUM_MUL_CREG_POS_FLAG_C_FLAG:
			sprintf(buf, "flag_names[%d],%d*cr%d+flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_CREG_C_NUM_C_GPR_C_GPR:
			sprintf(buf, "cr%d,%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "%d*cr%d+flag_names[%d],%d*cr%d+flag_names[%d],%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5], dec.operand_values[6], dec.operand_values[7], dec.operand_values[8]);
			break;
		case PPC_FMTSTR__POS_NUM_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "+%d,%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_VSREG_C_NUM_C_GPR:
			sprintf(buf, "vs%d,%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_NUM_LPAREN_NUM_RPAREN_:
			sprintf(buf, "vs%d,%d(%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_CREG_C_NUM_C_FREG:
			sprintf(buf, "cr%d,%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_NUM_C_NUM:
			sprintf(buf, "r%d,r%d,%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR__NEG_NUM_C_FLAG:
			sprintf(buf, "-%d,flag_names[%d]", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_NUM_C_GPR:
			sprintf(buf, "v%d,%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__POS_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "+%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG_C_NUM:
			sprintf(buf, "vs%d,vs%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_NUM:
			sprintf(buf, "vs%d,%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_FCREG_C_GPR_C_GPR:
			sprintf(buf, "Fcr%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_NUM_MUL_CREG_POS_FLAG_C_NUM:
			sprintf(buf, "%d,%d*cr%d+flag_names[%d],%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_VREG:
			sprintf(buf, "v%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_CREG_C_FREG_C_FREG:
			sprintf(buf, "cr%d,f%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "%d*cr%d+flag_names[%d],%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5]);
			break;
		case PPC_FMTSTR_GPR_C_VREG:
			sprintf(buf, "r%d,v%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_VREG_C_NUM:
			sprintf(buf, "v%d,v%d,v%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_CREG_C_FREG_C_NUM:
			sprintf(buf, "cr%d,f%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VREG_C_NUM_LPAREN_GPR_RPAREN_:
			sprintf(buf, "v%d,%d(r%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_CREG_C_GPR_C_GPR:
			sprintf(buf, "cr%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_NUM_LPAREN_GPR_RPAREN_:
			sprintf(buf, "vs%d,%d(r%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "%d*cr%d+flag_names[%d],flag_names[%d],%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5], dec.operand_values[6]);
			break;
		case PPC_FMTSTR_CREG_C_GPR_C_NUM:
			sprintf(buf, "cr%d,r%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_FREG_C_FREG_C_NUM:
			sprintf(buf, "%d,f%d,f%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_GPR_C_NUM:
			sprintf(buf, "r%d,r%d,r%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_NUM_C_NUM:
			sprintf(buf, "%d,%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_CREG_C_VSREG_C_NUM:
			sprintf(buf, "cr%d,vs%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_VSREG:
			sprintf(buf, "r%d,vs%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_FLAG:
			sprintf(buf, "%d*cr%d+flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_FREG_C_NUM_LPAREN_GPR_RPAREN__C_NUM_C_NUM:
			sprintf(buf, "f%d,%d(r%d),%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR__POS_FLAG:
			sprintf(buf, "+flag_names[%d]", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_GPR_C_FREG:
			sprintf(buf, "r%d,f%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_FLAG_C_FLAG:
			sprintf(buf, "%d*cr%d+flag_names[%d],flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_NUM_C_NUM_C_GPR:
			sprintf(buf, "%d,%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_CREG_C_FREG:
			sprintf(buf, "cr%d,f%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_GPR_C_GPR:
			sprintf(buf, "r%d,r%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_FREG_C_GPR_C_GPR_C_NUM_C_NUM:
			sprintf(buf, "f%d,r%d,r%d,%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_C_NUM:
			sprintf(buf, "r%d,%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "flag_names[%d],%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_VREG_C_GPR:
			sprintf(buf, "v%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_FLAG_C_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "flag_names[%d],flag_names[%d],%d*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR__NEG_NUM_C_FLAG_C_NUM:
			sprintf(buf, "-%d,flag_names[%d],%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_GPR:
			sprintf(buf, "vs%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_NUM_LPAREN_NUM_RPAREN_:
			sprintf(buf, "v%d,%d(%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG:
			sprintf(buf, "f%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_CREG_C_VREG_C_VREG:
			sprintf(buf, "cr%d,v%d,v%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_FREG:
			sprintf(buf, "%d,f%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_CREG_C_VREG_C_NUM:
			sprintf(buf, "cr%d,v%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_FREG_C_NUM_C_NUM:
			sprintf(buf, "%d,f%d,%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_NUM_C_VREG_C_VREG_C_NUM:
			sprintf(buf, "%d,v%d,v%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_CREG_C_VSREG:
			sprintf(buf, "cr%d,vs%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_CREG_C_CREG:
			sprintf(buf, "cr%d,cr%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_GPR_C_CREG:
			sprintf(buf, "r%d,cr%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_NUM_C_NUM:
			sprintf(buf, "v%d,v%d,%d,%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG_C_VSREG_C_VSREG:
			sprintf(buf, "vs%d,vs%d,vs%d,vs%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_GPR_C_INT16:
			sprintf(buf, "r%d,%d", dec.operand_values[0], (int16_t)dec.operand_values[1]);
			break;
		case PPC_FMTSTR_DEC_C_GPR_C_INT16:
			sprintf(buf, "%d,r%d,%d", dec.operand_values[0], dec.operand_values[1], (int16_t)dec.operand_values[2]);
			break;
		default:
			break;
	}

	if(buf[0]) {
		strcat(result, " ");
		strcat(result, buf);
	}

	return 0;
}
