#include <string.h>
#include <stdio.h>

#include "disassembler.h"

static const char *mnem_to_str(enum ppc_mnemonic mnem)
{
	switch(mnem)
	{
		case PPC_MNEM_ABS: return "ABS";
		case PPC_MNEM_ABSO: return "ABSO";
		case PPC_MNEM_ADD: return "ADD";
		case PPC_MNEM_ADDC: return "ADDC";
		case PPC_MNEM_ADDCO: return "ADDCO";
		case PPC_MNEM_ADDE: return "ADDE";
		case PPC_MNEM_ADDEO: return "ADDEO";
		case PPC_MNEM_ADDEX: return "ADDEX";
		case PPC_MNEM_ADDG6S: return "ADDG6S";
		case PPC_MNEM_ADDI: return "ADDI";
		case PPC_MNEM_ADDIC: return "ADDIC";
		case PPC_MNEM_ADDIS: return "ADDIS";
		case PPC_MNEM_ADDME: return "ADDME";
		case PPC_MNEM_ADDMEO: return "ADDMEO";
		case PPC_MNEM_ADDO: return "ADDO";
		case PPC_MNEM_ADDPCIS: return "ADDPCIS";
		case PPC_MNEM_ADDZE: return "ADDZE";
		case PPC_MNEM_ADDZEO: return "ADDZEO";
		case PPC_MNEM_AND: return "AND";
		case PPC_MNEM_ANDC: return "ANDC";
		case PPC_MNEM_ANDI: return "ANDI";
		case PPC_MNEM_ANDIS: return "ANDIS";
		case PPC_MNEM_ATTN: return "ATTN";
		case PPC_MNEM_B: return "B";
		case PPC_MNEM_BA: return "BA";
		case PPC_MNEM_BBELR: return "BBELR";
		case PPC_MNEM_BBLELS: return "BBLELS";
		case PPC_MNEM_BC: return "BC";
		case PPC_MNEM_BCA: return "BCA";
		case PPC_MNEM_BCCTR: return "BCCTR";
		case PPC_MNEM_BCCTRL: return "BCCTRL";
		case PPC_MNEM_BCDADD: return "BCDADD";
		case PPC_MNEM_BCDCFN: return "BCDCFN";
		case PPC_MNEM_BCDCFSQ: return "BCDCFSQ";
		case PPC_MNEM_BCDCFZ: return "BCDCFZ";
		case PPC_MNEM_BCDCPSGN: return "BCDCPSGN";
		case PPC_MNEM_BCDCTN: return "BCDCTN";
		case PPC_MNEM_BCDCTSQ: return "BCDCTSQ";
		case PPC_MNEM_BCDCTZ: return "BCDCTZ";
		case PPC_MNEM_BCDS: return "BCDS";
		case PPC_MNEM_BCDSETSGN: return "BCDSETSGN";
		case PPC_MNEM_BCDSR: return "BCDSR";
		case PPC_MNEM_BCDSUB: return "BCDSUB";
		case PPC_MNEM_BCDTRUNC: return "BCDTRUNC";
		case PPC_MNEM_BCDUS: return "BCDUS";
		case PPC_MNEM_BCDUTRUNC: return "BCDUTRUNC";
		case PPC_MNEM_BCL: return "BCL";
		case PPC_MNEM_BCLA: return "BCLA";
		case PPC_MNEM_BCLR: return "BCLR";
		case PPC_MNEM_BCLRL: return "BCLRL";
		case PPC_MNEM_BCTAR: return "BCTAR";
		case PPC_MNEM_BCTARL: return "BCTARL";
		case PPC_MNEM_BCTR: return "BCTR";
		case PPC_MNEM_BCTRL: return "BCTRL";
		case PPC_MNEM_BDNZ: return "BDNZ";
		case PPC_MNEM_BDNZA: return "BDNZA";
		case PPC_MNEM_BDNZF: return "BDNZF";
		case PPC_MNEM_BDNZFA: return "BDNZFA";
		case PPC_MNEM_BDNZFL: return "BDNZFL";
		case PPC_MNEM_BDNZFLA: return "BDNZFLA";
		case PPC_MNEM_BDNZFLR: return "BDNZFLR";
		case PPC_MNEM_BDNZFLRL: return "BDNZFLRL";
		case PPC_MNEM_BDNZL: return "BDNZL";
		case PPC_MNEM_BDNZLA: return "BDNZLA";
		case PPC_MNEM_BDNZLR: return "BDNZLR";
		case PPC_MNEM_BDNZLRL: return "BDNZLRL";
		case PPC_MNEM_BDNZT: return "BDNZT";
		case PPC_MNEM_BDNZTA: return "BDNZTA";
		case PPC_MNEM_BDNZTL: return "BDNZTL";
		case PPC_MNEM_BDNZTLA: return "BDNZTLA";
		case PPC_MNEM_BDNZTLR: return "BDNZTLR";
		case PPC_MNEM_BDNZTLRL: return "BDNZTLRL";
		case PPC_MNEM_BDZ: return "BDZ";
		case PPC_MNEM_BDZA: return "BDZA";
		case PPC_MNEM_BDZF: return "BDZF";
		case PPC_MNEM_BDZFA: return "BDZFA";
		case PPC_MNEM_BDZFL: return "BDZFL";
		case PPC_MNEM_BDZFLA: return "BDZFLA";
		case PPC_MNEM_BDZFLR: return "BDZFLR";
		case PPC_MNEM_BDZFLRL: return "BDZFLRL";
		case PPC_MNEM_BDZL: return "BDZL";
		case PPC_MNEM_BDZLA: return "BDZLA";
		case PPC_MNEM_BDZLR: return "BDZLR";
		case PPC_MNEM_BDZLRL: return "BDZLRL";
		case PPC_MNEM_BDZT: return "BDZT";
		case PPC_MNEM_BDZTA: return "BDZTA";
		case PPC_MNEM_BDZTL: return "BDZTL";
		case PPC_MNEM_BDZTLA: return "BDZTLA";
		case PPC_MNEM_BDZTLR: return "BDZTLR";
		case PPC_MNEM_BDZTLRL: return "BDZTLRL";
		case PPC_MNEM_BEQ: return "BEQ";
		case PPC_MNEM_BEQA: return "BEQA";
		case PPC_MNEM_BEQCTR: return "BEQCTR";
		case PPC_MNEM_BEQCTRL: return "BEQCTRL";
		case PPC_MNEM_BEQL: return "BEQL";
		case PPC_MNEM_BEQLA: return "BEQLA";
		case PPC_MNEM_BEQLR: return "BEQLR";
		case PPC_MNEM_BEQLRL: return "BEQLRL";
		case PPC_MNEM_BGE: return "BGE";
		case PPC_MNEM_BGEA: return "BGEA";
		case PPC_MNEM_BGECTR: return "BGECTR";
		case PPC_MNEM_BGECTRL: return "BGECTRL";
		case PPC_MNEM_BGEL: return "BGEL";
		case PPC_MNEM_BGELA: return "BGELA";
		case PPC_MNEM_BGELR: return "BGELR";
		case PPC_MNEM_BGELRL: return "BGELRL";
		case PPC_MNEM_BGT: return "BGT";
		case PPC_MNEM_BGTA: return "BGTA";
		case PPC_MNEM_BGTCTR: return "BGTCTR";
		case PPC_MNEM_BGTCTRL: return "BGTCTRL";
		case PPC_MNEM_BGTL: return "BGTL";
		case PPC_MNEM_BGTLA: return "BGTLA";
		case PPC_MNEM_BGTLR: return "BGTLR";
		case PPC_MNEM_BGTLRL: return "BGTLRL";
		case PPC_MNEM_BL: return "BL";
		case PPC_MNEM_BLA: return "BLA";
		case PPC_MNEM_BLE: return "BLE";
		case PPC_MNEM_BLEA: return "BLEA";
		case PPC_MNEM_BLECTR: return "BLECTR";
		case PPC_MNEM_BLECTRL: return "BLECTRL";
		case PPC_MNEM_BLEL: return "BLEL";
		case PPC_MNEM_BLELA: return "BLELA";
		case PPC_MNEM_BLELR: return "BLELR";
		case PPC_MNEM_BLELRL: return "BLELRL";
		case PPC_MNEM_BLR: return "BLR";
		case PPC_MNEM_BLRL: return "BLRL";
		case PPC_MNEM_BLT: return "BLT";
		case PPC_MNEM_BLTA: return "BLTA";
		case PPC_MNEM_BLTCTR: return "BLTCTR";
		case PPC_MNEM_BLTCTRL: return "BLTCTRL";
		case PPC_MNEM_BLTL: return "BLTL";
		case PPC_MNEM_BLTLA: return "BLTLA";
		case PPC_MNEM_BLTLR: return "BLTLR";
		case PPC_MNEM_BLTLRL: return "BLTLRL";
		case PPC_MNEM_BNE: return "BNE";
		case PPC_MNEM_BNEA: return "BNEA";
		case PPC_MNEM_BNECTR: return "BNECTR";
		case PPC_MNEM_BNECTRL: return "BNECTRL";
		case PPC_MNEM_BNEL: return "BNEL";
		case PPC_MNEM_BNELA: return "BNELA";
		case PPC_MNEM_BNELR: return "BNELR";
		case PPC_MNEM_BNELRL: return "BNELRL";
		case PPC_MNEM_BNS: return "BNS";
		case PPC_MNEM_BNSA: return "BNSA";
		case PPC_MNEM_BNSCTR: return "BNSCTR";
		case PPC_MNEM_BNSCTRL: return "BNSCTRL";
		case PPC_MNEM_BNSL: return "BNSL";
		case PPC_MNEM_BNSLA: return "BNSLA";
		case PPC_MNEM_BNSLR: return "BNSLR";
		case PPC_MNEM_BNSLRL: return "BNSLRL";
		case PPC_MNEM_BPERMD: return "BPERMD";
		case PPC_MNEM_BSO: return "BSO";
		case PPC_MNEM_BSOA: return "BSOA";
		case PPC_MNEM_BSOCTR: return "BSOCTR";
		case PPC_MNEM_BSOCTRL: return "BSOCTRL";
		case PPC_MNEM_BSOL: return "BSOL";
		case PPC_MNEM_BSOLA: return "BSOLA";
		case PPC_MNEM_BSOLR: return "BSOLR";
		case PPC_MNEM_BSOLRL: return "BSOLRL";
		case PPC_MNEM_CBCDTD: return "CBCDTD";
		case PPC_MNEM_CDTBCD: return "CDTBCD";
		case PPC_MNEM_CLCS: return "CLCS";
		case PPC_MNEM_CLF: return "CLF";
		case PPC_MNEM_CLI: return "CLI";
		case PPC_MNEM_CLRBHRB: return "CLRBHRB";
		case PPC_MNEM_CLRLDI: return "CLRLDI";
		case PPC_MNEM_CLRLWI: return "CLRLWI";
		case PPC_MNEM_CMPB: return "CMPB";
		case PPC_MNEM_CMPD: return "CMPD";
		case PPC_MNEM_CMPDI: return "CMPDI";
		case PPC_MNEM_CMPEQB: return "CMPEQB";
		case PPC_MNEM_CMPLD: return "CMPLD";
		case PPC_MNEM_CMPLDI: return "CMPLDI";
		case PPC_MNEM_CMPLW: return "CMPLW";
		case PPC_MNEM_CMPLWI: return "CMPLWI";
		case PPC_MNEM_CMPRB: return "CMPRB";
		case PPC_MNEM_CMPW: return "CMPW";
		case PPC_MNEM_CMPWI: return "CMPWI";
		case PPC_MNEM_CNTLZD: return "CNTLZD";
		case PPC_MNEM_CNTLZW: return "CNTLZW";
		case PPC_MNEM_CNTTZD: return "CNTTZD";
		case PPC_MNEM_CNTTZW: return "CNTTZW";
		case PPC_MNEM_COPY: return "COPY";
		case PPC_MNEM_CPABORT: return "CPABORT";
		case PPC_MNEM_CRAND: return "CRAND";
		case PPC_MNEM_CRANDC: return "CRANDC";
		case PPC_MNEM_CRCLR: return "CRCLR";
		case PPC_MNEM_CREQV: return "CREQV";
		case PPC_MNEM_CRMOVE: return "CRMOVE";
		case PPC_MNEM_CRNAND: return "CRNAND";
		case PPC_MNEM_CRNOR: return "CRNOR";
		case PPC_MNEM_CRNOT: return "CRNOT";
		case PPC_MNEM_CROR: return "CROR";
		case PPC_MNEM_CRORC: return "CRORC";
		case PPC_MNEM_CRSET: return "CRSET";
		case PPC_MNEM_CRXOR: return "CRXOR";
		case PPC_MNEM_DADD: return "DADD";
		case PPC_MNEM_DADDQ: return "DADDQ";
		case PPC_MNEM_DARN: return "DARN";
		case PPC_MNEM_DCBA: return "DCBA";
		case PPC_MNEM_DCBAL: return "DCBAL";
		case PPC_MNEM_DCBF: return "DCBF";
		case PPC_MNEM_DCBFEP: return "DCBFEP";
		case PPC_MNEM_DCBFL: return "DCBFL";
		case PPC_MNEM_DCBI: return "DCBI";
		case PPC_MNEM_DCBLC: return "DCBLC";
		case PPC_MNEM_DCBLCE: return "DCBLCE";
		case PPC_MNEM_DCBLQ: return "DCBLQ";
		case PPC_MNEM_DCBST: return "DCBST";
		case PPC_MNEM_DCBSTEP: return "DCBSTEP";
		case PPC_MNEM_DCBT: return "DCBT";
		case PPC_MNEM_DCBTEP: return "DCBTEP";
		case PPC_MNEM_DCBTLS: return "DCBTLS";
		case PPC_MNEM_DCBTLSE: return "DCBTLSE";
		case PPC_MNEM_DCBTST: return "DCBTST";
		case PPC_MNEM_DCBTSTEP: return "DCBTSTEP";
		case PPC_MNEM_DCBTSTLS: return "DCBTSTLS";
		case PPC_MNEM_DCBTSTLSE: return "DCBTSTLSE";
		case PPC_MNEM_DCBTSTT: return "DCBTSTT";
		case PPC_MNEM_DCBTT: return "DCBTT";
		case PPC_MNEM_DCBZ: return "DCBZ";
		case PPC_MNEM_DCBZEP: return "DCBZEP";
		case PPC_MNEM_DCBZL: return "DCBZL";
		case PPC_MNEM_DCBZ_L: return "DCBZ_L";
		case PPC_MNEM_DCCCI: return "DCCCI";
		case PPC_MNEM_DCFFIX: return "DCFFIX";
		case PPC_MNEM_DCFFIXQ: return "DCFFIXQ";
		case PPC_MNEM_DCI: return "DCI";
		case PPC_MNEM_DCLST: return "DCLST";
		case PPC_MNEM_DCMPO: return "DCMPO";
		case PPC_MNEM_DCMPOQ: return "DCMPOQ";
		case PPC_MNEM_DCMPU: return "DCMPU";
		case PPC_MNEM_DCMPUQ: return "DCMPUQ";
		case PPC_MNEM_DCREAD: return "DCREAD";
		case PPC_MNEM_DCTDP: return "DCTDP";
		case PPC_MNEM_DCTFIX: return "DCTFIX";
		case PPC_MNEM_DCTFIXQ: return "DCTFIXQ";
		case PPC_MNEM_DCTQPQ: return "DCTQPQ";
		case PPC_MNEM_DDEDPD: return "DDEDPD";
		case PPC_MNEM_DDEDPDQ: return "DDEDPDQ";
		case PPC_MNEM_DDIV: return "DDIV";
		case PPC_MNEM_DDIVQ: return "DDIVQ";
		case PPC_MNEM_DENBCD: return "DENBCD";
		case PPC_MNEM_DENBCDQ: return "DENBCDQ";
		case PPC_MNEM_DIEX: return "DIEX";
		case PPC_MNEM_DIEXQ: return "DIEXQ";
		case PPC_MNEM_DIV: return "DIV";
		case PPC_MNEM_DIVD: return "DIVD";
		case PPC_MNEM_DIVDE: return "DIVDE";
		case PPC_MNEM_DIVDEO: return "DIVDEO";
		case PPC_MNEM_DIVDEU: return "DIVDEU";
		case PPC_MNEM_DIVDEUO: return "DIVDEUO";
		case PPC_MNEM_DIVDO: return "DIVDO";
		case PPC_MNEM_DIVDU: return "DIVDU";
		case PPC_MNEM_DIVDUO: return "DIVDUO";
		case PPC_MNEM_DIVO: return "DIVO";
		case PPC_MNEM_DIVS: return "DIVS";
		case PPC_MNEM_DIVSO: return "DIVSO";
		case PPC_MNEM_DIVW: return "DIVW";
		case PPC_MNEM_DIVWE: return "DIVWE";
		case PPC_MNEM_DIVWEO: return "DIVWEO";
		case PPC_MNEM_DIVWEU: return "DIVWEU";
		case PPC_MNEM_DIVWEUO: return "DIVWEUO";
		case PPC_MNEM_DIVWO: return "DIVWO";
		case PPC_MNEM_DIVWU: return "DIVWU";
		case PPC_MNEM_DIVWUO: return "DIVWUO";
		case PPC_MNEM_DLMZB: return "DLMZB";
		case PPC_MNEM_DMUL: return "DMUL";
		case PPC_MNEM_DMULQ: return "DMULQ";
		case PPC_MNEM_DNH: return "DNH";
		case PPC_MNEM_DNI: return "DNI";
		case PPC_MNEM_DOZ: return "DOZ";
		case PPC_MNEM_DOZE: return "DOZE";
		case PPC_MNEM_DOZI: return "DOZI";
		case PPC_MNEM_DOZO: return "DOZO";
		case PPC_MNEM_DQUA: return "DQUA";
		case PPC_MNEM_DQUAI: return "DQUAI";
		case PPC_MNEM_DQUAIQ: return "DQUAIQ";
		case PPC_MNEM_DQUAQ: return "DQUAQ";
		case PPC_MNEM_DRDPQ: return "DRDPQ";
		case PPC_MNEM_DRINTN: return "DRINTN";
		case PPC_MNEM_DRINTNQ: return "DRINTNQ";
		case PPC_MNEM_DRINTX: return "DRINTX";
		case PPC_MNEM_DRINTXQ: return "DRINTXQ";
		case PPC_MNEM_DRRND: return "DRRND";
		case PPC_MNEM_DRRNDQ: return "DRRNDQ";
		case PPC_MNEM_DRSP: return "DRSP";
		case PPC_MNEM_DSCLI: return "DSCLI";
		case PPC_MNEM_DSCLIQ: return "DSCLIQ";
		case PPC_MNEM_DSCRI: return "DSCRI";
		case PPC_MNEM_DSCRIQ: return "DSCRIQ";
		case PPC_MNEM_DSN: return "DSN";
		case PPC_MNEM_DSS: return "DSS";
		case PPC_MNEM_DSSALL: return "DSSALL";
		case PPC_MNEM_DST: return "DST";
		case PPC_MNEM_DSTST: return "DSTST";
		case PPC_MNEM_DSTSTT: return "DSTSTT";
		case PPC_MNEM_DSTT: return "DSTT";
		case PPC_MNEM_DSUB: return "DSUB";
		case PPC_MNEM_DSUBQ: return "DSUBQ";
		case PPC_MNEM_DTSTDC: return "DTSTDC";
		case PPC_MNEM_DTSTDCQ: return "DTSTDCQ";
		case PPC_MNEM_DTSTDG: return "DTSTDG";
		case PPC_MNEM_DTSTDGQ: return "DTSTDGQ";
		case PPC_MNEM_DTSTEX: return "DTSTEX";
		case PPC_MNEM_DTSTEXQ: return "DTSTEXQ";
		case PPC_MNEM_DTSTSF: return "DTSTSF";
		case PPC_MNEM_DTSTSFI: return "DTSTSFI";
		case PPC_MNEM_DTSTSFIQ: return "DTSTSFIQ";
		case PPC_MNEM_DTSTSFQ: return "DTSTSFQ";
		case PPC_MNEM_DXEX: return "DXEX";
		case PPC_MNEM_DXEXQ: return "DXEXQ";
		case PPC_MNEM_ECIWX: return "ECIWX";
		case PPC_MNEM_ECOWX: return "ECOWX";
		case PPC_MNEM_EFDCFUF: return "EFDCFUF";
		case PPC_MNEM_EFDCTH: return "EFDCTH";
		case PPC_MNEM_EFDCTSF: return "EFDCTSF";
		case PPC_MNEM_EFDCTSI: return "EFDCTSI";
		case PPC_MNEM_EFDCTUF: return "EFDCTUF";
		case PPC_MNEM_EFDCTUI: return "EFDCTUI";
		case PPC_MNEM_EFSADD: return "EFSADD";
		case PPC_MNEM_EFSCFH: return "EFSCFH";
		case PPC_MNEM_EFSCFSF: return "EFSCFSF";
		case PPC_MNEM_EFSCFSI: return "EFSCFSI";
		case PPC_MNEM_EFSCFUF: return "EFSCFUF";
		case PPC_MNEM_EFSCFUI: return "EFSCFUI";
		case PPC_MNEM_EFSCTSIZ: return "EFSCTSIZ";
		case PPC_MNEM_EFSCTUIZ: return "EFSCTUIZ";
		case PPC_MNEM_EFSDIV: return "EFSDIV";
		case PPC_MNEM_EFSMSUB: return "EFSMSUB";
		case PPC_MNEM_EFSMUL: return "EFSMUL";
		case PPC_MNEM_EFSNABS: return "EFSNABS";
		case PPC_MNEM_EFSNMADD: return "EFSNMADD";
		case PPC_MNEM_EFSNMSUB: return "EFSNMSUB";
		case PPC_MNEM_EFSSUB: return "EFSSUB";
		case PPC_MNEM_EHPRIV: return "EHPRIV";
		case PPC_MNEM_EIEIO: return "EIEIO";
		case PPC_MNEM_EQV: return "EQV";
		case PPC_MNEM_ERATILX: return "ERATILX";
		case PPC_MNEM_ERATIVAX: return "ERATIVAX";
		case PPC_MNEM_ERATRE: return "ERATRE";
		case PPC_MNEM_ERATSX: return "ERATSX";
		case PPC_MNEM_ERATWE: return "ERATWE";
		case PPC_MNEM_EVADDSMIAAW: return "EVADDSMIAAW";
		case PPC_MNEM_EVAND: return "EVAND";
		case PPC_MNEM_EVANDC: return "EVANDC";
		case PPC_MNEM_EVCMPEQ: return "EVCMPEQ";
		case PPC_MNEM_EVCMPLTU: return "EVCMPLTU";
		case PPC_MNEM_EVEQV: return "EVEQV";
		case PPC_MNEM_EVEXTSB: return "EVEXTSB";
		case PPC_MNEM_EVEXTSH: return "EVEXTSH";
		case PPC_MNEM_EVFSCFH: return "EVFSCFH";
		case PPC_MNEM_EVFSCFSF: return "EVFSCFSF";
		case PPC_MNEM_EVFSCFSI: return "EVFSCFSI";
		case PPC_MNEM_EVFSCFUF: return "EVFSCFUF";
		case PPC_MNEM_EVFSCFUI: return "EVFSCFUI";
		case PPC_MNEM_EVFSCTSIZ: return "EVFSCTSIZ";
		case PPC_MNEM_EVFSCTUIZ: return "EVFSCTUIZ";
		case PPC_MNEM_EVFSDIV: return "EVFSDIV";
		case PPC_MNEM_EVFSMSUB: return "EVFSMSUB";
		case PPC_MNEM_EVFSNABS: return "EVFSNABS";
		case PPC_MNEM_EVFSNMADD: return "EVFSNMADD";
		case PPC_MNEM_EVFSNMSUB: return "EVFSNMSUB";
		case PPC_MNEM_EVFSSQRT: return "EVFSSQRT";
		case PPC_MNEM_EVFSSUB: return "EVFSSUB";
		case PPC_MNEM_EVLDD: return "EVLDD";
		case PPC_MNEM_EVLDDEPX: return "EVLDDEPX";
		case PPC_MNEM_EVLDH: return "EVLDH";
		case PPC_MNEM_EVLDW: return "EVLDW";
		case PPC_MNEM_EVLHHESPLAT: return "EVLHHESPLAT";
		case PPC_MNEM_EVMHESMF: return "EVMHESMF";
		case PPC_MNEM_EVMHESMFAAW: return "EVMHESMFAAW";
		case PPC_MNEM_EVMHESMFANW: return "EVMHESMFANW";
		case PPC_MNEM_EVMHESMI: return "EVMHESMI";
		case PPC_MNEM_EVMHESMIANW: return "EVMHESMIANW";
		case PPC_MNEM_EVMHESSFAAW: return "EVMHESSFAAW";
		case PPC_MNEM_EVMHESSFANW: return "EVMHESSFANW";
		case PPC_MNEM_EVMHESSIANW: return "EVMHESSIANW";
		case PPC_MNEM_EVMHEUMIANW: return "EVMHEUMIANW";
		case PPC_MNEM_EVMHOGUMIAA: return "EVMHOGUMIAA";
		case PPC_MNEM_EVMHOGUMIAN: return "EVMHOGUMIAN";
		case PPC_MNEM_EVMHOSSIAAW: return "EVMHOSSIAAW";
		case PPC_MNEM_EVMHOSSIANW: return "EVMHOSSIANW";
		case PPC_MNEM_EVMHOUMIA: return "EVMHOUMIA";
		case PPC_MNEM_EVMWHSSIAN: return "EVMWHSSIAN";
		case PPC_MNEM_EVMWHSSMAA: return "EVMWHSSMAA";
		case PPC_MNEM_EVMWHUMIA: return "EVMWHUMIA";
		case PPC_MNEM_EVMWLSMF: return "EVMWLSMF";
		case PPC_MNEM_EVMWLSMFAAW: return "EVMWLSMFAAW";
		case PPC_MNEM_EVMWLSMFANW: return "EVMWLSMFANW";
		case PPC_MNEM_EVMWLSMIANW: return "EVMWLSMIANW";
		case PPC_MNEM_EVMWLSSFAAW: return "EVMWLSSFAAW";
		case PPC_MNEM_EVMWLSSFANW: return "EVMWLSSFANW";
		case PPC_MNEM_EVMWLUMIANW: return "EVMWLUMIANW";
		case PPC_MNEM_EVMWLUSIANW: return "EVMWLUSIANW";
		case PPC_MNEM_EVMWSMF: return "EVMWSMF";
		case PPC_MNEM_EVMWSMFAA: return "EVMWSMFAA";
		case PPC_MNEM_EVMWSMFAN: return "EVMWSMFAN";
		case PPC_MNEM_EVMWSSF: return "EVMWSSF";
		case PPC_MNEM_EVMWSSFAA: return "EVMWSSFAA";
		case PPC_MNEM_EVMWSSFAN: return "EVMWSSFAN";
		case PPC_MNEM_EVNEG: return "EVNEG";
		case PPC_MNEM_EVNOR: return "EVNOR";
		case PPC_MNEM_EVORC: return "EVORC";
		case PPC_MNEM_EVSTDDEPX: return "EVSTDDEPX";
		case PPC_MNEM_EVSTWHO: return "EVSTWHO";
		case PPC_MNEM_EVSTWHOX: return "EVSTWHOX";
		case PPC_MNEM_EVSUBFSMIAAW: return "EVSUBFSMIAAW";
		case PPC_MNEM_EVSUBFSSIAAW: return "EVSUBFSSIAAW";
		case PPC_MNEM_EVSUBFUMIAAW: return "EVSUBFUMIAAW";
		case PPC_MNEM_EVSUBFUSIAAW: return "EVSUBFUSIAAW";
		case PPC_MNEM_EXTSB: return "EXTSB";
		case PPC_MNEM_EXTSH: return "EXTSH";
		case PPC_MNEM_EXTSW: return "EXTSW";
		case PPC_MNEM_EXTSWSLI: return "EXTSWSLI";
		case PPC_MNEM_FABS: return "FABS";
		case PPC_MNEM_FADD: return "FADD";
		case PPC_MNEM_FADDS: return "FADDS";
		case PPC_MNEM_FCFID: return "FCFID";
		case PPC_MNEM_FCFIDS: return "FCFIDS";
		case PPC_MNEM_FCFIDU: return "FCFIDU";
		case PPC_MNEM_FCFIDUS: return "FCFIDUS";
		case PPC_MNEM_FCMPO: return "FCMPO";
		case PPC_MNEM_FCMPU: return "FCMPU";
		case PPC_MNEM_FCPSGN: return "FCPSGN";
		case PPC_MNEM_FCTID: return "FCTID";
		case PPC_MNEM_FCTIDU: return "FCTIDU";
		case PPC_MNEM_FCTIDUZ: return "FCTIDUZ";
		case PPC_MNEM_FCTIDZ: return "FCTIDZ";
		case PPC_MNEM_FCTIW: return "FCTIW";
		case PPC_MNEM_FCTIWU: return "FCTIWU";
		case PPC_MNEM_FCTIWUZ: return "FCTIWUZ";
		case PPC_MNEM_FCTIWZ: return "FCTIWZ";
		case PPC_MNEM_FDIV: return "FDIV";
		case PPC_MNEM_FDIVS: return "FDIVS";
		case PPC_MNEM_FMADD: return "FMADD";
		case PPC_MNEM_FMADDS: return "FMADDS";
		case PPC_MNEM_FMR: return "FMR";
		case PPC_MNEM_FMRGEW: return "FMRGEW";
		case PPC_MNEM_FMRGOW: return "FMRGOW";
		case PPC_MNEM_FMSUB: return "FMSUB";
		case PPC_MNEM_FMSUBS: return "FMSUBS";
		case PPC_MNEM_FMUL: return "FMUL";
		case PPC_MNEM_FMULS: return "FMULS";
		case PPC_MNEM_FNABS: return "FNABS";
		case PPC_MNEM_FNEG: return "FNEG";
		case PPC_MNEM_FNMADD: return "FNMADD";
		case PPC_MNEM_FNMADDS: return "FNMADDS";
		case PPC_MNEM_FNMSUB: return "FNMSUB";
		case PPC_MNEM_FNMSUBS: return "FNMSUBS";
		case PPC_MNEM_FRE: return "FRE";
		case PPC_MNEM_FRES: return "FRES";
		case PPC_MNEM_FRIM: return "FRIM";
		case PPC_MNEM_FRIN: return "FRIN";
		case PPC_MNEM_FRIP: return "FRIP";
		case PPC_MNEM_FRIZ: return "FRIZ";
		case PPC_MNEM_FRSP: return "FRSP";
		case PPC_MNEM_FRSQRTE: return "FRSQRTE";
		case PPC_MNEM_FRSQRTES: return "FRSQRTES";
		case PPC_MNEM_FSEL: return "FSEL";
		case PPC_MNEM_FSQRT: return "FSQRT";
		case PPC_MNEM_FSQRTS: return "FSQRTS";
		case PPC_MNEM_FSUB: return "FSUB";
		case PPC_MNEM_FSUBS: return "FSUBS";
		case PPC_MNEM_FTDIV: return "FTDIV";
		case PPC_MNEM_FTSQRT: return "FTSQRT";
		case PPC_MNEM_HRFID: return "HRFID";
		case PPC_MNEM_HWSYNC: return "HWSYNC";
		case PPC_MNEM_ICBI: return "ICBI";
		case PPC_MNEM_ICBIEP: return "ICBIEP";
		case PPC_MNEM_ICBLC: return "ICBLC";
		case PPC_MNEM_ICBLCE: return "ICBLCE";
		case PPC_MNEM_ICBLQ: return "ICBLQ";
		case PPC_MNEM_ICBT: return "ICBT";
		case PPC_MNEM_ICCCI: return "ICCCI";
		case PPC_MNEM_ICI: return "ICI";
		case PPC_MNEM_ICREAD: return "ICREAD";
		case PPC_MNEM_ICSWEPX: return "ICSWEPX";
		case PPC_MNEM_ICSWX: return "ICSWX";
		case PPC_MNEM_ISEL: return "ISEL";
		case PPC_MNEM_ISELEQ: return "ISELEQ";
		case PPC_MNEM_ISELGT: return "ISELGT";
		case PPC_MNEM_ISELLT: return "ISELLT";
		case PPC_MNEM_ISYNC: return "ISYNC";
		case PPC_MNEM_LBARX: return "LBARX";
		case PPC_MNEM_LBDCBX: return "LBDCBX";
		case PPC_MNEM_LBDX: return "LBDX";
		case PPC_MNEM_LBEPX: return "LBEPX";
		case PPC_MNEM_LBZ: return "LBZ";
		case PPC_MNEM_LBZCIX: return "LBZCIX";
		case PPC_MNEM_LBZU: return "LBZU";
		case PPC_MNEM_LBZUX: return "LBZUX";
		case PPC_MNEM_LBZX: return "LBZX";
		case PPC_MNEM_LD: return "LD";
		case PPC_MNEM_LDARX: return "LDARX";
		case PPC_MNEM_LDAT: return "LDAT";
		case PPC_MNEM_LDAWX: return "LDAWX";
		case PPC_MNEM_LDBRX: return "LDBRX";
		case PPC_MNEM_LDCIX: return "LDCIX";
		case PPC_MNEM_LDDX: return "LDDX";
		case PPC_MNEM_LDMX: return "LDMX";
		case PPC_MNEM_LDU: return "LDU";
		case PPC_MNEM_LDUX: return "LDUX";
		case PPC_MNEM_LDX: return "LDX";
		case PPC_MNEM_LFD: return "LFD";
		case PPC_MNEM_LFDDX: return "LFDDX";
		case PPC_MNEM_LFDEPX: return "LFDEPX";
		case PPC_MNEM_LFDP: return "LFDP";
		case PPC_MNEM_LFDPX: return "LFDPX";
		case PPC_MNEM_LFDU: return "LFDU";
		case PPC_MNEM_LFDUX: return "LFDUX";
		case PPC_MNEM_LFDX: return "LFDX";
		case PPC_MNEM_LFIWAX: return "LFIWAX";
		case PPC_MNEM_LFIWZX: return "LFIWZX";
		case PPC_MNEM_LFQUX: return "LFQUX";
		case PPC_MNEM_LFQX: return "LFQX";
		case PPC_MNEM_LFS: return "LFS";
		case PPC_MNEM_LFSU: return "LFSU";
		case PPC_MNEM_LFSUX: return "LFSUX";
		case PPC_MNEM_LFSX: return "LFSX";
		case PPC_MNEM_LHA: return "LHA";
		case PPC_MNEM_LHARX: return "LHARX";
		case PPC_MNEM_LHAU: return "LHAU";
		case PPC_MNEM_LHAUX: return "LHAUX";
		case PPC_MNEM_LHAX: return "LHAX";
		case PPC_MNEM_LHBRX: return "LHBRX";
		case PPC_MNEM_LHDCBX: return "LHDCBX";
		case PPC_MNEM_LHDX: return "LHDX";
		case PPC_MNEM_LHEPX: return "LHEPX";
		case PPC_MNEM_LHZ: return "LHZ";
		case PPC_MNEM_LHZCIX: return "LHZCIX";
		case PPC_MNEM_LHZU: return "LHZU";
		case PPC_MNEM_LHZUX: return "LHZUX";
		case PPC_MNEM_LHZX: return "LHZX";
		case PPC_MNEM_LI: return "LI";
		case PPC_MNEM_LIS: return "LIS";
		case PPC_MNEM_LM: return "LM";
		case PPC_MNEM_LMW: return "LMW";
		case PPC_MNEM_LNIA: return "LNIA";
		case PPC_MNEM_LQ: return "LQ";
		case PPC_MNEM_LQARX: return "LQARX";
		case PPC_MNEM_LQFCMUX: return "LQFCMUX";
		case PPC_MNEM_LSCBX: return "LSCBX";
		case PPC_MNEM_LSI: return "LSI";
		case PPC_MNEM_LSWI: return "LSWI";
		case PPC_MNEM_LSWX: return "LSWX";
		case PPC_MNEM_LSX: return "LSX";
		case PPC_MNEM_LU: return "LU";
		case PPC_MNEM_LUX: return "LUX";
		case PPC_MNEM_LVEBX: return "LVEBX";
		case PPC_MNEM_LVEHX: return "LVEHX";
		case PPC_MNEM_LVEPX: return "LVEPX";
		case PPC_MNEM_LVEPXL: return "LVEPXL";
		case PPC_MNEM_LVEWX: return "LVEWX";
		case PPC_MNEM_LVEXBX: return "LVEXBX";
		case PPC_MNEM_LVEXHX: return "LVEXHX";
		case PPC_MNEM_LVEXWX: return "LVEXWX";
		case PPC_MNEM_LVLX: return "LVLX";
		case PPC_MNEM_LVRX: return "LVRX";
		case PPC_MNEM_LVSL: return "LVSL";
		case PPC_MNEM_LVSM: return "LVSM";
		case PPC_MNEM_LVSR: return "LVSR";
		case PPC_MNEM_LVSWX: return "LVSWX";
		case PPC_MNEM_LVSWXL: return "LVSWXL";
		case PPC_MNEM_LVTLX: return "LVTLX";
		case PPC_MNEM_LVTLXL: return "LVTLXL";
		case PPC_MNEM_LVTRX: return "LVTRX";
		case PPC_MNEM_LVTRXL: return "LVTRXL";
		case PPC_MNEM_LVX: return "LVX";
		case PPC_MNEM_LVXL: return "LVXL";
		case PPC_MNEM_LWA: return "LWA";
		case PPC_MNEM_LWARX: return "LWARX";
		case PPC_MNEM_LWAT: return "LWAT";
		case PPC_MNEM_LWAUX: return "LWAUX";
		case PPC_MNEM_LWAX: return "LWAX";
		case PPC_MNEM_LWBRX: return "LWBRX";
		case PPC_MNEM_LWDCBX: return "LWDCBX";
		case PPC_MNEM_LWDX: return "LWDX";
		case PPC_MNEM_LWEPX: return "LWEPX";
		case PPC_MNEM_LWFCMUX: return "LWFCMUX";
		case PPC_MNEM_LWSYNC: return "LWSYNC";
		case PPC_MNEM_LWZ: return "LWZ";
		case PPC_MNEM_LWZCIX: return "LWZCIX";
		case PPC_MNEM_LWZU: return "LWZU";
		case PPC_MNEM_LWZUX: return "LWZUX";
		case PPC_MNEM_LWZX: return "LWZX";
		case PPC_MNEM_LXSD: return "LXSD";
		case PPC_MNEM_LXSDX: return "LXSDX";
		case PPC_MNEM_LXSIBZX: return "LXSIBZX";
		case PPC_MNEM_LXSIHZX: return "LXSIHZX";
		case PPC_MNEM_LXSIWAX: return "LXSIWAX";
		case PPC_MNEM_LXSIWZX: return "LXSIWZX";
		case PPC_MNEM_LXSSP: return "LXSSP";
		case PPC_MNEM_LXSSPX: return "LXSSPX";
		case PPC_MNEM_LXV: return "LXV";
		case PPC_MNEM_LXVB16X: return "LXVB16X";
		case PPC_MNEM_LXVD2X: return "LXVD2X";
		case PPC_MNEM_LXVDSX: return "LXVDSX";
		case PPC_MNEM_LXVH8X: return "LXVH8X";
		case PPC_MNEM_LXVL: return "LXVL";
		case PPC_MNEM_LXVLL: return "LXVLL";
		case PPC_MNEM_LXVW4X: return "LXVW4X";
		case PPC_MNEM_LXVWSX: return "LXVWSX";
		case PPC_MNEM_LXVX: return "LXVX";
		case PPC_MNEM_MACCHW: return "MACCHW";
		case PPC_MNEM_MACCHWO: return "MACCHWO";
		case PPC_MNEM_MACCHWS: return "MACCHWS";
		case PPC_MNEM_MACCHWSO: return "MACCHWSO";
		case PPC_MNEM_MACCHWSU: return "MACCHWSU";
		case PPC_MNEM_MACCHWSUO: return "MACCHWSUO";
		case PPC_MNEM_MACCHWU: return "MACCHWU";
		case PPC_MNEM_MACCHWUO: return "MACCHWUO";
		case PPC_MNEM_MACHHW: return "MACHHW";
		case PPC_MNEM_MACHHWO: return "MACHHWO";
		case PPC_MNEM_MACHHWS: return "MACHHWS";
		case PPC_MNEM_MACHHWSO: return "MACHHWSO";
		case PPC_MNEM_MACHHWSU: return "MACHHWSU";
		case PPC_MNEM_MACHHWSUO: return "MACHHWSUO";
		case PPC_MNEM_MACHHWU: return "MACHHWU";
		case PPC_MNEM_MACHHWUO: return "MACHHWUO";
		case PPC_MNEM_MACLHW: return "MACLHW";
		case PPC_MNEM_MACLHWO: return "MACLHWO";
		case PPC_MNEM_MACLHWS: return "MACLHWS";
		case PPC_MNEM_MACLHWSO: return "MACLHWSO";
		case PPC_MNEM_MACLHWSU: return "MACLHWSU";
		case PPC_MNEM_MACLHWSUO: return "MACLHWSUO";
		case PPC_MNEM_MACLHWU: return "MACLHWU";
		case PPC_MNEM_MACLHWUO: return "MACLHWUO";
		case PPC_MNEM_MADDHD: return "MADDHD";
		case PPC_MNEM_MADDHDU: return "MADDHDU";
		case PPC_MNEM_MADDLD: return "MADDLD";
		case PPC_MNEM_MASKG: return "MASKG";
		case PPC_MNEM_MASKIR: return "MASKIR";
		case PPC_MNEM_MBAR: return "MBAR";
		case PPC_MNEM_MCRF: return "MCRF";
		case PPC_MNEM_MCRFS: return "MCRFS";
		case PPC_MNEM_MCRXR: return "MCRXR";
		case PPC_MNEM_MCRXRX: return "MCRXRX";
		case PPC_MNEM_MDOIO: return "MDOIO";
		case PPC_MNEM_MDOOM: return "MDOOM";
		case PPC_MNEM_MFAPIDI: return "MFAPIDI";
		case PPC_MNEM_MFASR: return "MFASR";
		case PPC_MNEM_MFBEAR: return "MFBEAR";
		case PPC_MNEM_MFBESR: return "MFBESR";
		case PPC_MNEM_MFBHRBE: return "MFBHRBE";
		case PPC_MNEM_MFBR0: return "MFBR0";
		case PPC_MNEM_MFBR1: return "MFBR1";
		case PPC_MNEM_MFBR2: return "MFBR2";
		case PPC_MNEM_MFBR3: return "MFBR3";
		case PPC_MNEM_MFBR4: return "MFBR4";
		case PPC_MNEM_MFBR5: return "MFBR5";
		case PPC_MNEM_MFBR6: return "MFBR6";
		case PPC_MNEM_MFBR7: return "MFBR7";
		case PPC_MNEM_MFCFAR: return "MFCFAR";
		case PPC_MNEM_MFCR: return "MFCR";
		case PPC_MNEM_MFCTR: return "MFCTR";
		case PPC_MNEM_MFCTRL: return "MFCTRL";
		case PPC_MNEM_MFDAR: return "MFDAR";
		case PPC_MNEM_MFDBATL: return "MFDBATL";
		case PPC_MNEM_MFDBATU: return "MFDBATU";
		case PPC_MNEM_MFDCR: return "MFDCR";
		case PPC_MNEM_MFDCRUX: return "MFDCRUX";
		case PPC_MNEM_MFDCRX: return "MFDCRX";
		case PPC_MNEM_MFDEC: return "MFDEC";
		case PPC_MNEM_MFDMACC0: return "MFDMACC0";
		case PPC_MNEM_MFDMACC1: return "MFDMACC1";
		case PPC_MNEM_MFDMACC2: return "MFDMACC2";
		case PPC_MNEM_MFDMACC3: return "MFDMACC3";
		case PPC_MNEM_MFDMACR0: return "MFDMACR0";
		case PPC_MNEM_MFDMACR1: return "MFDMACR1";
		case PPC_MNEM_MFDMACR2: return "MFDMACR2";
		case PPC_MNEM_MFDMACR3: return "MFDMACR3";
		case PPC_MNEM_MFDMACT0: return "MFDMACT0";
		case PPC_MNEM_MFDMACT1: return "MFDMACT1";
		case PPC_MNEM_MFDMACT2: return "MFDMACT2";
		case PPC_MNEM_MFDMACT3: return "MFDMACT3";
		case PPC_MNEM_MFDMADA0: return "MFDMADA0";
		case PPC_MNEM_MFDMADA1: return "MFDMADA1";
		case PPC_MNEM_MFDMADA2: return "MFDMADA2";
		case PPC_MNEM_MFDMADA3: return "MFDMADA3";
		case PPC_MNEM_MFDMASA0: return "MFDMASA0";
		case PPC_MNEM_MFDMASA1: return "MFDMASA1";
		case PPC_MNEM_MFDMASA2: return "MFDMASA2";
		case PPC_MNEM_MFDMASA3: return "MFDMASA3";
		case PPC_MNEM_MFDMASR: return "MFDMASR";
		case PPC_MNEM_MFDSCR: return "MFDSCR";
		case PPC_MNEM_MFDSISR: return "MFDSISR";
		case PPC_MNEM_MFEAR: return "MFEAR";
		case PPC_MNEM_MFEXIER: return "MFEXIER";
		case PPC_MNEM_MFEXISR: return "MFEXISR";
		case PPC_MNEM_MFFGPR: return "MFFGPR";
		case PPC_MNEM_MFFPRWZ: return "MFFPRWZ";
		case PPC_MNEM_MFFS: return "MFFS";
		case PPC_MNEM_MFFSCDRN: return "MFFSCDRN";
		case PPC_MNEM_MFFSCDRNI: return "MFFSCDRNI";
		case PPC_MNEM_MFFSCE: return "MFFSCE";
		case PPC_MNEM_MFFSCRN: return "MFFSCRN";
		case PPC_MNEM_MFFSCRNI: return "MFFSCRNI";
		case PPC_MNEM_MFFSL: return "MFFSL";
		case PPC_MNEM_MFIBATL: return "MFIBATL";
		case PPC_MNEM_MFIBATU: return "MFIBATU";
		case PPC_MNEM_MFIOCR: return "MFIOCR";
		case PPC_MNEM_MFLR: return "MFLR";
		case PPC_MNEM_MFMSR: return "MFMSR";
		case PPC_MNEM_MFOCRF: return "MFOCRF";
		case PPC_MNEM_MFPMR: return "MFPMR";
		case PPC_MNEM_MFPPR: return "MFPPR";
		case PPC_MNEM_MFPPR32: return "MFPPR32";
		case PPC_MNEM_MFPVR: return "MFPVR";
		case PPC_MNEM_MFRTCL: return "MFRTCL";
		case PPC_MNEM_MFRTCU: return "MFRTCU";
		case PPC_MNEM_MFSDR1: return "MFSDR1";
		case PPC_MNEM_MFSPR: return "MFSPR";
		case PPC_MNEM_MFSPRG: return "MFSPRG";
		case PPC_MNEM_MFSR: return "MFSR";
		case PPC_MNEM_MFSRI: return "MFSRI";
		case PPC_MNEM_MFSRIN: return "MFSRIN";
		case PPC_MNEM_MFSRR0: return "MFSRR0";
		case PPC_MNEM_MFSRR1: return "MFSRR1";
		case PPC_MNEM_MFTB: return "MFTB";
		case PPC_MNEM_MFTBU: return "MFTBU";
		case PPC_MNEM_MFTGPR: return "MFTGPR";
		case PPC_MNEM_MFTMR: return "MFTMR";
		case PPC_MNEM_MFVRSAVE: return "MFVRSAVE";
		case PPC_MNEM_MFVRWZ: return "MFVRWZ";
		case PPC_MNEM_MFVSCR: return "MFVSCR";
		case PPC_MNEM_MFVSRD: return "MFVSRD";
		case PPC_MNEM_MFVSRLD: return "MFVSRLD";
		case PPC_MNEM_MFXER: return "MFXER";
		case PPC_MNEM_MODSD: return "MODSD";
		case PPC_MNEM_MODSW: return "MODSW";
		case PPC_MNEM_MODUD: return "MODUD";
		case PPC_MNEM_MODUW: return "MODUW";
		case PPC_MNEM_MR: return "MR";
		case PPC_MNEM_MSGCLR: return "MSGCLR";
		case PPC_MNEM_MSGCLRP: return "MSGCLRP";
		case PPC_MNEM_MSGSND: return "MSGSND";
		case PPC_MNEM_MSGSNDP: return "MSGSNDP";
		case PPC_MNEM_MSGSYNC: return "MSGSYNC";
		case PPC_MNEM_MTASR: return "MTASR";
		case PPC_MNEM_MTBEAR: return "MTBEAR";
		case PPC_MNEM_MTBESR: return "MTBESR";
		case PPC_MNEM_MTBR0: return "MTBR0";
		case PPC_MNEM_MTBR1: return "MTBR1";
		case PPC_MNEM_MTBR2: return "MTBR2";
		case PPC_MNEM_MTBR3: return "MTBR3";
		case PPC_MNEM_MTBR4: return "MTBR4";
		case PPC_MNEM_MTBR5: return "MTBR5";
		case PPC_MNEM_MTBR6: return "MTBR6";
		case PPC_MNEM_MTBR7: return "MTBR7";
		case PPC_MNEM_MTCFAR: return "MTCFAR";
		case PPC_MNEM_MTCR: return "MTCR";
		case PPC_MNEM_MTCRF: return "MTCRF";
		case PPC_MNEM_MTCTR: return "MTCTR";
		case PPC_MNEM_MTCTRL: return "MTCTRL";
		case PPC_MNEM_MTDAR: return "MTDAR";
		case PPC_MNEM_MTDBATL: return "MTDBATL";
		case PPC_MNEM_MTDBATU: return "MTDBATU";
		case PPC_MNEM_MTDCR: return "MTDCR";
		case PPC_MNEM_MTDCRUX: return "MTDCRUX";
		case PPC_MNEM_MTDCRX: return "MTDCRX";
		case PPC_MNEM_MTDEC: return "MTDEC";
		case PPC_MNEM_MTDMACC0: return "MTDMACC0";
		case PPC_MNEM_MTDMACC1: return "MTDMACC1";
		case PPC_MNEM_MTDMACC2: return "MTDMACC2";
		case PPC_MNEM_MTDMACC3: return "MTDMACC3";
		case PPC_MNEM_MTDMACR0: return "MTDMACR0";
		case PPC_MNEM_MTDMACR1: return "MTDMACR1";
		case PPC_MNEM_MTDMACR2: return "MTDMACR2";
		case PPC_MNEM_MTDMACR3: return "MTDMACR3";
		case PPC_MNEM_MTDMACT0: return "MTDMACT0";
		case PPC_MNEM_MTDMACT1: return "MTDMACT1";
		case PPC_MNEM_MTDMACT2: return "MTDMACT2";
		case PPC_MNEM_MTDMACT3: return "MTDMACT3";
		case PPC_MNEM_MTDMADA0: return "MTDMADA0";
		case PPC_MNEM_MTDMADA1: return "MTDMADA1";
		case PPC_MNEM_MTDMADA2: return "MTDMADA2";
		case PPC_MNEM_MTDMADA3: return "MTDMADA3";
		case PPC_MNEM_MTDMASA0: return "MTDMASA0";
		case PPC_MNEM_MTDMASA1: return "MTDMASA1";
		case PPC_MNEM_MTDMASA2: return "MTDMASA2";
		case PPC_MNEM_MTDMASA3: return "MTDMASA3";
		case PPC_MNEM_MTDMASR: return "MTDMASR";
		case PPC_MNEM_MTDSCR: return "MTDSCR";
		case PPC_MNEM_MTDSISR: return "MTDSISR";
		case PPC_MNEM_MTEAR: return "MTEAR";
		case PPC_MNEM_MTEXIER: return "MTEXIER";
		case PPC_MNEM_MTEXISR: return "MTEXISR";
		case PPC_MNEM_MTFPRWA: return "MTFPRWA";
		case PPC_MNEM_MTFPRWZ: return "MTFPRWZ";
		case PPC_MNEM_MTFSB0: return "MTFSB0";
		case PPC_MNEM_MTFSB1: return "MTFSB1";
		case PPC_MNEM_MTFSF: return "MTFSF";
		case PPC_MNEM_MTFSFI: return "MTFSFI";
		case PPC_MNEM_MTIBATL: return "MTIBATL";
		case PPC_MNEM_MTIBATU: return "MTIBATU";
		case PPC_MNEM_MTIOCR: return "MTIOCR";
		case PPC_MNEM_MTLR: return "MTLR";
		case PPC_MNEM_MTMSR: return "MTMSR";
		case PPC_MNEM_MTMSRD: return "MTMSRD";
		case PPC_MNEM_MTOCRF: return "MTOCRF";
		case PPC_MNEM_MTPMR: return "MTPMR";
		case PPC_MNEM_MTPPR: return "MTPPR";
		case PPC_MNEM_MTPPR32: return "MTPPR32";
		case PPC_MNEM_MTRTCL: return "MTRTCL";
		case PPC_MNEM_MTRTCU: return "MTRTCU";
		case PPC_MNEM_MTSDR1: return "MTSDR1";
		case PPC_MNEM_MTSLE: return "MTSLE";
		case PPC_MNEM_MTSPR: return "MTSPR";
		case PPC_MNEM_MTSPRG: return "MTSPRG";
		case PPC_MNEM_MTSR: return "MTSR";
		case PPC_MNEM_MTSRD: return "MTSRD";
		case PPC_MNEM_MTSRDIN: return "MTSRDIN";
		case PPC_MNEM_MTSRIN: return "MTSRIN";
		case PPC_MNEM_MTSRR0: return "MTSRR0";
		case PPC_MNEM_MTSRR1: return "MTSRR1";
		case PPC_MNEM_MTTBL: return "MTTBL";
		case PPC_MNEM_MTTBU: return "MTTBU";
		case PPC_MNEM_MTTMR: return "MTTMR";
		case PPC_MNEM_MTVRSAVE: return "MTVRSAVE";
		case PPC_MNEM_MTVRWA: return "MTVRWA";
		case PPC_MNEM_MTVRWZ: return "MTVRWZ";
		case PPC_MNEM_MTVSCR: return "MTVSCR";
		case PPC_MNEM_MTVSRD: return "MTVSRD";
		case PPC_MNEM_MTVSRDD: return "MTVSRDD";
		case PPC_MNEM_MTVSRWS: return "MTVSRWS";
		case PPC_MNEM_MTXER: return "MTXER";
		case PPC_MNEM_MUL: return "MUL";
		case PPC_MNEM_MULCHW: return "MULCHW";
		case PPC_MNEM_MULCHWU: return "MULCHWU";
		case PPC_MNEM_MULHD: return "MULHD";
		case PPC_MNEM_MULHDU: return "MULHDU";
		case PPC_MNEM_MULHHW: return "MULHHW";
		case PPC_MNEM_MULHHWU: return "MULHHWU";
		case PPC_MNEM_MULHW: return "MULHW";
		case PPC_MNEM_MULHWU: return "MULHWU";
		case PPC_MNEM_MULLD: return "MULLD";
		case PPC_MNEM_MULLDO: return "MULLDO";
		case PPC_MNEM_MULLHW: return "MULLHW";
		case PPC_MNEM_MULLHWU: return "MULLHWU";
		case PPC_MNEM_MULLI: return "MULLI";
		case PPC_MNEM_MULLW: return "MULLW";
		case PPC_MNEM_MULLWO: return "MULLWO";
		case PPC_MNEM_MULO: return "MULO";
		case PPC_MNEM_MVIDSPLT: return "MVIDSPLT";
		case PPC_MNEM_MVIWSPLT: return "MVIWSPLT";
		case PPC_MNEM_NABS: return "NABS";
		case PPC_MNEM_NABSO: return "NABSO";
		case PPC_MNEM_NAND: return "NAND";
		case PPC_MNEM_NAP: return "NAP";
		case PPC_MNEM_NEG: return "NEG";
		case PPC_MNEM_NEGO: return "NEGO";
		case PPC_MNEM_NOP: return "NOP";
		case PPC_MNEM_NOR: return "NOR";
		case PPC_MNEM_NOT: return "NOT";
		case PPC_MNEM_OR: return "OR";
		case PPC_MNEM_ORC: return "ORC";
		case PPC_MNEM_ORI: return "ORI";
		case PPC_MNEM_ORIS: return "ORIS";
		case PPC_MNEM_PASTE: return "PASTE";
		case PPC_MNEM_PBT: return "PBT";
		case PPC_MNEM_POPCNTB: return "POPCNTB";
		case PPC_MNEM_POPCNTD: return "POPCNTD";
		case PPC_MNEM_POPCNTW: return "POPCNTW";
		case PPC_MNEM_PRTYD: return "PRTYD";
		case PPC_MNEM_PRTYW: return "PRTYW";
		case PPC_MNEM_PSQ_L: return "PSQ_L";
		case PPC_MNEM_PSQ_LU: return "PSQ_LU";
		case PPC_MNEM_PSQ_LUX: return "PSQ_LUX";
		case PPC_MNEM_PSQ_LX: return "PSQ_LX";
		case PPC_MNEM_PSQ_ST: return "PSQ_ST";
		case PPC_MNEM_PSQ_STU: return "PSQ_STU";
		case PPC_MNEM_PSQ_STUX: return "PSQ_STUX";
		case PPC_MNEM_PSQ_STX: return "PSQ_STX";
		case PPC_MNEM_PS_ABS: return "PS_ABS";
		case PPC_MNEM_PS_MADD: return "PS_MADD";
		case PPC_MNEM_PS_MADDS0: return "PS_MADDS0";
		case PPC_MNEM_PS_MADDS1: return "PS_MADDS1";
		case PPC_MNEM_PS_MR: return "PS_MR";
		case PPC_MNEM_PS_MSUB: return "PS_MSUB";
		case PPC_MNEM_PS_MUL: return "PS_MUL";
		case PPC_MNEM_PS_MULS0: return "PS_MULS0";
		case PPC_MNEM_PS_MULS1: return "PS_MULS1";
		case PPC_MNEM_PS_NABS: return "PS_NABS";
		case PPC_MNEM_PS_NEG: return "PS_NEG";
		case PPC_MNEM_PS_RSQRTE: return "PS_RSQRTE";
		case PPC_MNEM_PS_SUM0: return "PS_SUM0";
		case PPC_MNEM_PS_SUM1: return "PS_SUM1";
		case PPC_MNEM_PTESYNC: return "PTESYNC";
		case PPC_MNEM_RAC: return "RAC";
		case PPC_MNEM_RFCI: return "RFCI";
		case PPC_MNEM_RFDI: return "RFDI";
		case PPC_MNEM_RFEBB: return "RFEBB";
		case PPC_MNEM_RFGI: return "RFGI";
		case PPC_MNEM_RFI: return "RFI";
		case PPC_MNEM_RFID: return "RFID";
		case PPC_MNEM_RFMCI: return "RFMCI";
		case PPC_MNEM_RFSCV: return "RFSCV";
		case PPC_MNEM_RLDCL: return "RLDCL";
		case PPC_MNEM_RLDCR: return "RLDCR";
		case PPC_MNEM_RLDIC: return "RLDIC";
		case PPC_MNEM_RLDICL: return "RLDICL";
		case PPC_MNEM_RLDICR: return "RLDICR";
		case PPC_MNEM_RLDIMI: return "RLDIMI";
		case PPC_MNEM_RLMI: return "RLMI";
		case PPC_MNEM_RLWIMI: return "RLWIMI";
		case PPC_MNEM_RLWINM: return "RLWINM";
		case PPC_MNEM_RLWNM: return "RLWNM";
		case PPC_MNEM_RMIEG: return "RMIEG";
		case PPC_MNEM_ROTLD: return "ROTLD";
		case PPC_MNEM_ROTLDI: return "ROTLDI";
		case PPC_MNEM_ROTLW: return "ROTLW";
		case PPC_MNEM_ROTLWI: return "ROTLWI";
		case PPC_MNEM_RRIB: return "RRIB";
		case PPC_MNEM_RVWINKLE: return "RVWINKLE";
		case PPC_MNEM_SC: return "SC";
		case PPC_MNEM_SCV: return "SCV";
		case PPC_MNEM_SETB: return "SETB";
		case PPC_MNEM_SLBFEE: return "SLBFEE";
		case PPC_MNEM_SLBIA: return "SLBIA";
		case PPC_MNEM_SLBIAG: return "SLBIAG";
		case PPC_MNEM_SLBIE: return "SLBIE";
		case PPC_MNEM_SLBIEG: return "SLBIEG";
		case PPC_MNEM_SLBMFEE: return "SLBMFEE";
		case PPC_MNEM_SLBMFEV: return "SLBMFEV";
		case PPC_MNEM_SLBMTE: return "SLBMTE";
		case PPC_MNEM_SLBSYNC: return "SLBSYNC";
		case PPC_MNEM_SLD: return "SLD";
		case PPC_MNEM_SLE: return "SLE";
		case PPC_MNEM_SLEEP: return "SLEEP";
		case PPC_MNEM_SLEQ: return "SLEQ";
		case PPC_MNEM_SLIQ: return "SLIQ";
		case PPC_MNEM_SLLIQ: return "SLLIQ";
		case PPC_MNEM_SLLQ: return "SLLQ";
		case PPC_MNEM_SLQ: return "SLQ";
		case PPC_MNEM_SLW: return "SLW";
		case PPC_MNEM_SRAD: return "SRAD";
		case PPC_MNEM_SRADI: return "SRADI";
		case PPC_MNEM_SRAIQ: return "SRAIQ";
		case PPC_MNEM_SRAQ: return "SRAQ";
		case PPC_MNEM_SRAW: return "SRAW";
		case PPC_MNEM_SRAWI: return "SRAWI";
		case PPC_MNEM_SRD: return "SRD";
		case PPC_MNEM_SRE: return "SRE";
		case PPC_MNEM_SREA: return "SREA";
		case PPC_MNEM_SREQ: return "SREQ";
		case PPC_MNEM_SRIQ: return "SRIQ";
		case PPC_MNEM_SRLIQ: return "SRLIQ";
		case PPC_MNEM_SRLQ: return "SRLQ";
		case PPC_MNEM_SRQ: return "SRQ";
		case PPC_MNEM_SRW: return "SRW";
		case PPC_MNEM_STB: return "STB";
		case PPC_MNEM_STBCIX: return "STBCIX";
		case PPC_MNEM_STBCX: return "STBCX";
		case PPC_MNEM_STBDCBX: return "STBDCBX";
		case PPC_MNEM_STBDX: return "STBDX";
		case PPC_MNEM_STBEPX: return "STBEPX";
		case PPC_MNEM_STBU: return "STBU";
		case PPC_MNEM_STBUX: return "STBUX";
		case PPC_MNEM_STBX: return "STBX";
		case PPC_MNEM_STD: return "STD";
		case PPC_MNEM_STDAT: return "STDAT";
		case PPC_MNEM_STDBRX: return "STDBRX";
		case PPC_MNEM_STDCIX: return "STDCIX";
		case PPC_MNEM_STDCX: return "STDCX";
		case PPC_MNEM_STDDX: return "STDDX";
		case PPC_MNEM_STDEPX: return "STDEPX";
		case PPC_MNEM_STDFCMX: return "STDFCMX";
		case PPC_MNEM_STDU: return "STDU";
		case PPC_MNEM_STDUX: return "STDUX";
		case PPC_MNEM_STDX: return "STDX";
		case PPC_MNEM_STFD: return "STFD";
		case PPC_MNEM_STFDDX: return "STFDDX";
		case PPC_MNEM_STFDEPX: return "STFDEPX";
		case PPC_MNEM_STFDP: return "STFDP";
		case PPC_MNEM_STFDPX: return "STFDPX";
		case PPC_MNEM_STFDU: return "STFDU";
		case PPC_MNEM_STFDUX: return "STFDUX";
		case PPC_MNEM_STFDX: return "STFDX";
		case PPC_MNEM_STFIWX: return "STFIWX";
		case PPC_MNEM_STFQUX: return "STFQUX";
		case PPC_MNEM_STFQX: return "STFQX";
		case PPC_MNEM_STFS: return "STFS";
		case PPC_MNEM_STFSU: return "STFSU";
		case PPC_MNEM_STFSUX: return "STFSUX";
		case PPC_MNEM_STFSX: return "STFSX";
		case PPC_MNEM_STH: return "STH";
		case PPC_MNEM_STHBRX: return "STHBRX";
		case PPC_MNEM_STHCIX: return "STHCIX";
		case PPC_MNEM_STHCX: return "STHCX";
		case PPC_MNEM_STHDCBX: return "STHDCBX";
		case PPC_MNEM_STHDX: return "STHDX";
		case PPC_MNEM_STHEPX: return "STHEPX";
		case PPC_MNEM_STHU: return "STHU";
		case PPC_MNEM_STHUX: return "STHUX";
		case PPC_MNEM_STHX: return "STHX";
		case PPC_MNEM_STMW: return "STMW";
		case PPC_MNEM_STOP: return "STOP";
		case PPC_MNEM_STQ: return "STQ";
		case PPC_MNEM_STQCX: return "STQCX";
		case PPC_MNEM_STQFCMUX: return "STQFCMUX";
		case PPC_MNEM_STSWI: return "STSWI";
		case PPC_MNEM_STSWX: return "STSWX";
		case PPC_MNEM_STU: return "STU";
		case PPC_MNEM_STUX: return "STUX";
		case PPC_MNEM_STVEBX: return "STVEBX";
		case PPC_MNEM_STVEHX: return "STVEHX";
		case PPC_MNEM_STVEPX: return "STVEPX";
		case PPC_MNEM_STVEPXL: return "STVEPXL";
		case PPC_MNEM_STVEWX: return "STVEWX";
		case PPC_MNEM_STVEXBX: return "STVEXBX";
		case PPC_MNEM_STVEXHX: return "STVEXHX";
		case PPC_MNEM_STVEXWX: return "STVEXWX";
		case PPC_MNEM_STVFLX: return "STVFLX";
		case PPC_MNEM_STVFLXL: return "STVFLXL";
		case PPC_MNEM_STVFRX: return "STVFRX";
		case PPC_MNEM_STVFRXL: return "STVFRXL";
		case PPC_MNEM_STVLX: return "STVLX";
		case PPC_MNEM_STVLXL: return "STVLXL";
		case PPC_MNEM_STVRX: return "STVRX";
		case PPC_MNEM_STVRXL: return "STVRXL";
		case PPC_MNEM_STVSWX: return "STVSWX";
		case PPC_MNEM_STVSWXL: return "STVSWXL";
		case PPC_MNEM_STVX: return "STVX";
		case PPC_MNEM_STVXL: return "STVXL";
		case PPC_MNEM_STW: return "STW";
		case PPC_MNEM_STWAT: return "STWAT";
		case PPC_MNEM_STWBRX: return "STWBRX";
		case PPC_MNEM_STWCIX: return "STWCIX";
		case PPC_MNEM_STWCX: return "STWCX";
		case PPC_MNEM_STWDCBX: return "STWDCBX";
		case PPC_MNEM_STWDX: return "STWDX";
		case PPC_MNEM_STWEPX: return "STWEPX";
		case PPC_MNEM_STWFCMUX: return "STWFCMUX";
		case PPC_MNEM_STWU: return "STWU";
		case PPC_MNEM_STWUX: return "STWUX";
		case PPC_MNEM_STWX: return "STWX";
		case PPC_MNEM_STXSD: return "STXSD";
		case PPC_MNEM_STXSDX: return "STXSDX";
		case PPC_MNEM_STXSIBX: return "STXSIBX";
		case PPC_MNEM_STXSIHX: return "STXSIHX";
		case PPC_MNEM_STXSIWX: return "STXSIWX";
		case PPC_MNEM_STXSSP: return "STXSSP";
		case PPC_MNEM_STXSSPX: return "STXSSPX";
		case PPC_MNEM_STXV: return "STXV";
		case PPC_MNEM_STXVB16X: return "STXVB16X";
		case PPC_MNEM_STXVD2X: return "STXVD2X";
		case PPC_MNEM_STXVH8X: return "STXVH8X";
		case PPC_MNEM_STXVL: return "STXVL";
		case PPC_MNEM_STXVLL: return "STXVLL";
		case PPC_MNEM_STXVW4X: return "STXVW4X";
		case PPC_MNEM_STXVX: return "STXVX";
		case PPC_MNEM_SUBF: return "SUBF";
		case PPC_MNEM_SUBFC: return "SUBFC";
		case PPC_MNEM_SUBFCO: return "SUBFCO";
		case PPC_MNEM_SUBFE: return "SUBFE";
		case PPC_MNEM_SUBFEO: return "SUBFEO";
		case PPC_MNEM_SUBFIC: return "SUBFIC";
		case PPC_MNEM_SUBFME: return "SUBFME";
		case PPC_MNEM_SUBFMEO: return "SUBFMEO";
		case PPC_MNEM_SUBFO: return "SUBFO";
		case PPC_MNEM_SUBFZE: return "SUBFZE";
		case PPC_MNEM_SUBFZEO: return "SUBFZEO";
		case PPC_MNEM_SVC: return "SVC";
		case PPC_MNEM_SVCLA: return "SVCLA";
		case PPC_MNEM_SYNC: return "SYNC";
		case PPC_MNEM_TABORT: return "TABORT";
		case PPC_MNEM_TABORTDC: return "TABORTDC";
		case PPC_MNEM_TABORTDCI: return "TABORTDCI";
		case PPC_MNEM_TABORTWC: return "TABORTWC";
		case PPC_MNEM_TABORTWCI: return "TABORTWCI";
		case PPC_MNEM_TBEGIN: return "TBEGIN";
		case PPC_MNEM_TCHECK: return "TCHECK";
		case PPC_MNEM_TD: return "TD";
		case PPC_MNEM_TDEQ: return "TDEQ";
		case PPC_MNEM_TDEQI: return "TDEQI";
		case PPC_MNEM_TDGE: return "TDGE";
		case PPC_MNEM_TDGEI: return "TDGEI";
		case PPC_MNEM_TDGT: return "TDGT";
		case PPC_MNEM_TDGTI: return "TDGTI";
		case PPC_MNEM_TDI: return "TDI";
		case PPC_MNEM_TDLE: return "TDLE";
		case PPC_MNEM_TDLEI: return "TDLEI";
		case PPC_MNEM_TDLGE: return "TDLGE";
		case PPC_MNEM_TDLGEI: return "TDLGEI";
		case PPC_MNEM_TDLGT: return "TDLGT";
		case PPC_MNEM_TDLGTI: return "TDLGTI";
		case PPC_MNEM_TDLLE: return "TDLLE";
		case PPC_MNEM_TDLLEI: return "TDLLEI";
		case PPC_MNEM_TDLLT: return "TDLLT";
		case PPC_MNEM_TDLLTI: return "TDLLTI";
		case PPC_MNEM_TDLT: return "TDLT";
		case PPC_MNEM_TDLTI: return "TDLTI";
		case PPC_MNEM_TDNE: return "TDNE";
		case PPC_MNEM_TDNEI: return "TDNEI";
		case PPC_MNEM_TDU: return "TDU";
		case PPC_MNEM_TDUI: return "TDUI";
		case PPC_MNEM_TEND: return "TEND";
		case PPC_MNEM_TENDALL: return "TENDALL";
		case PPC_MNEM_TLBI: return "TLBI";
		case PPC_MNEM_TLBIA: return "TLBIA";
		case PPC_MNEM_TLBIE: return "TLBIE";
		case PPC_MNEM_TLBIEL: return "TLBIEL";
		case PPC_MNEM_TLBILX: return "TLBILX";
		case PPC_MNEM_TLBILXLPID: return "TLBILXLPID";
		case PPC_MNEM_TLBILXPID: return "TLBILXPID";
		case PPC_MNEM_TLBILXVA: return "TLBILXVA";
		case PPC_MNEM_TLBIVAX: return "TLBIVAX";
		case PPC_MNEM_TLBLD: return "TLBLD";
		case PPC_MNEM_TLBLI: return "TLBLI";
		case PPC_MNEM_TLBRE: return "TLBRE";
		case PPC_MNEM_TLBREHI: return "TLBREHI";
		case PPC_MNEM_TLBRELO: return "TLBRELO";
		case PPC_MNEM_TLBSRX: return "TLBSRX";
		case PPC_MNEM_TLBSX: return "TLBSX";
		case PPC_MNEM_TLBSYNC: return "TLBSYNC";
		case PPC_MNEM_TLBWE: return "TLBWE";
		case PPC_MNEM_TLBWEHI: return "TLBWEHI";
		case PPC_MNEM_TLBWELO: return "TLBWELO";
		case PPC_MNEM_TRAP: return "TRAP";
		case PPC_MNEM_TRECHKPT: return "TRECHKPT";
		case PPC_MNEM_TRECLAIM: return "TRECLAIM";
		case PPC_MNEM_TRESUME: return "TRESUME";
		case PPC_MNEM_TSUSPEND: return "TSUSPEND";
		case PPC_MNEM_TW: return "TW";
		case PPC_MNEM_TWEQ: return "TWEQ";
		case PPC_MNEM_TWEQI: return "TWEQI";
		case PPC_MNEM_TWGE: return "TWGE";
		case PPC_MNEM_TWGEI: return "TWGEI";
		case PPC_MNEM_TWGT: return "TWGT";
		case PPC_MNEM_TWGTI: return "TWGTI";
		case PPC_MNEM_TWI: return "TWI";
		case PPC_MNEM_TWLE: return "TWLE";
		case PPC_MNEM_TWLEI: return "TWLEI";
		case PPC_MNEM_TWLGE: return "TWLGE";
		case PPC_MNEM_TWLGEI: return "TWLGEI";
		case PPC_MNEM_TWLGT: return "TWLGT";
		case PPC_MNEM_TWLGTI: return "TWLGTI";
		case PPC_MNEM_TWLLE: return "TWLLE";
		case PPC_MNEM_TWLLEI: return "TWLLEI";
		case PPC_MNEM_TWLLT: return "TWLLT";
		case PPC_MNEM_TWLLTI: return "TWLLTI";
		case PPC_MNEM_TWLT: return "TWLT";
		case PPC_MNEM_TWLTI: return "TWLTI";
		case PPC_MNEM_TWNE: return "TWNE";
		case PPC_MNEM_TWNEI: return "TWNEI";
		case PPC_MNEM_TWU: return "TWU";
		case PPC_MNEM_TWUI: return "TWUI";
		case PPC_MNEM_UDI10FCM: return "UDI10FCM";
		case PPC_MNEM_UDI12FCM: return "UDI12FCM";
		case PPC_MNEM_UDI13FCM: return "UDI13FCM";
		case PPC_MNEM_UDI14FCM: return "UDI14FCM";
		case PPC_MNEM_UDI4FCM: return "UDI4FCM";
		case PPC_MNEM_UDI5FCM: return "UDI5FCM";
		case PPC_MNEM_UDI6FCM: return "UDI6FCM";
		case PPC_MNEM_UDI7FCM: return "UDI7FCM";
		case PPC_MNEM_UDI8FCM: return "UDI8FCM";
		case PPC_MNEM_UDI9FCM: return "UDI9FCM";
		case PPC_MNEM_URFID: return "URFID";
		case PPC_MNEM_VABSDUB: return "VABSDUB";
		case PPC_MNEM_VABSDUH: return "VABSDUH";
		case PPC_MNEM_VABSDUW: return "VABSDUW";
		case PPC_MNEM_VADDCUQ: return "VADDCUQ";
		case PPC_MNEM_VADDCUW: return "VADDCUW";
		case PPC_MNEM_VADDECUQ: return "VADDECUQ";
		case PPC_MNEM_VADDEUQM: return "VADDEUQM";
		case PPC_MNEM_VADDFP: return "VADDFP";
		case PPC_MNEM_VADDSBS: return "VADDSBS";
		case PPC_MNEM_VADDSHS: return "VADDSHS";
		case PPC_MNEM_VADDSWS: return "VADDSWS";
		case PPC_MNEM_VADDUBM: return "VADDUBM";
		case PPC_MNEM_VADDUBS: return "VADDUBS";
		case PPC_MNEM_VADDUDM: return "VADDUDM";
		case PPC_MNEM_VADDUHM: return "VADDUHM";
		case PPC_MNEM_VADDUHS: return "VADDUHS";
		case PPC_MNEM_VADDUQM: return "VADDUQM";
		case PPC_MNEM_VADDUWM: return "VADDUWM";
		case PPC_MNEM_VADDUWS: return "VADDUWS";
		case PPC_MNEM_VAND: return "VAND";
		case PPC_MNEM_VANDC: return "VANDC";
		case PPC_MNEM_VAVGSB: return "VAVGSB";
		case PPC_MNEM_VAVGSH: return "VAVGSH";
		case PPC_MNEM_VAVGSW: return "VAVGSW";
		case PPC_MNEM_VAVGUB: return "VAVGUB";
		case PPC_MNEM_VAVGUH: return "VAVGUH";
		case PPC_MNEM_VAVGUW: return "VAVGUW";
		case PPC_MNEM_VBPERMD: return "VBPERMD";
		case PPC_MNEM_VBPERMQ: return "VBPERMQ";
		case PPC_MNEM_VCFSX: return "VCFSX";
		case PPC_MNEM_VCFUX: return "VCFUX";
		case PPC_MNEM_VCIPHER: return "VCIPHER";
		case PPC_MNEM_VCIPHERLAST: return "VCIPHERLAST";
		case PPC_MNEM_VCLZB: return "VCLZB";
		case PPC_MNEM_VCLZD: return "VCLZD";
		case PPC_MNEM_VCLZH: return "VCLZH";
		case PPC_MNEM_VCLZLSBB: return "VCLZLSBB";
		case PPC_MNEM_VCLZW: return "VCLZW";
		case PPC_MNEM_VCMPBFP: return "VCMPBFP";
		case PPC_MNEM_VCMPEQFP: return "VCMPEQFP";
		case PPC_MNEM_VCMPEQUB: return "VCMPEQUB";
		case PPC_MNEM_VCMPEQUD: return "VCMPEQUD";
		case PPC_MNEM_VCMPEQUH: return "VCMPEQUH";
		case PPC_MNEM_VCMPEQUW: return "VCMPEQUW";
		case PPC_MNEM_VCMPGEFP: return "VCMPGEFP";
		case PPC_MNEM_VCMPGTFP: return "VCMPGTFP";
		case PPC_MNEM_VCMPGTSB: return "VCMPGTSB";
		case PPC_MNEM_VCMPGTSD: return "VCMPGTSD";
		case PPC_MNEM_VCMPGTSH: return "VCMPGTSH";
		case PPC_MNEM_VCMPGTSW: return "VCMPGTSW";
		case PPC_MNEM_VCMPGTUB: return "VCMPGTUB";
		case PPC_MNEM_VCMPGTUD: return "VCMPGTUD";
		case PPC_MNEM_VCMPGTUH: return "VCMPGTUH";
		case PPC_MNEM_VCMPGTUW: return "VCMPGTUW";
		case PPC_MNEM_VCMPNEB: return "VCMPNEB";
		case PPC_MNEM_VCMPNEH: return "VCMPNEH";
		case PPC_MNEM_VCMPNEW: return "VCMPNEW";
		case PPC_MNEM_VCMPNEZB: return "VCMPNEZB";
		case PPC_MNEM_VCMPNEZH: return "VCMPNEZH";
		case PPC_MNEM_VCMPNEZW: return "VCMPNEZW";
		case PPC_MNEM_VCTSXS: return "VCTSXS";
		case PPC_MNEM_VCTUXS: return "VCTUXS";
		case PPC_MNEM_VCTZB: return "VCTZB";
		case PPC_MNEM_VCTZD: return "VCTZD";
		case PPC_MNEM_VCTZH: return "VCTZH";
		case PPC_MNEM_VCTZLSBB: return "VCTZLSBB";
		case PPC_MNEM_VCTZW: return "VCTZW";
		case PPC_MNEM_VEQV: return "VEQV";
		case PPC_MNEM_VEXPTEFP: return "VEXPTEFP";
		case PPC_MNEM_VEXTRACTD: return "VEXTRACTD";
		case PPC_MNEM_VEXTRACTUB: return "VEXTRACTUB";
		case PPC_MNEM_VEXTRACTUH: return "VEXTRACTUH";
		case PPC_MNEM_VEXTRACTUW: return "VEXTRACTUW";
		case PPC_MNEM_VEXTSB2D: return "VEXTSB2D";
		case PPC_MNEM_VEXTSB2W: return "VEXTSB2W";
		case PPC_MNEM_VEXTSH2D: return "VEXTSH2D";
		case PPC_MNEM_VEXTSH2W: return "VEXTSH2W";
		case PPC_MNEM_VEXTSW2D: return "VEXTSW2D";
		case PPC_MNEM_VEXTUBLX: return "VEXTUBLX";
		case PPC_MNEM_VEXTUBRX: return "VEXTUBRX";
		case PPC_MNEM_VEXTUHLX: return "VEXTUHLX";
		case PPC_MNEM_VEXTUHRX: return "VEXTUHRX";
		case PPC_MNEM_VEXTUWLX: return "VEXTUWLX";
		case PPC_MNEM_VEXTUWRX: return "VEXTUWRX";
		case PPC_MNEM_VGBBD: return "VGBBD";
		case PPC_MNEM_VINSERTB: return "VINSERTB";
		case PPC_MNEM_VINSERTD: return "VINSERTD";
		case PPC_MNEM_VINSERTH: return "VINSERTH";
		case PPC_MNEM_VINSERTW: return "VINSERTW";
		case PPC_MNEM_VLOGEFP: return "VLOGEFP";
		case PPC_MNEM_VMADDFP: return "VMADDFP";
		case PPC_MNEM_VMAXFP: return "VMAXFP";
		case PPC_MNEM_VMAXSB: return "VMAXSB";
		case PPC_MNEM_VMAXSD: return "VMAXSD";
		case PPC_MNEM_VMAXSH: return "VMAXSH";
		case PPC_MNEM_VMAXSW: return "VMAXSW";
		case PPC_MNEM_VMAXUB: return "VMAXUB";
		case PPC_MNEM_VMAXUD: return "VMAXUD";
		case PPC_MNEM_VMAXUH: return "VMAXUH";
		case PPC_MNEM_VMAXUW: return "VMAXUW";
		case PPC_MNEM_VMHADDSHS: return "VMHADDSHS";
		case PPC_MNEM_VMHRADDSHS: return "VMHRADDSHS";
		case PPC_MNEM_VMINFP: return "VMINFP";
		case PPC_MNEM_VMINSB: return "VMINSB";
		case PPC_MNEM_VMINSD: return "VMINSD";
		case PPC_MNEM_VMINSH: return "VMINSH";
		case PPC_MNEM_VMINSW: return "VMINSW";
		case PPC_MNEM_VMINUB: return "VMINUB";
		case PPC_MNEM_VMINUD: return "VMINUD";
		case PPC_MNEM_VMINUH: return "VMINUH";
		case PPC_MNEM_VMINUW: return "VMINUW";
		case PPC_MNEM_VMLADDUHM: return "VMLADDUHM";
		case PPC_MNEM_VMR: return "VMR";
		case PPC_MNEM_VMRGEW: return "VMRGEW";
		case PPC_MNEM_VMRGHB: return "VMRGHB";
		case PPC_MNEM_VMRGHH: return "VMRGHH";
		case PPC_MNEM_VMRGHW: return "VMRGHW";
		case PPC_MNEM_VMRGLB: return "VMRGLB";
		case PPC_MNEM_VMRGLH: return "VMRGLH";
		case PPC_MNEM_VMRGLW: return "VMRGLW";
		case PPC_MNEM_VMRGOW: return "VMRGOW";
		case PPC_MNEM_VMSUMMBM: return "VMSUMMBM";
		case PPC_MNEM_VMSUMSHM: return "VMSUMSHM";
		case PPC_MNEM_VMSUMSHS: return "VMSUMSHS";
		case PPC_MNEM_VMSUMUBM: return "VMSUMUBM";
		case PPC_MNEM_VMSUMUDM: return "VMSUMUDM";
		case PPC_MNEM_VMSUMUHM: return "VMSUMUHM";
		case PPC_MNEM_VMSUMUHS: return "VMSUMUHS";
		case PPC_MNEM_VMUL10CUQ: return "VMUL10CUQ";
		case PPC_MNEM_VMUL10ECUQ: return "VMUL10ECUQ";
		case PPC_MNEM_VMUL10EUQ: return "VMUL10EUQ";
		case PPC_MNEM_VMUL10UQ: return "VMUL10UQ";
		case PPC_MNEM_VMULESB: return "VMULESB";
		case PPC_MNEM_VMULESH: return "VMULESH";
		case PPC_MNEM_VMULESW: return "VMULESW";
		case PPC_MNEM_VMULEUB: return "VMULEUB";
		case PPC_MNEM_VMULEUH: return "VMULEUH";
		case PPC_MNEM_VMULEUW: return "VMULEUW";
		case PPC_MNEM_VMULOSB: return "VMULOSB";
		case PPC_MNEM_VMULOSH: return "VMULOSH";
		case PPC_MNEM_VMULOSW: return "VMULOSW";
		case PPC_MNEM_VMULOUB: return "VMULOUB";
		case PPC_MNEM_VMULOUH: return "VMULOUH";
		case PPC_MNEM_VMULOUW: return "VMULOUW";
		case PPC_MNEM_VMULUWM: return "VMULUWM";
		case PPC_MNEM_VNAND: return "VNAND";
		case PPC_MNEM_VNCIPHER: return "VNCIPHER";
		case PPC_MNEM_VNCIPHERLAST: return "VNCIPHERLAST";
		case PPC_MNEM_VNEGD: return "VNEGD";
		case PPC_MNEM_VNEGW: return "VNEGW";
		case PPC_MNEM_VNMSUBFP: return "VNMSUBFP";
		case PPC_MNEM_VNOR: return "VNOR";
		case PPC_MNEM_VNOT: return "VNOT";
		case PPC_MNEM_VOR: return "VOR";
		case PPC_MNEM_VORC: return "VORC";
		case PPC_MNEM_VPERM: return "VPERM";
		case PPC_MNEM_VPERMR: return "VPERMR";
		case PPC_MNEM_VPERMXOR: return "VPERMXOR";
		case PPC_MNEM_VPKPX: return "VPKPX";
		case PPC_MNEM_VPKSDSS: return "VPKSDSS";
		case PPC_MNEM_VPKSDUS: return "VPKSDUS";
		case PPC_MNEM_VPKSHSS: return "VPKSHSS";
		case PPC_MNEM_VPKSHUS: return "VPKSHUS";
		case PPC_MNEM_VPKSWSS: return "VPKSWSS";
		case PPC_MNEM_VPKSWUS: return "VPKSWUS";
		case PPC_MNEM_VPKUDUM: return "VPKUDUM";
		case PPC_MNEM_VPKUDUS: return "VPKUDUS";
		case PPC_MNEM_VPKUHUM: return "VPKUHUM";
		case PPC_MNEM_VPKUHUS: return "VPKUHUS";
		case PPC_MNEM_VPKUWUM: return "VPKUWUM";
		case PPC_MNEM_VPKUWUS: return "VPKUWUS";
		case PPC_MNEM_VPMSUMB: return "VPMSUMB";
		case PPC_MNEM_VPMSUMD: return "VPMSUMD";
		case PPC_MNEM_VPMSUMH: return "VPMSUMH";
		case PPC_MNEM_VPMSUMW: return "VPMSUMW";
		case PPC_MNEM_VPOPCNTB: return "VPOPCNTB";
		case PPC_MNEM_VPOPCNTD: return "VPOPCNTD";
		case PPC_MNEM_VPOPCNTH: return "VPOPCNTH";
		case PPC_MNEM_VPOPCNTW: return "VPOPCNTW";
		case PPC_MNEM_VPRTYBD: return "VPRTYBD";
		case PPC_MNEM_VPRTYBQ: return "VPRTYBQ";
		case PPC_MNEM_VPRTYBW: return "VPRTYBW";
		case PPC_MNEM_VREFP: return "VREFP";
		case PPC_MNEM_VRFIM: return "VRFIM";
		case PPC_MNEM_VRFIN: return "VRFIN";
		case PPC_MNEM_VRFIP: return "VRFIP";
		case PPC_MNEM_VRFIZ: return "VRFIZ";
		case PPC_MNEM_VRLB: return "VRLB";
		case PPC_MNEM_VRLD: return "VRLD";
		case PPC_MNEM_VRLDMI: return "VRLDMI";
		case PPC_MNEM_VRLDNM: return "VRLDNM";
		case PPC_MNEM_VRLH: return "VRLH";
		case PPC_MNEM_VRLW: return "VRLW";
		case PPC_MNEM_VRLWMI: return "VRLWMI";
		case PPC_MNEM_VRLWNM: return "VRLWNM";
		case PPC_MNEM_VRSQRTEFP: return "VRSQRTEFP";
		case PPC_MNEM_VSBOX: return "VSBOX";
		case PPC_MNEM_VSEL: return "VSEL";
		case PPC_MNEM_VSHASIGMAD: return "VSHASIGMAD";
		case PPC_MNEM_VSHASIGMAW: return "VSHASIGMAW";
		case PPC_MNEM_VSL: return "VSL";
		case PPC_MNEM_VSLB: return "VSLB";
		case PPC_MNEM_VSLD: return "VSLD";
		case PPC_MNEM_VSLDOI: return "VSLDOI";
		case PPC_MNEM_VSLH: return "VSLH";
		case PPC_MNEM_VSLO: return "VSLO";
		case PPC_MNEM_VSLV: return "VSLV";
		case PPC_MNEM_VSLW: return "VSLW";
		case PPC_MNEM_VSPLTB: return "VSPLTB";
		case PPC_MNEM_VSPLTH: return "VSPLTH";
		case PPC_MNEM_VSPLTISB: return "VSPLTISB";
		case PPC_MNEM_VSPLTISH: return "VSPLTISH";
		case PPC_MNEM_VSPLTISW: return "VSPLTISW";
		case PPC_MNEM_VSPLTW: return "VSPLTW";
		case PPC_MNEM_VSR: return "VSR";
		case PPC_MNEM_VSRAB: return "VSRAB";
		case PPC_MNEM_VSRAD: return "VSRAD";
		case PPC_MNEM_VSRAH: return "VSRAH";
		case PPC_MNEM_VSRAW: return "VSRAW";
		case PPC_MNEM_VSRB: return "VSRB";
		case PPC_MNEM_VSRD: return "VSRD";
		case PPC_MNEM_VSRH: return "VSRH";
		case PPC_MNEM_VSRO: return "VSRO";
		case PPC_MNEM_VSRV: return "VSRV";
		case PPC_MNEM_VSRW: return "VSRW";
		case PPC_MNEM_VSUBCUQ: return "VSUBCUQ";
		case PPC_MNEM_VSUBCUW: return "VSUBCUW";
		case PPC_MNEM_VSUBECUQ: return "VSUBECUQ";
		case PPC_MNEM_VSUBEUQM: return "VSUBEUQM";
		case PPC_MNEM_VSUBFP: return "VSUBFP";
		case PPC_MNEM_VSUBSBS: return "VSUBSBS";
		case PPC_MNEM_VSUBSHS: return "VSUBSHS";
		case PPC_MNEM_VSUBSWS: return "VSUBSWS";
		case PPC_MNEM_VSUBUBM: return "VSUBUBM";
		case PPC_MNEM_VSUBUBS: return "VSUBUBS";
		case PPC_MNEM_VSUBUDM: return "VSUBUDM";
		case PPC_MNEM_VSUBUHM: return "VSUBUHM";
		case PPC_MNEM_VSUBUHS: return "VSUBUHS";
		case PPC_MNEM_VSUBUQM: return "VSUBUQM";
		case PPC_MNEM_VSUBUWM: return "VSUBUWM";
		case PPC_MNEM_VSUBUWS: return "VSUBUWS";
		case PPC_MNEM_VSUM2SWS: return "VSUM2SWS";
		case PPC_MNEM_VSUM4SBS: return "VSUM4SBS";
		case PPC_MNEM_VSUM4SHS: return "VSUM4SHS";
		case PPC_MNEM_VSUM4UBS: return "VSUM4UBS";
		case PPC_MNEM_VSUMSWS: return "VSUMSWS";
		case PPC_MNEM_VUPKHPX: return "VUPKHPX";
		case PPC_MNEM_VUPKHSB: return "VUPKHSB";
		case PPC_MNEM_VUPKHSH: return "VUPKHSH";
		case PPC_MNEM_VUPKHSW: return "VUPKHSW";
		case PPC_MNEM_VUPKLPX: return "VUPKLPX";
		case PPC_MNEM_VUPKLSB: return "VUPKLSB";
		case PPC_MNEM_VUPKLSH: return "VUPKLSH";
		case PPC_MNEM_VUPKLSW: return "VUPKLSW";
		case PPC_MNEM_VXOR: return "VXOR";
		case PPC_MNEM_WAIT: return "WAIT";
		case PPC_MNEM_WAITIMPL: return "WAITIMPL";
		case PPC_MNEM_WAITRSV: return "WAITRSV";
		case PPC_MNEM_WCHKALL: return "WCHKALL";
		case PPC_MNEM_WCLR: return "WCLR";
		case PPC_MNEM_WCLRALL: return "WCLRALL";
		case PPC_MNEM_WCLRONE: return "WCLRONE";
		case PPC_MNEM_WRTEE: return "WRTEE";
		case PPC_MNEM_WRTEEI: return "WRTEEI";
		case PPC_MNEM_XNOP: return "XNOP";
		case PPC_MNEM_XOR: return "XOR";
		case PPC_MNEM_XORI: return "XORI";
		case PPC_MNEM_XORIS: return "XORIS";
		case PPC_MNEM_XSABSDP: return "XSABSDP";
		case PPC_MNEM_XSABSQP: return "XSABSQP";
		case PPC_MNEM_XSADDDP: return "XSADDDP";
		case PPC_MNEM_XSADDQP: return "XSADDQP";
		case PPC_MNEM_XSADDQPO: return "XSADDQPO";
		case PPC_MNEM_XSADDSP: return "XSADDSP";
		case PPC_MNEM_XSCMPEQDP: return "XSCMPEQDP";
		case PPC_MNEM_XSCMPEXPDP: return "XSCMPEXPDP";
		case PPC_MNEM_XSCMPEXPQP: return "XSCMPEXPQP";
		case PPC_MNEM_XSCMPGEDP: return "XSCMPGEDP";
		case PPC_MNEM_XSCMPGTDP: return "XSCMPGTDP";
		case PPC_MNEM_XSCMPODP: return "XSCMPODP";
		case PPC_MNEM_XSCMPOQP: return "XSCMPOQP";
		case PPC_MNEM_XSCMPUDP: return "XSCMPUDP";
		case PPC_MNEM_XSCMPUQP: return "XSCMPUQP";
		case PPC_MNEM_XSCPSGNDP: return "XSCPSGNDP";
		case PPC_MNEM_XSCPSGNQP: return "XSCPSGNQP";
		case PPC_MNEM_XSCVDPHP: return "XSCVDPHP";
		case PPC_MNEM_XSCVDPQP: return "XSCVDPQP";
		case PPC_MNEM_XSCVDPSP: return "XSCVDPSP";
		case PPC_MNEM_XSCVDPSPN: return "XSCVDPSPN";
		case PPC_MNEM_XSCVDPSXDS: return "XSCVDPSXDS";
		case PPC_MNEM_XSCVDPSXWS: return "XSCVDPSXWS";
		case PPC_MNEM_XSCVDPUXDS: return "XSCVDPUXDS";
		case PPC_MNEM_XSCVDPUXWS: return "XSCVDPUXWS";
		case PPC_MNEM_XSCVHPDP: return "XSCVHPDP";
		case PPC_MNEM_XSCVQPDP: return "XSCVQPDP";
		case PPC_MNEM_XSCVQPDPO: return "XSCVQPDPO";
		case PPC_MNEM_XSCVQPSDZ: return "XSCVQPSDZ";
		case PPC_MNEM_XSCVQPSWZ: return "XSCVQPSWZ";
		case PPC_MNEM_XSCVQPUDZ: return "XSCVQPUDZ";
		case PPC_MNEM_XSCVQPUWZ: return "XSCVQPUWZ";
		case PPC_MNEM_XSCVSDQP: return "XSCVSDQP";
		case PPC_MNEM_XSCVSPDP: return "XSCVSPDP";
		case PPC_MNEM_XSCVSPDPN: return "XSCVSPDPN";
		case PPC_MNEM_XSCVSXDDP: return "XSCVSXDDP";
		case PPC_MNEM_XSCVSXDSP: return "XSCVSXDSP";
		case PPC_MNEM_XSCVUDQP: return "XSCVUDQP";
		case PPC_MNEM_XSCVUXDDP: return "XSCVUXDDP";
		case PPC_MNEM_XSCVUXDSP: return "XSCVUXDSP";
		case PPC_MNEM_XSDIVDP: return "XSDIVDP";
		case PPC_MNEM_XSDIVQP: return "XSDIVQP";
		case PPC_MNEM_XSDIVQPO: return "XSDIVQPO";
		case PPC_MNEM_XSDIVSP: return "XSDIVSP";
		case PPC_MNEM_XSIEXPDP: return "XSIEXPDP";
		case PPC_MNEM_XSIEXPQP: return "XSIEXPQP";
		case PPC_MNEM_XSMADDADP: return "XSMADDADP";
		case PPC_MNEM_XSMADDASP: return "XSMADDASP";
		case PPC_MNEM_XSMADDMDP: return "XSMADDMDP";
		case PPC_MNEM_XSMADDMSP: return "XSMADDMSP";
		case PPC_MNEM_XSMADDQP: return "XSMADDQP";
		case PPC_MNEM_XSMADDQPO: return "XSMADDQPO";
		case PPC_MNEM_XSMAXCDP: return "XSMAXCDP";
		case PPC_MNEM_XSMAXDP: return "XSMAXDP";
		case PPC_MNEM_XSMAXJDP: return "XSMAXJDP";
		case PPC_MNEM_XSMINCDP: return "XSMINCDP";
		case PPC_MNEM_XSMINDP: return "XSMINDP";
		case PPC_MNEM_XSMINJDP: return "XSMINJDP";
		case PPC_MNEM_XSMSUBADP: return "XSMSUBADP";
		case PPC_MNEM_XSMSUBASP: return "XSMSUBASP";
		case PPC_MNEM_XSMSUBMDP: return "XSMSUBMDP";
		case PPC_MNEM_XSMSUBMSP: return "XSMSUBMSP";
		case PPC_MNEM_XSMSUBQP: return "XSMSUBQP";
		case PPC_MNEM_XSMSUBQPO: return "XSMSUBQPO";
		case PPC_MNEM_XSMULDP: return "XSMULDP";
		case PPC_MNEM_XSMULQP: return "XSMULQP";
		case PPC_MNEM_XSMULQPO: return "XSMULQPO";
		case PPC_MNEM_XSMULSP: return "XSMULSP";
		case PPC_MNEM_XSNABSDP: return "XSNABSDP";
		case PPC_MNEM_XSNABSQP: return "XSNABSQP";
		case PPC_MNEM_XSNEGDP: return "XSNEGDP";
		case PPC_MNEM_XSNEGQP: return "XSNEGQP";
		case PPC_MNEM_XSNMADDADP: return "XSNMADDADP";
		case PPC_MNEM_XSNMADDASP: return "XSNMADDASP";
		case PPC_MNEM_XSNMADDMDP: return "XSNMADDMDP";
		case PPC_MNEM_XSNMADDMSP: return "XSNMADDMSP";
		case PPC_MNEM_XSNMADDQP: return "XSNMADDQP";
		case PPC_MNEM_XSNMADDQPO: return "XSNMADDQPO";
		case PPC_MNEM_XSNMSUBADP: return "XSNMSUBADP";
		case PPC_MNEM_XSNMSUBASP: return "XSNMSUBASP";
		case PPC_MNEM_XSNMSUBMDP: return "XSNMSUBMDP";
		case PPC_MNEM_XSNMSUBMSP: return "XSNMSUBMSP";
		case PPC_MNEM_XSNMSUBQP: return "XSNMSUBQP";
		case PPC_MNEM_XSNMSUBQPO: return "XSNMSUBQPO";
		case PPC_MNEM_XSRDPI: return "XSRDPI";
		case PPC_MNEM_XSRDPIC: return "XSRDPIC";
		case PPC_MNEM_XSRDPIM: return "XSRDPIM";
		case PPC_MNEM_XSRDPIP: return "XSRDPIP";
		case PPC_MNEM_XSRDPIZ: return "XSRDPIZ";
		case PPC_MNEM_XSREDP: return "XSREDP";
		case PPC_MNEM_XSRESP: return "XSRESP";
		case PPC_MNEM_XSRQPI: return "XSRQPI";
		case PPC_MNEM_XSRQPIX: return "XSRQPIX";
		case PPC_MNEM_XSRQPXP: return "XSRQPXP";
		case PPC_MNEM_XSRSP: return "XSRSP";
		case PPC_MNEM_XSRSQRTEDP: return "XSRSQRTEDP";
		case PPC_MNEM_XSRSQRTESP: return "XSRSQRTESP";
		case PPC_MNEM_XSSQRTDP: return "XSSQRTDP";
		case PPC_MNEM_XSSQRTQP: return "XSSQRTQP";
		case PPC_MNEM_XSSQRTQPO: return "XSSQRTQPO";
		case PPC_MNEM_XSSQRTSP: return "XSSQRTSP";
		case PPC_MNEM_XSSUBDP: return "XSSUBDP";
		case PPC_MNEM_XSSUBQP: return "XSSUBQP";
		case PPC_MNEM_XSSUBQPO: return "XSSUBQPO";
		case PPC_MNEM_XSSUBSP: return "XSSUBSP";
		case PPC_MNEM_XSTDIVDP: return "XSTDIVDP";
		case PPC_MNEM_XSTSQRTDP: return "XSTSQRTDP";
		case PPC_MNEM_XSTSTDCDP: return "XSTSTDCDP";
		case PPC_MNEM_XSTSTDCQP: return "XSTSTDCQP";
		case PPC_MNEM_XSTSTDCSP: return "XSTSTDCSP";
		case PPC_MNEM_XSXEXPDP: return "XSXEXPDP";
		case PPC_MNEM_XSXEXPQP: return "XSXEXPQP";
		case PPC_MNEM_XSXSIGDP: return "XSXSIGDP";
		case PPC_MNEM_XSXSIGQP: return "XSXSIGQP";
		case PPC_MNEM_XVABSDP: return "XVABSDP";
		case PPC_MNEM_XVABSSP: return "XVABSSP";
		case PPC_MNEM_XVADDDP: return "XVADDDP";
		case PPC_MNEM_XVADDSP: return "XVADDSP";
		case PPC_MNEM_XVCMPEQDP: return "XVCMPEQDP";
		case PPC_MNEM_XVCMPEQSP: return "XVCMPEQSP";
		case PPC_MNEM_XVCMPGEDP: return "XVCMPGEDP";
		case PPC_MNEM_XVCMPGESP: return "XVCMPGESP";
		case PPC_MNEM_XVCMPGTDP: return "XVCMPGTDP";
		case PPC_MNEM_XVCMPGTSP: return "XVCMPGTSP";
		case PPC_MNEM_XVCPSGNDP: return "XVCPSGNDP";
		case PPC_MNEM_XVCPSGNSP: return "XVCPSGNSP";
		case PPC_MNEM_XVCVDPSP: return "XVCVDPSP";
		case PPC_MNEM_XVCVDPSXDS: return "XVCVDPSXDS";
		case PPC_MNEM_XVCVDPSXWS: return "XVCVDPSXWS";
		case PPC_MNEM_XVCVDPUXDS: return "XVCVDPUXDS";
		case PPC_MNEM_XVCVDPUXWS: return "XVCVDPUXWS";
		case PPC_MNEM_XVCVHPSP: return "XVCVHPSP";
		case PPC_MNEM_XVCVSPDP: return "XVCVSPDP";
		case PPC_MNEM_XVCVSPHP: return "XVCVSPHP";
		case PPC_MNEM_XVCVSPSXDS: return "XVCVSPSXDS";
		case PPC_MNEM_XVCVSPSXWS: return "XVCVSPSXWS";
		case PPC_MNEM_XVCVSPUXDS: return "XVCVSPUXDS";
		case PPC_MNEM_XVCVSPUXWS: return "XVCVSPUXWS";
		case PPC_MNEM_XVCVSXDDP: return "XVCVSXDDP";
		case PPC_MNEM_XVCVSXDSP: return "XVCVSXDSP";
		case PPC_MNEM_XVCVSXWDP: return "XVCVSXWDP";
		case PPC_MNEM_XVCVSXWSP: return "XVCVSXWSP";
		case PPC_MNEM_XVCVUXDDP: return "XVCVUXDDP";
		case PPC_MNEM_XVCVUXDSP: return "XVCVUXDSP";
		case PPC_MNEM_XVCVUXWDP: return "XVCVUXWDP";
		case PPC_MNEM_XVCVUXWSP: return "XVCVUXWSP";
		case PPC_MNEM_XVDIVDP: return "XVDIVDP";
		case PPC_MNEM_XVDIVSP: return "XVDIVSP";
		case PPC_MNEM_XVIEXPDP: return "XVIEXPDP";
		case PPC_MNEM_XVIEXPSP: return "XVIEXPSP";
		case PPC_MNEM_XVMADDADP: return "XVMADDADP";
		case PPC_MNEM_XVMADDASP: return "XVMADDASP";
		case PPC_MNEM_XVMADDMDP: return "XVMADDMDP";
		case PPC_MNEM_XVMADDMSP: return "XVMADDMSP";
		case PPC_MNEM_XVMAXDP: return "XVMAXDP";
		case PPC_MNEM_XVMAXSP: return "XVMAXSP";
		case PPC_MNEM_XVMINDP: return "XVMINDP";
		case PPC_MNEM_XVMINSP: return "XVMINSP";
		case PPC_MNEM_XVMOVDP: return "XVMOVDP";
		case PPC_MNEM_XVMOVSP: return "XVMOVSP";
		case PPC_MNEM_XVMSUBADP: return "XVMSUBADP";
		case PPC_MNEM_XVMSUBASP: return "XVMSUBASP";
		case PPC_MNEM_XVMSUBMDP: return "XVMSUBMDP";
		case PPC_MNEM_XVMSUBMSP: return "XVMSUBMSP";
		case PPC_MNEM_XVMULDP: return "XVMULDP";
		case PPC_MNEM_XVMULSP: return "XVMULSP";
		case PPC_MNEM_XVNABSDP: return "XVNABSDP";
		case PPC_MNEM_XVNABSSP: return "XVNABSSP";
		case PPC_MNEM_XVNEGDP: return "XVNEGDP";
		case PPC_MNEM_XVNEGSP: return "XVNEGSP";
		case PPC_MNEM_XVNMADDADP: return "XVNMADDADP";
		case PPC_MNEM_XVNMADDASP: return "XVNMADDASP";
		case PPC_MNEM_XVNMADDMDP: return "XVNMADDMDP";
		case PPC_MNEM_XVNMADDMSP: return "XVNMADDMSP";
		case PPC_MNEM_XVNMSUBADP: return "XVNMSUBADP";
		case PPC_MNEM_XVNMSUBASP: return "XVNMSUBASP";
		case PPC_MNEM_XVNMSUBMDP: return "XVNMSUBMDP";
		case PPC_MNEM_XVNMSUBMSP: return "XVNMSUBMSP";
		case PPC_MNEM_XVRDPI: return "XVRDPI";
		case PPC_MNEM_XVRDPIC: return "XVRDPIC";
		case PPC_MNEM_XVRDPIM: return "XVRDPIM";
		case PPC_MNEM_XVRDPIP: return "XVRDPIP";
		case PPC_MNEM_XVRDPIZ: return "XVRDPIZ";
		case PPC_MNEM_XVREDP: return "XVREDP";
		case PPC_MNEM_XVRESP: return "XVRESP";
		case PPC_MNEM_XVRSPI: return "XVRSPI";
		case PPC_MNEM_XVRSPIC: return "XVRSPIC";
		case PPC_MNEM_XVRSPIM: return "XVRSPIM";
		case PPC_MNEM_XVRSPIP: return "XVRSPIP";
		case PPC_MNEM_XVRSPIZ: return "XVRSPIZ";
		case PPC_MNEM_XVRSQRTEDP: return "XVRSQRTEDP";
		case PPC_MNEM_XVRSQRTESP: return "XVRSQRTESP";
		case PPC_MNEM_XVSQRTDP: return "XVSQRTDP";
		case PPC_MNEM_XVSQRTSP: return "XVSQRTSP";
		case PPC_MNEM_XVSUBDP: return "XVSUBDP";
		case PPC_MNEM_XVSUBSP: return "XVSUBSP";
		case PPC_MNEM_XVTDIVDP: return "XVTDIVDP";
		case PPC_MNEM_XVTDIVSP: return "XVTDIVSP";
		case PPC_MNEM_XVTSQRTDP: return "XVTSQRTDP";
		case PPC_MNEM_XVTSQRTSP: return "XVTSQRTSP";
		case PPC_MNEM_XVTSTDCDP: return "XVTSTDCDP";
		case PPC_MNEM_XVTSTDCSP: return "XVTSTDCSP";
		case PPC_MNEM_XVXEXPDP: return "XVXEXPDP";
		case PPC_MNEM_XVXEXPSP: return "XVXEXPSP";
		case PPC_MNEM_XVXSIGDP: return "XVXSIGDP";
		case PPC_MNEM_XVXSIGSP: return "XVXSIGSP";
		case PPC_MNEM_XXBRD: return "XXBRD";
		case PPC_MNEM_XXBRH: return "XXBRH";
		case PPC_MNEM_XXBRQ: return "XXBRQ";
		case PPC_MNEM_XXBRW: return "XXBRW";
		case PPC_MNEM_XXEXTRACTUW: return "XXEXTRACTUW";
		case PPC_MNEM_XXINSERTW: return "XXINSERTW";
		case PPC_MNEM_XXLAND: return "XXLAND";
		case PPC_MNEM_XXLANDC: return "XXLANDC";
		case PPC_MNEM_XXLEQV: return "XXLEQV";
		case PPC_MNEM_XXLNAND: return "XXLNAND";
		case PPC_MNEM_XXLNOR: return "XXLNOR";
		case PPC_MNEM_XXLOR: return "XXLOR";
		case PPC_MNEM_XXLORC: return "XXLORC";
		case PPC_MNEM_XXLXOR: return "XXLXOR";
		case PPC_MNEM_XXMRGHD: return "XXMRGHD";
		case PPC_MNEM_XXMRGHW: return "XXMRGHW";
		case PPC_MNEM_XXMRGLD: return "XXMRGLD";
		case PPC_MNEM_XXMRGLW: return "XXMRGLW";
		case PPC_MNEM_XXPERM: return "XXPERM";
		case PPC_MNEM_XXPERMDI: return "XXPERMDI";
		case PPC_MNEM_XXPERMR: return "XXPERMR";
		case PPC_MNEM_XXSEL: return "XXSEL";
		case PPC_MNEM_XXSLDWI: return "XXSLDWI";
		case PPC_MNEM_XXSPLTD: return "XXSPLTD";
		case PPC_MNEM_XXSPLTIB: return "XXSPLTIB";
		case PPC_MNEM_XXSPLTW: return "XXSPLTW";
		case PPC_MNEM_XXSWAPD: return "XXSWAPD";
		case PPC_MNEM_YIELD: return "YIELD";
		default: return "ERROR";
	}
}

int ppc_disassemble(uint32_t insword, char *result)
{
	struct ppc_decoded dec;

	if(ppc_decode(insword, &dec))
		return -1;

	if(!(dec.mnemonic > PPC_MNEM_NONE && dec.mnemonic < PPC_MNEM_LAST_ENTRY))
		return -1;

	strcpy(result, mnem_to_str(dec.mnemonic));
	
	char buf[128] = {'\0'};
	switch(dec.operand_fmtstr) {
		case PPC_FMTSTR_GPR:
			sprintf(buf, "r%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_C_GPR:
			sprintf(buf, "r%d,0x%X,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_LPAREN_GPR_RPAREN_:
			sprintf(buf, "r%d,0x%X(r%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_NUM:
			sprintf(buf, "r%d,r%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__NEG_:
			sprintf(buf, "-");
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_GPR:
			sprintf(buf, "r%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_GPR:
			sprintf(buf, "r%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_FREG_C_FREG:
			sprintf(buf, "f%d,f%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR__POS_NUM_C_FLAG:
			sprintf(buf, "+0x%X,flag_names[%d]", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_VREG:
			sprintf(buf, "v%d,v%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_C_GPR_C_GPR:
			sprintf(buf, "0x%X,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FLAG_C_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "flag_names[%d],0x%X*cr%d+flag_names[%d],0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5], dec.operand_values[6]);
			break;
		case PPC_FMTSTR_FREG_C_NUM_LPAREN_GPR_RPAREN_:
			sprintf(buf, "f%d,0x%X(r%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_FREG_C_FREG_C_FREG:
			sprintf(buf, "f%d,f%d,f%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_FREG_C_NUM:
			sprintf(buf, "f%d,0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG_C_VSREG:
			sprintf(buf, "vs%d,vs%d,vs%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_VREG:
			sprintf(buf, "v%d,v%d,v%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__NEG_CREG_C_NUM:
			sprintf(buf, "-cr%d,0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR__POS_CREG_C_NUM:
			sprintf(buf, "+cr%d,0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG:
			sprintf(buf, "vs%d,vs%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_FREG_C_GPR_C_GPR:
			sprintf(buf, "f%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_NUM_C_GPR:
			sprintf(buf, "f%d,0x%X,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_GPR:
			sprintf(buf, "f%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_NUM:
			sprintf(buf, "0x%X*cr%d+flag_names[%d],0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_FLAG_C_NUM:
			sprintf(buf, "flag_names[%d],0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_LPAREN_NUM_RPAREN_:
			sprintf(buf, "r%d,0x%X(0x%X)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__POS_NUM_C_FLAG_C_NUM:
			sprintf(buf, "+0x%X,flag_names[%d],0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_FLAG_C_NUM:
			sprintf(buf, "0x%X,flag_names[%d],0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_NUM_C_NUM:
			sprintf(buf, "0x%X,0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_C_GPR_C_NUM:
			sprintf(buf, "r%d,0x%X,r%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR__POS_:
			sprintf(buf, "+");
			break;
		case PPC_FMTSTR_NUM_C_GPR_C_NUM:
			sprintf(buf, "0x%X,r%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__POS_NUM_C_NUM_MUL_CREG_POS_FLAG_C_NUM:
			sprintf(buf, "+0x%X,0x%X*cr%d+flag_names[%d],0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_VREG_C_NUM:
			sprintf(buf, "v%d,0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM:
			sprintf(buf, "0x%X", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_VREG_C_VREG:
			sprintf(buf, "v%d,v%d,v%d,v%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_CREG_C_VSREG_C_VSREG:
			sprintf(buf, "cr%d,vs%d,vs%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_NUM:
			sprintf(buf, "r%d,0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG_C_FLAG:
			sprintf(buf, "0x%X*cr%d+flag_names[%d],0x%X*cr%d+flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5], dec.operand_values[6]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_GPR_C_NUM_C_NUM:
			sprintf(buf, "r%d,r%d,r%d,0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_VREG_C_GPR_C_GPR:
			sprintf(buf, "v%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__NEG_NUM_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "-0x%X,0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR__NEG_NUM:
			sprintf(buf, "-0x%X", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_FLAG_C_FLAG_C_FLAG:
			sprintf(buf, "flag_names[%d],flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_FREG_C_FREG:
			sprintf(buf, "f%d,f%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG_C_FREG_C_NUM:
			sprintf(buf, "f%d,f%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FLAG_C_FLAG:
			sprintf(buf, "flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_NUM:
			sprintf(buf, "v%d,v%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_CREG_C_NUM:
			sprintf(buf, "cr%d,0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG_C_VSREG_C_NUM:
			sprintf(buf, "vs%d,vs%d,vs%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR__POS_CREG:
			sprintf(buf, "+cr%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_NUM_C_FREG_C_FREG:
			sprintf(buf, "0x%X,f%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__POS_NUM:
			sprintf(buf, "+0x%X", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_FLAG:
			sprintf(buf, "flag_names[%d]", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_VSREG_C_GPR_C_GPR:
			sprintf(buf, "vs%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_GPR:
			sprintf(buf, "0x%X,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_VREG:
			sprintf(buf, "r%d,r%d,v%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__NEG_CREG:
			sprintf(buf, "-cr%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR__NEG_NUM_C_NUM_MUL_CREG_POS_FLAG_C_NUM:
			sprintf(buf, "-0x%X,0x%X*cr%d+flag_names[%d],0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_FREG_C_FREG_C_FREG_C_NUM:
			sprintf(buf, "f%d,f%d,f%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_CREG:
			sprintf(buf, "cr%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_NUM_C_NUM_C_NUM:
			sprintf(buf, "r%d,r%d,0x%X,0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_FREG_C_NUM_LPAREN_NUM_RPAREN_:
			sprintf(buf, "f%d,0x%X(0x%X)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FLAG_C_NUM_MUL_CREG_POS_FLAG_C_FLAG:
			sprintf(buf, "flag_names[%d],0x%X*cr%d+flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_CREG_C_NUM_C_GPR_C_GPR:
			sprintf(buf, "cr%d,0x%X,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "0x%X*cr%d+flag_names[%d],0x%X*cr%d+flag_names[%d],0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5], dec.operand_values[6], dec.operand_values[7], dec.operand_values[8]);
			break;
		case PPC_FMTSTR__POS_NUM_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "+0x%X,0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_VSREG_C_NUM_C_GPR:
			sprintf(buf, "vs%d,0x%X,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_NUM_LPAREN_NUM_RPAREN_:
			sprintf(buf, "vs%d,0x%X(0x%X)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_CREG_C_NUM_C_FREG:
			sprintf(buf, "cr%d,0x%X,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_NUM_C_NUM:
			sprintf(buf, "r%d,r%d,0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR__NEG_NUM_C_FLAG:
			sprintf(buf, "-0x%X,flag_names[%d]", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_NUM_C_GPR:
			sprintf(buf, "v%d,0x%X,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR__POS_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "+0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG_C_NUM:
			sprintf(buf, "vs%d,vs%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_NUM:
			sprintf(buf, "vs%d,0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_FCREG_C_GPR_C_GPR:
			sprintf(buf, "Fcr%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_NUM_MUL_CREG_POS_FLAG_C_NUM:
			sprintf(buf, "0x%X,0x%X*cr%d+flag_names[%d],0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_VREG:
			sprintf(buf, "v%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_CREG_C_FREG_C_FREG:
			sprintf(buf, "cr%d,f%d,f%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "0x%X*cr%d+flag_names[%d],0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5]);
			break;
		case PPC_FMTSTR_GPR_C_VREG:
			sprintf(buf, "r%d,v%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_VREG_C_NUM:
			sprintf(buf, "v%d,v%d,v%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_CREG_C_FREG_C_NUM:
			sprintf(buf, "cr%d,f%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VREG_C_NUM_LPAREN_GPR_RPAREN_:
			sprintf(buf, "v%d,0x%X(r%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_CREG_C_GPR_C_GPR:
			sprintf(buf, "cr%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_NUM_LPAREN_GPR_RPAREN_:
			sprintf(buf, "vs%d,0x%X(r%d)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "0x%X*cr%d+flag_names[%d],flag_names[%d],0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4], dec.operand_values[5], dec.operand_values[6]);
			break;
		case PPC_FMTSTR_CREG_C_GPR_C_NUM:
			sprintf(buf, "cr%d,r%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_FREG_C_FREG_C_NUM:
			sprintf(buf, "0x%X,f%d,f%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_GPR_C_NUM:
			sprintf(buf, "r%d,r%d,r%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_NUM_C_NUM:
			sprintf(buf, "0x%X,0x%X", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_CREG_C_VSREG_C_NUM:
			sprintf(buf, "cr%d,vs%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_GPR_C_VSREG:
			sprintf(buf, "r%d,vs%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_FLAG:
			sprintf(buf, "0x%X*cr%d+flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_FREG_C_NUM_LPAREN_GPR_RPAREN__C_NUM_C_NUM:
			sprintf(buf, "f%d,0x%X(r%d),0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR__POS_FLAG:
			sprintf(buf, "+flag_names[%d]", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_GPR_C_FREG:
			sprintf(buf, "r%d,f%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_NUM_MUL_CREG_POS_FLAG_C_FLAG_C_FLAG:
			sprintf(buf, "0x%X*cr%d+flag_names[%d],flag_names[%d],flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_NUM_C_NUM_C_GPR:
			sprintf(buf, "0x%X,0x%X,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_CREG_C_FREG:
			sprintf(buf, "cr%d,f%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_GPR_C_GPR_C_GPR_C_GPR:
			sprintf(buf, "r%d,r%d,r%d,r%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_FREG_C_GPR_C_GPR_C_NUM_C_NUM:
			sprintf(buf, "f%d,r%d,r%d,0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR_GPR_C_NUM_C_NUM:
			sprintf(buf, "r%d,0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "flag_names[%d],0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_VREG_C_GPR:
			sprintf(buf, "v%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_FLAG_C_FLAG_C_NUM_MUL_CREG_POS_FLAG:
			sprintf(buf, "flag_names[%d],flag_names[%d],0x%X*cr%d+flag_names[%d]", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3], dec.operand_values[4]);
			break;
		case PPC_FMTSTR__NEG_NUM_C_FLAG_C_NUM:
			sprintf(buf, "-0x%X,flag_names[%d],0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_VSREG_C_GPR:
			sprintf(buf, "vs%d,r%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_NUM_LPAREN_NUM_RPAREN_:
			sprintf(buf, "v%d,0x%X(0x%X)", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_FREG:
			sprintf(buf, "f%d", dec.operand_values[0]);
			break;
		case PPC_FMTSTR_CREG_C_VREG_C_VREG:
			sprintf(buf, "cr%d,v%d,v%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_FREG:
			sprintf(buf, "0x%X,f%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_CREG_C_VREG_C_NUM:
			sprintf(buf, "cr%d,v%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2]);
			break;
		case PPC_FMTSTR_NUM_C_FREG_C_NUM_C_NUM:
			sprintf(buf, "0x%X,f%d,0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_NUM_C_VREG_C_VREG_C_NUM:
			sprintf(buf, "0x%X,v%d,v%d,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_CREG_C_VSREG:
			sprintf(buf, "cr%d,vs%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_CREG_C_CREG:
			sprintf(buf, "cr%d,cr%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_GPR_C_CREG:
			sprintf(buf, "r%d,cr%d", dec.operand_values[0], dec.operand_values[1]);
			break;
		case PPC_FMTSTR_VREG_C_VREG_C_NUM_C_NUM:
			sprintf(buf, "v%d,v%d,0x%X,0x%X", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		case PPC_FMTSTR_VSREG_C_VSREG_C_VSREG_C_VSREG:
			sprintf(buf, "vs%d,vs%d,vs%d,vs%d", dec.operand_values[0], dec.operand_values[1], dec.operand_values[2], dec.operand_values[3]);
			break;
		default:
			break;
	}

	if(buf[0]) {
		strcat(result, " ");
		strcat(result, buf);
	}

	return 0;
}
